### ISSUE TITLE
Panic: event: wrong type in Subscribe got chan

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#10465]
I got panic when starting the beacon node. This will happen if config `BellatrixForkEpoch` has been set to non-max. Looks related to #10413, we are passing in wrong type of channel

```
panic: event: wrong type in Subscribe got chan *state.BlockProcessedData, want chan<- *feed.Event

goroutine 227 [running]:
github.com/prysmaticlabs/prysm/async/event.(*Feed).Subscribe(0xc000ddfc00, {0x528a0c0, 0xc002a2e660})
	async/event/feed.go:86 +0x4ea
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).checkTransitionConfiguration(0xc000030c40, {0x5aa1af0, 0xc0065f4880}, 0xc002a2e660)
	beacon-chain/powchain/check_transition_config.go:62 +0x616
created by github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).Start
	beacon-chain/powchain/service.go:255 +0x30f
```

**Comment by terencechain** [comment]
temporarily assigning to @rauljordan feel free to re-assign
