### ISSUE TITLE
No block in DB when update head

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#10570]
After the transition from the initial(req-resp) syncing to regular(gossip) syncing, we encountered an edge case when the head updates from A -> B.  Prsym node encounters block B is not in the DB. The following two things can happen:
- Update head routine errors out when rebuilding the state
- Update head routine panics if the state exists in cache

The above edge case did not happen in v2.0.6 because prsym node would just no-op when updating the head if the block is not in the DB. v2.1.0 added a new assumption where the head must exist in DB.

To fix the edge case, there are two options:
1. Add back the no-op
2. Make sure we save initial sync cached blocks in DB before updating head
I currently favor 2. 
Another thing we should do is to change DB behavior not to return nil and return an error instead of nil.

**Comment by prestonvanloon** [comment]
This is a high priority issue in v2.1.0. This can lead to occasional crashes of the beacon chain.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2961883]

goroutine 322 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).notifyEngineIfChangedHead(0xc00049c380, {0xb27370, 0xc002cdacc0}, {0xa, 0x3, 0x48, 0xd7, 0x63, 0x4b, 0x9f, ...})
        beacon-chain/blockchain/receive_attestation.go:197 +0x643
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).spawnProcessAttestationsRoutine.func1()
        beacon-chain/blockchain/receive_attestation.go:169 +0x6b4
created by github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).spawnProcessAttestationsRoutine
        beacon-chain/blockchain/receive_attestation.go:115 +0xdd
```
