### ISSUE TITLE
ERROR gRPC panicked! error=runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Teebsio** [prysmaticlabs/prysm#10934]
# 🐞 Bug Report

### Description

When I check to verify that the beacon node has synced successfully to the execution node with this command in different terminal window
"curl http://localhost:3500/eth/v1alpha1/node/eth1/connections"

I get this error
 {"code":2,"message":"runtime error: invalid memory address or nil pointer dereference","details":[]}

 the prysm terminal also shows an error that I have posted bellow in logs and after the error report  the node seems to return to Finished applying state transition & Synced blocks .

### Has this worked before in a previous version?

first time user.

## 🔥 Error

<pre><code>

[2022-06-25 15:34:06] ERROR gRPC panicked! error=runtime error: invalid memory address or nil pointer dereference stack=goroutine 12158917 [running]:
runtime/debug.Stack()
        GOROOT/src/runtime/debug/stack.go:24 +0x65
github.com/prysmaticlabs/prysm/monitoring/tracing.RecoveryHandlerFunc({0x266a750?, 0xc071532720?}, {0x1ee8980?, 0x1d2e280})
        monitoring/tracing/recovery_interceptor_option.go:29 +0x1f7
github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom({0x266a750?, 0xc071532720?}, {0x1ee8980?, 0x1d2e280?}, 0x0?)
        external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:61 +0x36
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1()
        external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:29 +0x7b
panic({0x1ee8980, 0x1d2e280})
        GOROOT/src/runtime/panic.go:838 +0x207
github.com/prysmaticlabs/prysm/beacon-chain/rpc/prysm/v1alpha1/node.(*Server).GetETH1ConnectionStatus(0xc03e816000, {0x208fa80?, 0x1ee5920?}, 0x34a6720?)
        beacon-chain/rpc/prysm/v1alpha1/node/server.go:238 +0xbc
github.com/prysmaticlabs/prysm/proto/prysm/v1alpha1._Node_GetETH1ConnectionStatus_Handler.func1({0x266a750, 0xc071532810}, {0x1f8b900?, 0xc071532750})
        bazel-out/k8-opt/bin/proto/prysm/v1alpha1/go_proto_/github.com/prysmaticlabs/prysm/proto/prysm/v1alpha1/node.pb.go:1283 +0x78
github.com/prysmaticlabs/prysm/beacon-chain/rpc.(*Service).validatorUnaryConnectionInterceptor(0x266a750?, {0x266a750, 0xc071532810}, {0x1f8b900, 0xc071532750}, 0x34a60a0?, 0xc07b3b17a0)
        beacon-chain/rpc/service.go:400 +0x50
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x266a750?, 0xc071532810?}, {0x1f8b900?, 0xc071532750?})
        external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1({0x266a750, 0xc071532720}, {0x1f8b900, 0xc071532750}, 0x0?, 0xc06b9415a0)
        external/com_github_grpc_ecosystem_go_grpc_middleware/tracing/opentracing/server_interceptors.go:34 +0x11e
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x266a750?, 0xc071532720?}, {0x1f8b900?, 0xc071532750?})
        external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1({0x266a750, 0xc071532720}, {0x1f8b900, 0xc071532750}, 0x109a36aa0ac?, 0xc06b9415c0)
        external/com_github_grpc_ecosystem_go_grpc_prometheus/server_metrics.go:107 +0x87
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x266a750?, 0xc071532720?}, {0x1f8b900?, 0xc071532750?})
        external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1({0x266a750?, 0xc071532720?}, {0x1f8b900?, 0xc071532750?}, 0x109a1a2b5b8?, 0xc06b941580?)
        external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:33 +0xc4
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x266a750?, 0xc071532720?}, {0x1f8b900?, 0xc071532750?})
        external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x266a750, 0xc071532720}, {0x1f8b900, 0xc071532750}, 0xc0527e3ae0?, 0x1ee7660?)
        external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:34 +0xbf
github.com/prysmaticlabs/prysm/proto/prysm/v1alpha1._Node_GetETH1ConnectionStatus_Handler({0x202d080?, 0xc03e816000}, {0x266a750, 0xc071532720}, 0xc07bee8720, 0xc000132720)
        bazel-out/k8-opt/bin/proto/prysm/v1alpha1/go_proto_/github.com/prysmaticlabs/prysm/proto/prysm/v1alpha1/node.pb.go:1285 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003e1880, {0x2674a20, 0xc019378000}, 0xc05967d320, 0xc000ce4270, 0x1d46a08, 0x0)
        external/org_golang_google_grpc/server.go:1297 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0003e1880, {0x2674a20, 0xc019378000}, 0xc05967d320, 0x0)
        external/org_golang_google_grpc/server.go:1626 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        external/org_golang_google_grpc/server.go:941 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        external/org_golang_google_grpc/server.go:939 +0x28a

[2022-06-25 15:34:13]  INFO blockchain: Synced new block block=0x5e9611cc... epoch=128574 finalizedEpoch=128572 finalizedRoot=0x52786b29... parentRoot=0xcbb02a6e... slot=4114369 slotInEpoch=1 version=altair
[2022-06-25 15:34:13]  INFO blockchain: Finished applying state transition attestations=108 slot=4114369 syncBitsCount=471
[2022-06-25 15:34:24]  INFO blockchain: Synced new block block=0xffdaca4c... epoch=128574 finalizedEpoch=128572 finalizedRoot=0x52786b29... parentRoot=0x5e9611cc... slot=4114370 slotInEpoch=2 version=altair
[2022-06-25 15:34:24]  INFO blockchain: Finished applying state transition attestations=108 slot=4114370 syncBitsCount=505
[2022-06-25 15:34:38]  INFO blockchain: Synced new block block=0xe6681096... epoch=128574 finalizedEpoch=128572 finalizedRoot=0x52786b29... parentRoot=0xffdaca4c... slot=4114371 slotInEpoch=3 version=altair
[2022-06-25 15:34:38]  INFO blockchain: Finished applying state transition attestations=128 slot=4114371 syncBitsCount=503
[2022-06-25 15:34:45]  INFO p2p: Peer summary activePeers=49 inbound=0 outbound=49
[2022-06-25 15:34:49]  INFO blockchain: Synced new block block=0x752f31f3... epoch=128574 finalizedEpoch=128572 finalizedRoot=0x52786b29... parentRoot=0xe6681096... slot=4114372 slotInEpoch=4 version=altair
[2022-06-25 15:34:49]  INFO blockchain: Finished applying state transition attestations=118 slot=4114372 syncBitsCount=504
[2022-06-25 15:35:00]  INFO blockchain: Synced new block block=0x47df8076... epoch=128574 finalizedEpoch=128572 finalizedRoot=0x52786b29... parentRoot=0x752f31f3... slot=4114373 slotInEpoch=5 version=altair
[2022-06-25 15:35:00]  INFO blockchain: Finished applying state transition attestations=128 slot=4114373 syncBitsCount=506
[2022-06-25 15:35:13]  INFO blockchain: Synced new block block=0x64b87751... epoch=128574 finalizedEpoch=128572 finalizedRoot=0x52786b29... parentRoot=0x47df8076... slot=4114374 slotInEpoch=6 version=altair
[2022-06-25 15:35:13]  INFO blockchain: Finished applying state transition attestations=78 slot=4114374 syncBitsCount=506
[2022-06-25 15:35:24]  INFO blockchain: Synced new block block=0x304417e3... epoch=128574 finalizedEpoch=128572 finalizedRoot=0x52786b29... parentRoot=0x64b87751... slot=4114375 slotInEpoch=7 version=altair
[2022-06-25 15:35:24]  INFO blockchain: Finished applying state transition attestations=128 slot=4114375 syncBitsCount=506
[2022-06-25 15:35:45]  INFO p2p: Peer summary activePeers=46 inbound=0 outbound=46
[2022-06-25 15:35:49]  INFO blockchain: Synced new block block=0xa9c10783... epoch=128574 finalizedEpoch=128572 finalizedRoot=0x52786b29... parentRoot=0x304417e3... slot=4114377 slotInEpoch=9 version=altair
[2022-06-25 15:35:49]  INFO blockchain: Finished applying state transition attestations=128 slot=4114377 syncBitsCount=496
[2022-06-25 15:36:01]  INFO blockchain: Synced new block block=0xf731ea85... epoch=128574 finalizedEpoch=128572 finalizedRoot=0x52786b29... parentRoot=0xa9c10783... slot=4114378 slotInEpoch=10 version=altair
[2022-06-25 15:36:01]  INFO blockchain: Finished applying state transition attestations=128 slot=4114378 syncBitsCount=504
[2022-06-25 15:36:12]  INFO blockchain: Synced new block block=0xd69d8c23... epoch=128574 finalizedEpoch=128572 finalizedRoot=0x52786b29... parentRoot=0xf731ea85... slot=4114379 slotInEpoch=11 version=altair
[2022-06-25 15:36:12]  INFO blockchain: Finished applying state transition attestations=128 slot=4114379 syncBitsCount=505
[2022-06-25 15:36:25]  INFO blockchain: Synced new block block=0xff4f48bc... epoch=128574 finalizedEpoch=128572 finalizedRoot=0x52786b29... parentRoot=0xd69d8c23... slot=4114380 slotInEpoch=12 version=altair
[2022-06-25 15:36:25]  INFO blockchain: Finished applying state transition attestations=68 slot=4114380 syncBitsCount=503
[2022-06-25 15:36:37]  INFO blockchain: Synced new block block=0x05147db1... epoch=128574 finalizedEpoch=128572 finalizedRoot=0x52786b29... parentRoot=0xff4f48bc... slot=4114381 slotInEpoch=13 version=altair
[2022-06-25 15:36:37]  INFO blockchain: Finished applying state transition attestations=128 slot=4114381 syncBitsCount=505
[2022-06-25 15:36:45]  INFO p2p: Peer summary activePeers=45 inbound=0 outbound=45
</code></pre>

## 🌍  Your Environment

**Operating System:**
Windows
<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**
Prysm 2.1.2.
<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by jo-tud** [comment]
I can confirm the exact same bug.

**Comment by c0deright** [comment]
v2.1.3 still affected

**Comment by nisdas** [comment]
@c0deright The patch unfortunately did not make it in time into v2.1.3. However this is indeed fixed in develop, it should be included in our next release.
