### ISSUE TITLE
Could not sign validator registration

### ISSUE THREAD

**Issue by nalepae** [prysmaticlabs/prysm#11507]
# 🐞 Bug Report
- EL Geth version: `v1.10.23`
- BN/VC Prysm version: `v3.1.1`
- MEV-Boost version: `v1.3.2`
- Web3Signer version: `22.8.1-jdk17`

### Description

When running Geth/Prysm/MEV-Boost (and Web3Signer) combo on `mainnet`, with only one key, I get this error on Prysm VC:
```
time="2022-09-28 10:02:27" level=error msg="could not sign validator registration: http: ContentLength=362 with Body length 0" feeRecipient=0x388C818CA8B9251b393131C08a736A67ccB19297 prefix=validator pubkey=0x83ac9977c01b00c54b54f66f562dc40c052f344cf8d2dd3254c52f350a320340a237eb9fa2be2cd71b127c13eb5ee8b8
```

However, I get this in BN logs, which seems normal.
```
time="2022-09-28 07:48:44" level=info msg="Waiting for state to be initialized" prefix=initial-sync
time="2022-09-28 07:48:44" level=info msg="Builder has been configured" endpoint="http://mainnet-mev-boost-debug:18550"
time="2022-09-28 07:48:44" level=warning msg="Outsourcing block construction to external builders adds non-trivial delay to block propagation time.  Builder-constructed blocks or fallback blocks may get orphaned. Use at your own risk!"
```

MEV-Boost logs:
```
time="2022-09-28T09:59:07Z" level=info msg="mev-boost v1.3.2" module=cli
time="2022-09-28T09:59:07Z" level=info msg="using genesis fork version: 0x00000000" module=cli
time="2022-09-28T09:59:07Z" level=info msg="using 1 relays" module=cli relays="[https://0xac6e77dfe25ecd6110b8e780608cce0dab71fdd5ebea22a16c0205200f2f8e2e3ad3b71d3499c54ad14d6c21b41a37ae@boost-relay.flashbots.net]"
time="2022-09-28T09:59:07Z" level=info msg="listening on 0.0.0.0:18550" module=cli
time="2022-09-28T12:04:40Z" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.184968 method=GET module=service path=/eth/v1/builder/status status=200
```

In a normal situation, VC logs should looks like this:
```
time="2022-09-28 07:50:48" level=info msg="Submitted builder validator registration settings for custom builders" prefix=validator
```

Specific configurations:

**BN**:
```
http-mev-relay: http://mainnet-mev-boost-debug:18550
< ... And other values not related to block proposal ... >
```

**VC**:
```
suggested-fee-recipient: 0x388C818CA8B9251b393131C08a736A67ccB19297
enable-builder: true
validators-external-signer-public-keys:
- 0x83ac9977c01b00c54b54f66f562dc40c052f344cf8d2dd3254c52f350a320340a237eb9fa2be2cd71b127c13eb5ee8b8
< ... And other values not related to block proposal ... >
```

**MEV-Boost**:
```
-mainnet
-relay-check
-relays=https://0xac6e77dfe25ecd6110b8e780608cce0dab71fdd5ebea22a16c0205200f2f8e2e3ad3b71d3499c54ad14d6c21b41a37ae@boost-relay.flashbots.net
```

## 🌍  Your Environment

**Operating System:**
I use Docker images over Kubernetes on EKS/AWS.

**Anything else relevant (validator index / public key)?**
I successfully run with the same configuration (to the best of my knowledge) the same combo on Sepolia and Goerli.

**Comment by james-prysm** [comment]
Do you see anything on web3signer? maybe something wasn't properly added in web3signer?

**Comment by nalepae** [comment]
Do you think this issue is related to W3S?
Apart proposing block via MEV-boost, everything goes well:
- Attestations are OK
- Block proposals are OK (but coming from EL)

To be 100% sure this issue does not come from W3S, I will create a `debug` W3S instance especially with only the key I'm trying to get working with Prysm.

**Comment by james-prysm** [comment]
you mentioned you're using > and Web3Signer

since the validator registration needs to be signed it submits it to the Web3signer to sign before submitting the registration requestion to the MEV relay.

**Comment by nalepae** [comment]
OK:

Here is log from Prysm VC:
```
time="2022-09-28 14:13:42" level=error msg="could not sign validator registration: http: ContentLength=362 with Body length 0" feeRecipient=0x388C818CA8B9251b393131C08a736A67ccB19297 prefix=validator pubkey=0x83ac9977c01b00c54b54f66f562dc40c052f344cf8d2dd3254c52f350a320340a237eb9fa2be2cd71b127c13eb5ee8b8
```

And, at the same timestamp, log from Web3Signer:
```
2022-09-28 14:13:42.483+00:00 | vert.x-eventloop-thread-0 | ERROR | LogErrorHandler | Failed request: http://mainnet-web3signer-debug.ethereum-web3signer:9000/api/v1/eth2/sign/0x83ac9977c01b00c54b54f66f562dc40c052f344cf8d2dd3254c52f350a320340a237eb9fa2be2cd71b127c13eb5ee8b8
java.lang.IllegalArgumentException: Signing root 0x5c9620a66902da4a7fb804384c48ec41addacc1884862020058d4bb1300e7e53 must match signing computed signing root 0x93b10c0ddc8a81dc89d3f30e7ccc85c7e5a20eb75d67bbb2a0ddb486b8f7c51d from data
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:435) ~[guava-31.0.1-jre.jar:?]
	at tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.handle(Eth2SignForIdentifierHandler.java:105) ~[web3signer-core-22.8.1.jar:22.8.1]
	at tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.handle(Eth2SignForIdentifierHandler.java:58) ~[web3signer-core-22.8.1.jar:22.8.1]
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:101) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157) ~[vertx-core-4.3.1.jar:4.3.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
2022-09-28 14:13:42.488+00:00 | vert.x-eventloop-thread-0 | ERROR | RoutingContext | Unhandled exception in router
java.lang.IllegalArgumentException: Signing root 0x5c9620a66902da4a7fb804384c48ec41addacc1884862020058d4bb1300e7e53 must match signing computed signing root 0x93b10c0ddc8a81dc89d3f30e7ccc85c7e5a20eb75d67bbb2a0ddb486b8f7c51d from data
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:435) ~[guava-31.0.1-jre.jar:?]
	at tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.handle(Eth2SignForIdentifierHandler.java:105) ~[web3signer-core-22.8.1.jar:22.8.1]
	at tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.handle(Eth2SignForIdentifierHandler.java:58) ~[web3signer-core-22.8.1.jar:22.8.1]
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:101) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157) ~[vertx-core-4.3.1.jar:4.3.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
2022-09-28 14:14:47.972+00:00 | vert.x-eventloop-thread-0 | ERROR | LogErrorHandler | Failed request: http://mainnet-web3signer-debug.ethereum-web3signer:9000/api/v1/eth2/sign/0x83ac9977c01b00c54b54f66f562dc40c052f344cf8d2dd3254c52f350a320340a237eb9fa2be2cd71b127c13eb5ee8b8
java.lang.IllegalArgumentException: Signing root 0x2f8fbcfa01c214871ceca35feac3c00a90eb963c0a774b3b1059c89f1a488c72 must match signing computed signing root 0x372c32774a163e544671ba1b327e87354c92d8b9b62628071f31911c57985971 from data
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:435) ~[guava-31.0.1-jre.jar:?]
	at tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.handle(Eth2SignForIdentifierHandler.java:105) ~[web3signer-core-22.8.1.jar:22.8.1]
	at tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.handle(Eth2SignForIdentifierHandler.java:58) ~[web3signer-core-22.8.1.jar:22.8.1]
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:101) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157) ~[vertx-core-4.3.1.jar:4.3.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
2022-09-28 14:14:47.973+00:00 | vert.x-eventloop-thread-0 | ERROR | RoutingContext | Unhandled exception in router
java.lang.IllegalArgumentException: Signing root 0x2f8fbcfa01c214871ceca35feac3c00a90eb963c0a774b3b1059c89f1a488c72 must match signing computed signing root 0x372c32774a163e544671ba1b327e87354c92d8b9b62628071f31911c57985971 from data
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:435) ~[guava-31.0.1-jre.jar:?]
	at tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.handle(Eth2SignForIdentifierHandler.java:105) ~[web3signer-core-22.8.1.jar:22.8.1]
	at tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.handle(Eth2SignForIdentifierHandler.java:58) ~[web3signer-core-22.8.1.jar:22.8.1]
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:101) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157) ~[vertx-core-4.3.1.jar:4.3.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

Do you think the issue could come:
- From Prysm?
- From Web3Signer?
- From a bad configuration on my side?

**Comment by james-prysm** [comment]
I'm guessing it's a configuration issue, most likely with web3signer (possibly due to the network it's on?) it looks like it's on mainnet? web3signer does a validator of the schema of the request so guessing it's not the format of the data sent... if it's using the latest we can see if anything changed recently.

**Comment by nalepae** [comment]
You'r right!

Found this in the Web3Signer configuration:
```
eth2.network: prater
```

instead of

```
eth2.network: mainnet
```

Thanks!
