### ISSUE TITLE
Prysm 3.1.1 crash

### ISSUE THREAD

**Issue by wmitsuda** [prysmaticlabs/prysm#11542]
prysm 3.1.1, mainnet/macos/docker:

This is my dev/laptop node, so I stop/start it a lot and then let it catch to the tip.

Today I started it again (after having it synced it up to the tip yesterday night) and it started crashing just a few minutes after start, see logs:

```
[2022-10-04 17:03:51]  INFO Finished reading JWT secret from /erigon-data/jwt.hex
[2022-10-04 17:03:51]  WARN flags: Running on Ethereum Mainnet
[2022-10-04 17:03:51]  INFO node: Checking DB database-path=/datadir/beaconchaindata
[2022-10-04 17:03:51]  INFO db: Opening Bolt DB at /datadir/beaconchaindata/beaconchain.db
[2022-10-04 17:03:51]  INFO node: Deposit contract: 0x00000000219ab540356cbb839cbe05303d7705fa
[2022-10-04 17:04:04]  INFO p2p: Running node with peer id of 16Uiu2HAmLpZ1T4gxtp1pF6B1UZLRxV5QacsQnyE2ZKeMpw8JPs5c
[2022-10-04 17:04:33]  INFO initial-sync: Waiting for state to be initialized
[2022-10-04 17:04:33]  INFO rpc: gRPC server listening on port address=0.0.0.0:4000
[2022-10-04 17:04:33]  WARN rpc: You are using an insecure gRPC server. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: https://docs.prylabs.network/docs/prysm-usage/secure-grpc
[2022-10-04 17:04:33]  INFO node: Starting beacon node version=Prysm/v3.1.1/653ea3b030c3bb99aa3f3d95a8de9f4d6e147930. Built at: 2022-09-09 21:18:25+00:00
[2022-10-04 17:04:33]  INFO blockchain: Blockchain data already exists in DB, initializing...
[2022-10-04 17:04:33]  INFO gateway: Starting API middleware
[2022-10-04 17:04:33]  INFO gateway: Starting gRPC gateway address=0.0.0.0:3500
[2022-10-04 17:04:33]  INFO initial-sync: Starting initial chain sync...
[2022-10-04 17:04:33]  INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=0
[2022-10-04 17:04:33]  INFO p2p: Started discovery v5 ENR=enr:-MK4QIid2t3u9Ojg0g7sVwnyY5pz2C5XvNxv_XzbBhZvIEXqBDQWWcmtyV7SOQWdBKomQ0IlVFN2etKV9Qm3JJ-u58OGAYOj9M54h2F0dG5ldHOIAAAAAAAAAACEZXRoMpBKJsWLAgAAAP__________gmlkgnY0gmlwhKwRAAKJc2VjcDI1NmsxoQN5UKYt-ComBRLg_sIVRyqtDU1QY5Q3AV_flRkYBiPT84hzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A
[2022-10-04 17:04:33]  INFO p2p: Node started p2p server multiAddr=/ip4/172.17.0.2/tcp/13000/p2p/16Uiu2HAmLpZ1T4gxtp1pF6B1UZLRxV5QacsQnyE2ZKeMpw8JPs5c
[2022-10-04 17:04:38]  INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=1
[2022-10-04 17:04:48]  INFO powchain: Connected to new endpoint: http://host.docker.internal:8551
[2022-10-04 17:04:48]  WARN powchain: Execution client is not syncing
[2022-10-04 17:05:00]  WARN powchain: Execution client is not syncing
[2022-10-04 17:05:06]  INFO initial-sync: Processing block batch of size 30 starting from  0x8d8c83df... 4837537/4839923 - estimated time remaining 26m30s blocksPerSecond=1.5 peers=19
[2022-10-04 17:05:14]  WARN powchain: Execution client is not syncing
[2022-10-04 17:05:28]  WARN powchain: Execution client is not syncing
[2022-10-04 17:05:33]  INFO p2p: Peer summary activePeers=30 inbound=0 outbound=30
[2022-10-04 17:05:41]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x233399f3c120 slot=4837537
[2022-10-04 17:05:41]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x7817c78263ce slot=4837538
[2022-10-04 17:05:41]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xd978c355a2f4 slot=4837539
[2022-10-04 17:05:41]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xfd3e4b16e0b3 slot=4837540
[2022-10-04 17:05:41]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xe4b5c3babf49 slot=4837541
[2022-10-04 17:05:41]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x27cc1bf89d17 slot=4837542
[2022-10-04 17:05:41]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x6952685a0bf2 slot=4837543
[2022-10-04 17:05:41]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xce3e9f930d28 slot=4837544
[2022-10-04 17:05:42]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xa68b9ea8c827 slot=4837545
[2022-10-04 17:05:42]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xaab155287922 slot=4837546
[2022-10-04 17:05:42]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x7da6d766dfa3 slot=4837547
[2022-10-04 17:05:42]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x6e5cb882623d slot=4837548
[2022-10-04 17:05:42]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x732ac17ae601 slot=4837549
[2022-10-04 17:05:42]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x098869694de9 slot=4837550
[2022-10-04 17:05:42]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xea3a1fbd7abf slot=4837551
[2022-10-04 17:05:42]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xb3bdb983107c slot=4837552
[2022-10-04 17:05:42]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x06d96d93a8cd slot=4837553
[2022-10-04 17:05:42]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xc0c94cae3ded slot=4837554
[2022-10-04 17:05:42]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x676dab470b02 slot=4837555
[2022-10-04 17:05:42]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xfa5ed727cd3b slot=4837556
[2022-10-04 17:05:42]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xe9b6142d4448 slot=4837557
[2022-10-04 17:05:42]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x2299e2eb5e4d slot=4837558
[2022-10-04 17:05:42]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x743fbdd3182d slot=4837560
[2022-10-04 17:05:42]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xe5eba5e074fd slot=4837561
[2022-10-04 17:05:42]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xa56a090629f2 slot=4837562
[2022-10-04 17:05:42]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x3b60538fb2bc slot=4837563
[2022-10-04 17:05:42]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x158ee1da8818 slot=4837564
[2022-10-04 17:05:42]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xfd333170abc8 slot=4837565
[2022-10-04 17:05:42]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x8b0520b9aee3 slot=4837566
[2022-10-04 17:05:42]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x51a18f9642d0 slot=4837567
[2022-10-04 17:05:42]  INFO blockchain: Called fork choice updated with optimistic block finalizedPayloadBlockHash=0x3eecbe279232 headPayloadBlockHash=0x51a18f9642d0 headSlot=4837567
[2022-10-04 17:05:42]  WARN powchain: Execution client is not syncing
[2022-10-04 17:05:48]  INFO initial-sync: Processing block batch of size 60 starting from  0x4dd34dac... 4837568/4839927 - estimated time remaining 13m6s blocksPerSecond=3.0 peers=30
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xc5e8718cf486 slot=4837568
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xeeab96f9b07a slot=4837569
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x0bb7b14daed2 slot=4837570
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xb6fd131ca575 slot=4837571
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x9fb7d9859260 slot=4837572
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x769bd346adc9 slot=4837573
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xd0934d13b8d0 slot=4837574
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x4d0544651034 slot=4837575
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xb0e71af1072b slot=4837576
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x21acf194d5c8 slot=4837577
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x0f2e8931f1ca slot=4837578
[2022-10-04 17:05:56]  WARN powchain: Execution client is not syncing
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xfc236368208a slot=4837579
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xe9c1dd20dcf7 slot=4837580
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x078c62af47f6 slot=4837581
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x71e154ed8894 slot=4837582
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x54a615e919bf slot=4837583
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x6f0223c20df7 slot=4837584
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xd16240048060 slot=4837585
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xf18fb42e7804 slot=4837586
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x29e7bb0b7f74 slot=4837587
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xb3e02bd0d47f slot=4837588
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x3be1075681cc slot=4837589
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x332896d1a769 slot=4837590
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xa443115a184a slot=4837591
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x7b71b7ff1e8d slot=4837592
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x9be75c66ec08 slot=4837593
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x1fc307886e36 slot=4837594
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xaa685ef23547 slot=4837595
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x5d2c3d3d5a68 slot=4837596
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x26323c274362 slot=4837597
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x509f763a5099 slot=4837598
[2022-10-04 17:05:56]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xf07b476f5d3c slot=4837599
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x7977caf79374 slot=4837600
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xf6f3d69df3b5 slot=4837601
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x94126f04bab3 slot=4837602
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x44c8fca06a0e slot=4837603
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x9bd03968d4bc slot=4837604
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x36d95b28ae0c slot=4837605
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x97b57c00461d slot=4837606
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x5401632b81c6 slot=4837607
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x28be3572b606 slot=4837608
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x18d2a40f64b2 slot=4837609
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x58deaf37399e slot=4837610
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xc4a00efe46c1 slot=4837611
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x052e43dbfa9b slot=4837613
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xcc05b5e46804 slot=4837614
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xce7cd425f4d1 slot=4837615
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x265dccc9712c slot=4837616
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xf67a21935acd slot=4837617
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x0da6180da947 slot=4837618
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x603e066b20e5 slot=4837619
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xf1ae8e63072a slot=4837620
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x34c196daa15f slot=4837621
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x69cb5f9d2586 slot=4837622
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xa8713ef3acf1 slot=4837623
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x332cc239afac slot=4837624
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xcb5f970fc8a2 slot=4837625
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x8ca3c49680e2 slot=4837626
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x887d8a6e276c slot=4837627
[2022-10-04 17:05:57]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0x65fc34b829ac slot=4837628
[2022-10-04 17:05:57]  INFO blockchain: Called fork choice updated with optimistic block finalizedPayloadBlockHash=0xc5e8718cf486 headPayloadBlockHash=0x65fc34b829ac headSlot=4837628
[2022-10-04 17:05:58]  INFO initial-sync: Processing block batch of size 64 starting from  0xf20c71de... 4837632/4839927 - estimated time remaining 6m10s blocksPerSecond=6.2 peers=33
[2022-10-04 17:05:58]  WARN initial-sync: Skip processing batched blocks error=beacon node doesn't have a parent in db with root: 0x6f7982af881e2bc4ef96a02c8a952dd7dcb9a8a6307ab43152bb51bf7859171a (in processBatchedBlocks, slot=4837632)
[2022-10-04 17:05:58]  INFO initial-sync: Processing block batch of size 63 starting from  0x8c5c3318... 4837696/4839927 - estimated time remaining 3m58s blocksPerSecond=9.3 peers=33
[2022-10-04 17:05:58]  WARN initial-sync: Skip processing batched blocks error=beacon node doesn't have a parent in db with root: 0x3f3a2518619b9d3cf6464542f89cfa9d28b0fe330f9b800a5c6de27b2deff07c (in processBatchedBlocks, slot=4837696)
[2022-10-04 17:05:58]  INFO initial-sync: Processing block batch of size 63 starting from  0x219b97d2... 4837760/4839927 - estimated time remaining 2m53s blocksPerSecond=12.5 peers=33
[2022-10-04 17:05:58]  WARN initial-sync: Skip processing batched blocks error=beacon node doesn't have a parent in db with root: 0xf0f3ddfe141422efbc3d0a76463d09574c0c69d06588c11f216d53845633f98d (in processBatchedBlocks, slot=4837760)
[2022-10-04 17:05:58]  INFO initial-sync: Processing block batch of size 63 starting from  0xccedeb0b... 4837824/4839927 - estimated time remaining 2m14s blocksPerSecond=15.7 peers=33
[2022-10-04 17:05:58]  WARN initial-sync: Skip processing batched blocks error=beacon node doesn't have a parent in db with root: 0x5e6e124a254afee4fce760d574db7b6aad3649246541c46bd300763becbef5e9 (in processBatchedBlocks, slot=4837824)
[2022-10-04 17:06:10]  WARN powchain: Execution client is not syncing
[2022-10-04 17:06:24]  WARN powchain: Execution client is not syncing
[2022-10-04 17:06:33]  INFO p2p: Peer summary activePeers=27 inbound=0 outbound=27
[2022-10-04 17:06:38]  WARN powchain: Execution client is not syncing
[2022-10-04 17:06:38]  INFO initial-sync: Processing block batch of size 3 starting from  0x16523a39... 4837629/4839931 - estimated time remaining 4h15m46s blocksPerSecond=0.1 peers=27
[2022-10-04 17:06:39]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xfb0ff901068f slot=4837629
[2022-10-04 17:06:39]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xc6e1797b6f62 slot=4837630
[2022-10-04 17:06:39]  INFO blockchain: Called new payload with optimistic block payloadBlockHash=0xf092ecb44a39 slot=4837631
[2022-10-04 17:06:39]  INFO blockchain: Called fork choice updated with optimistic block finalizedPayloadBlockHash=0xc5e8718cf486 headPayloadBlockHash=0xf092ecb44a39 headSlot=4837631
panic: page 1932712 already freed

goroutine 1799 [running]:
go.etcd.io/bbolt.(*freelist).free(0xc0003de800, 0x19f6a, 0x7f58cbda8000)
        external/io_etcd_go_bbolt/freelist.go:175 +0x2c8
go.etcd.io/bbolt.(*node).spill(0xc031a86cb0)
        external/io_etcd_go_bbolt/node.go:359 +0x213
go.etcd.io/bbolt.(*node).spill(0xc031a86c40)
        external/io_etcd_go_bbolt/node.go:346 +0xaa
go.etcd.io/bbolt.(*node).spill(0xc031a86a10)
        external/io_etcd_go_bbolt/node.go:346 +0xaa
go.etcd.io/bbolt.(*Bucket).spill(0xc0143b9e80)
        external/io_etcd_go_bbolt/bucket.go:570 +0x33f
go.etcd.io/bbolt.(*Bucket).spill(0xc01fa70c58)
        external/io_etcd_go_bbolt/bucket.go:537 +0x107
go.etcd.io/bbolt.(*Tx).Commit(0xc01fa70c40)
        external/io_etcd_go_bbolt/tx.go:160 +0xe7
go.etcd.io/bbolt.(*DB).Update(0xbb98d0?, 0xc052e59040)
        external/io_etcd_go_bbolt/db.go:701 +0xe5
github.com/prysmaticlabs/prysm/v3/beacon-chain/db/kv.(*Store).SaveBlocks(0xc0025b2140, {0xbb98d0?, 0xc05dd310e0?}, {0xc013e89180?, 0x1c, 0x1c})
        beacon-chain/db/kv/blocks.go:299 +0x265
github.com/prysmaticlabs/prysm/v3/beacon-chain/blockchain.(*Service).ReceiveBlockBatch(0xc013b5e000, {0xbb9828?, 0xc0630eee40?}, {0xc013cd0fc0, 0x3, 0x4}, {0xc025625500, 0x3, 0x3})
        beacon-chain/blockchain/receive_block.go:120 +0x24d
github.com/prysmaticlabs/prysm/v3/beacon-chain/sync/initial-sync.(*Service).processBatchedBlocks(0xc007792280, {0xbb9828, 0xc0630eee40}, {0x186bda5?, 0x60?, 0x30d2800?}, {0xc013cd0c00, 0x3f, 0x40}, 0xc08e0ff630)
        beacon-chain/sync/initial-sync/round_robin.go:291 +0x8fd
github.com/prysmaticlabs/prysm/v3/beacon-chain/sync/initial-sync.(*Service).processFetchedData(0xc0634a04d0?, {0xbb9828?, 0xc0630eee40?}, {0xc021e55680?, 0x0?, 0x30d2800?}, 0xc063496e58?, 0x0?)
        beacon-chain/sync/initial-sync/round_robin.go:133 +0x11e
github.com/prysmaticlabs/prysm/v3/beacon-chain/sync/initial-sync.(*Service).syncToFinalizedEpoch(0xc007792280, {0xbb9828, 0xc0630eee40}, {0x337e60?, 0x2ebde88?, 0x30d2800?})
        beacon-chain/sync/initial-sync/round_robin.go:86 +0x285
github.com/prysmaticlabs/prysm/v3/beacon-chain/sync/initial-sync.(*Service).roundRobinSync(0xc007792280, {0xe00000004?, 0xc006cb0ce0?, 0x30d2800?})
        beacon-chain/sync/initial-sync/round_robin.go:49 +0x187
github.com/prysmaticlabs/prysm/v3/beacon-chain/sync/initial-sync.(*Service).Start(0xc007792280)
        beacon-chain/sync/initial-sync/service.go:105 +0x597
created by github.com/prysmaticlabs/prysm/v3/runtime.(*ServiceRegistry).StartAll
        runtime/service_registry.go:46 +0x210
```

**Comment by wmitsuda** [comment]
Found some strange evidence, I started prysm standalone (without EL), it was able to start and do some progress.

After giving it a lot of time, I started erigon, and then as soon as I started it, prysm crashed with the same `panic: page 1932712 already freed` error.

The same combo with the same versions used to work perfectly fine until yesterday.

**Comment by wmitsuda** [comment]
hi, I didn’t try them again with recent versions because I’ve been busy trying other CL combos, so can’t say if it’s still happening
