### ISSUE TITLE
could not process block in batch: timeout from http.Client: received an undefined ee error

### ISSUE THREAD

**Issue by DoubleDi** [prysmaticlabs/prysm#11880]
# 🐞 Bug Report

### Description

I am currently running a besu execution client and prysm beacon client. After successfully syncing from the checkpoint and backward resync up to block 16407452, there was a restart of the server, and now there are multiple errors, and the blocks on the server our moving by about 50 per day. The issue looks similar to #11707 as the error is completely the same. 

## 🔬 Minimal Reproduction

used your instructions to setup besu + prysm

<pre><code>
nohup /var/ethereum/execution/besu-22.10.3/bin/besu --rpc-http-enabled --engine-jwt-enabled=true --engine-jwt-secret=/var/ethereum/consensus/prysm/jwt.hex --engine-host-allowlist="*" --data-storage-format=BONSAI --data-path=/var/ethereum --rpc-ws-enabled --rpc-http-host="0.0.0.0" --host-allowlist="*"  > /var/ethereum/ethereum.log

nohup /var/ethereum/consensus/prysm/prysm.sh beacon-chain --execution-endpoint=http://localhost:8551 --jwt-secret=/var/ethereum/consensus/prysm/jwt.hex --checkpoint-sync-url=https://mainnet.checkpoint.sigp.io --genesis-beacon-api-url=https://mainnet.checkpoint.sigp.io --datadir /var/ethererum/consensus/prysm  > /var/ethereum/prysm.log &
</code></pre>

## 🔥 Error

prysm 

<pre><code>
time="2023-01-17 01:21:36" level=info msg="Processing block batch of size 64 starting from  0x128dca8e... 5575358/5590306 - estimated time remaining 26m13s" blocksPerSecond=9.5 peers=47 prefix=initial-sync
time="2023-01-17 01:21:52" level=info msg="Peer summary" activePeers=44 inbound=0 outbound=44 prefix=p2p
time="2023-01-17 01:22:10" level=warning msg="Skip processing batched blocks" error="could not process block in batch: timeout from http.Client: received an undefined ee error" prefix=initial-sync
time="2023-01-17 01:22:10" level=info msg="Processing block batch of size 64 starting from  0x8e98ed90... 5575550/5590308 - estimated time remaining 1h16m51s" blocksPerSecond=3.2 peers=45 prefix=initial-sync
time="2023-01-17 01:22:10" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0xa7f6581fd5109a38d9391c134792ce1e5e5aef968169ae0fbcec9b049d437ea0 (in processBatchedBlocks, slot=5575550)" prefix=initial-sync
time="2023-01-17 01:22:10" level=info msg="Processing block batch of size 64 starting from  0x074a2eba... 5575614/5590308 - estimated time remaining 38m15s" blocksPerSecond=6.4 peers=45 prefix=initial-sync
time="2023-01-17 01:22:10" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0xd3b119576de56f7a0ee8e7e77538dbea6a53b1bc7eaa334e46b490a5c2115714 (in processBatchedBlocks, slot=5575614)" prefix=initial-sync
time="2023-01-17 01:22:10" level=info msg="Processing block batch of size 64 starting from  0xdf7f8678... 5575678/5590308 - estimated time remaining 25m23s" blocksPerSecond=9.6 peers=45 prefix=initial-sync
time="2023-01-17 01:22:10" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0xa42a2cf62987df2125a7411150478eb87aa0ebb383f7f158141100924315c2f3 (in processBatchedBlocks, slot=5575678)" prefix=initial-sync
time="2023-01-17 01:22:10" level=info msg="Processing block batch of size 63 starting from  0x8115fbc3... 5575742/5590308 - estimated time remaining 19m2s" blocksPerSecond=12.8 peers=45 prefix=initial-sync
time="2023-01-17 01:22:10" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0x70ec122be8245ac679237b45b754b955cd535bd30f1172f60abea3d26bcfbb55 (in processBatchedBlocks, slot=5575742)" prefix=initial-sync
time="2023-01-17 01:22:11" level=info msg="Processing block batch of size 62 starting from  0x071d46d0... 5575422/5590309 - estimated time remaining 15m39s" blocksPerSecond=15.8 peers=45 prefix=initial-sync
time="2023-01-17 01:22:11" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0xa03f272e3791f8927965a66e052593004c1ff7b55bc2223e72fb8a4e9b789b26 (in processBatchedBlocks, slot=5575422)" prefix=initial-sync
time="2023-01-17 01:22:13" level=info msg="Processing block batch of size 64 starting from  0x72e509cd... 5575486/5590309 - estimated time remaining 12m58s" blocksPerSecond=19.1 peers=45 prefix=initial-sync
time="2023-01-17 01:22:13" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0x1c2da119f2b7c56cead5022a53713ef295de52b35ff686420e5ad0767df762a1 (in processBatchedBlocks, slot=5575486)" prefix=initial-sync
time="2023-01-17 01:22:13" level=info msg="Processing block batch of size 63 starting from  0xdb6bad87... 5575806/5590309 - estimated time remaining 10m53s" blocksPerSecond=22.2 peers=45 prefix=initial-sync
time="2023-01-17 01:22:13" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0x4dee79666a9a1e3a76fc0b81d0ab63fad583f2828ae982adad8fb1a539355896 (in processBatchedBlocks, slot=5575806)" prefix=initial-sync
</code></pre>

besu 

<pre><code>
2023-01-17 01:23:07.131+03:00 | vertx-blocked-thread-checker | WARN  | BlockedThreadChecker | Thread Thread[#78,vert.x-worker-thread-0,5,main] has been blocked for 679364 ms, time limit is 60000 ms
io.vertx.core.VertxException: Thread blocked
	at org.rocksdb.Transaction.disposeInternal(Native Method)
	at org.rocksdb.RocksObject.disposeInternal(RocksObject.java:37)
	at org.rocksdb.AbstractImmutableNativeReference.close(AbstractImmutableNativeReference.java:55)
	at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBSnapshotTransaction.close(RocksDBSnapshotTransaction.java:163)
	at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueSnapshot.close(RocksDBColumnarKeyValueSnapshot.java:107)
	at org.hyperledger.besu.ethereum.bonsai.BonsaiSnapshotWorldStateKeyValueStorage.tryClose(BonsaiSnapshotWorldStateKeyValueStorage.java:112)
	at org.hyperledger.besu.ethereum.bonsai.BonsaiSnapshotWorldStateKeyValueStorage.close(BonsaiSnapshotWorldStateKeyValueStorage.java:104)
	at org.hyperledger.besu.ethereum.bonsai.BonsaiInMemoryWorldState.close(BonsaiInMemoryWorldState.java:158)
	at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:170)
	at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.validateBlock(MergeCoordinator.java:440)
	at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.rememberBlock(MergeCoordinator.java:454)
	at org.hyperledger.besu.consensus.merge.blockcreation.TransitionCoordinator.rememberBlock(TransitionCoordinator.java:141)
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.engine.EngineNewPayload.syncResponse(EngineNewPayload.java:217)
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.ExecutionEngineJsonRpcMethod.lambda$response$0(ExecutionEngineJsonRpcMethod.java:73)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1589)
2023-01-17 01:23:07.214+03:00 | vert.x-worker-thread-0 | INFO  | EngineNewPayload | Imported #16,407,465 / 117 tx / base fee 16.28 gwei / 11,340,811 (37.8%) gas / (0x1ded2e01b5f9ec40e3896cb8e754b5863893d9652edd80e290fe8e1e0e9dc022) in 679.416s. Peers: 25
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Virtualization: kvm
Operating System: Debian GNU/Linux 11 (bullseye)
Kernel: Linux 5.10.0-19-amd64
Architecture: x86-64
Prysm v3.2.0
Besu 22.10.3
  </code>
</pre>

**Comment by james-prysm** [comment]
apologies for the late response, an ee error means there's something wrong with besu, you'll find more support with their team. early guess is perhaps there was an unsafe shutdown, I'm not sure what would cause io.vertx.core.VertxException: Thread blocked

**Comment by DoubleDi** [comment]
Hi @james-prysm ! Thanks a lot. What about the "beacon node doesn't have a parent in db with root"?  Prysm does not move forward and get insync.

**Comment by james-prysm** [comment]
This could be the same on the prysm side , I'd try to get the execution client working first and not throwing an error before addressing this. worse case you may need to resync prysm as well, however if you are ok with added security assumptions then checkpointsync would be able to get you synced in a few min. https://docs.prylabs.network/docs/prysm-usage/checkpoint-sync

**Comment by nisdas** [comment]
This is an issue with besu not processing payloads in time. When this happens, prysm gets stuck and can't do anything. Closing this issue as its something that can't be resolved on our end.
