### ISSUE TITLE
"Panic occurred" error="reflect: call of reflect.Value.Int on struct Value"

### ISSUE THREAD

**Issue by cppfuns** [prysmaticlabs/prysm#12422]
The problem occurred on the test chain built locally. It was running and synchronous before. I am not sure whether it has something to do with my attempt to add --block-batch-limit. I removed the added --block-batch-limit, but Error persists. Even cleared the chain data and re-synced, the problem still exists

Branch: v4.0.3
os: ubuntu 20.04
```
time="2023-05-18 12:35:00" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=1 suitable=0
time="2023-05-18 12:35:01" level=error msg="Panic occurred" error="reflect: call of reflect.Value.Int on struct Value" prefix=sync topic="/eth2/beacon_chain/req/goodbye/1/ssz_snappy"
time="2023-05-18 12:35:01" level=error msg="goroutine 1751 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/prysmaticlabs/prysm/v4/beacon-chain/sync.(*Service).registerRPC.func1.1()
	/mnt/md0/jenkins/workspace/testnet/prysm/Branch_v4.0.3/beacon-chain/sync/rpc.go:116 +0x13f
panic({0x1c8a280, 0xc00388bb78})
	/usr/local/go/src/runtime/panic.go:890 +0x263
reflect.Value.Int(...)
	/usr/local/go/src/reflect/value.go:1461
github.com/trailofbits/go-mutexasserts.RWMutexRLocked(0x43c3fd?)
	/home/ps/go/pkg/mod/github.com/trailofbits/go-mutexasserts@v0.0.0-20200708152505-19999e7d3cef/mutex.go:22 +0x13d
github.com/prysmaticlabs/prysm/v4/beacon-chain/sync.(*limiter).retrieveCollector(0xc005c866c0, {0x207520a, 0x11})
	/mnt/md0/jenkins/workspace/testnet/prysm/Branch_v4.0.3/beacon-chain/sync/rate_limiter.go:190 +0x48
github.com/prysmaticlabs/prysm/v4/beacon-chain/sync.(*limiter).validateRawRpcRequest(0xc005c866c0, {0x253f080, 0xc003ba7480})
	/mnt/md0/jenkins/workspace/testnet/prysm/Branch_v4.0.3/beacon-chain/sync/rate_limiter.go:115 +0xcd
github.com/prysmaticlabs/prysm/v4/beacon-chain/sync.(*Service).registerRPC.func1({0x253f080?, 0xc003ba7480})
	/mnt/md0/jenkins/workspace/testnet/prysm/Branch_v4.0.3/beacon-chain/sync/rpc.go:146 +0x799
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1({0xc00470c0c0, 0x2b}, {0x7f74d8244008?, 0xc003ba7480})
	/home/ps/go/pkg/mod/github.com/libp2p/go-libp2p@v0.26.2/p2p/host/basic/basic_host.go:593 +0x76
created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
	/home/ps/go/pkg/mod/github.com/libp2p/go-libp2p@v0.26.2/p2p/host/basic/basic_host.go:434 +0x74f
" prefix=sync topic="/eth2/beacon_chain/req/goodbye/1/ssz_snappy"
```

**Comment by prestonvanloon** [comment]
Prysm v4.0.3 is not compatible with go1.20. Please downgrade to go1.19 or use bazel to build locally to ensure you have the correct version of go. See https://github.com/trailofbits/go-mutexasserts/issues/1
