### ISSUE TITLE
Cannot build docker container for "create-beacon-chain-genesis"

### ISSUE THREAD

**Issue by dewindtk** [prysmaticlabs/prysm#12885]
Hi. I am following the steps in https://docs.prylabs.network/docs/advanced/proof-of-stake-devnet
And am running into an issue right off the bat trying to up the docker containers. I get:

service "create-beacon-chain-genesis" didn't complete successfully: exit 2

And looking at the logs, here is what I see. What might have caused the issue? Thanks in advance.

```2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  | time="2023-09-11T14:42:05Z" level=info msg="Specified a chain config file: /consensus/config.yml" prefix=genesis
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  | time="2023-09-11T14:42:05Z" level=error msg="Failed to decode hex string." error="encoding/hex: invalid byte: U+000D"
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  | time="2023-09-11T14:42:05Z" level=error msg="Failed to decode hex string." error="encoding/hex: invalid byte: U+000D"
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  | time="2023-09-11T14:42:05Z" level=error msg="Failed to decode hex string." error="encoding/hex: invalid byte: U+000D"
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  | time="2023-09-11T14:42:05Z" level=error msg="Failed to decode hex string." error="encoding/hex: invalid byte: U+000D"
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  | time="2023-09-11T14:42:05Z" level=error msg="Failed to decode hex string." error="encoding/hex: invalid byte: U+000D"
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  | time="2023-09-11T14:42:05Z" level=info msg="No genesis time specified, defaulting to now()" prefix=genesis
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  | time="2023-09-11T14:42:05Z" level=info msg="Delaying genesis 1694443325 by 15 seconds" prefix=genesis
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  | time="2023-09-11T14:42:05Z" level=info msg="Genesis is now 1694443340" prefix=genesis
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  | panic: runtime error: invalid memory address or nil pointer dereference
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2d0503f]
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  | 
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  | goroutine 1 [running]:
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  | github.com/prysmaticlabs/prysm/v4/cmd/prysmctl/testnet.generateGenesis({0xcfacd0, 0xc000126000})
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  |     cmd/prysmctl/testnet/generate_genesis.go:279 +0x6ff
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  | github.com/prysmaticlabs/prysm/v4/cmd/prysmctl/testnet.cliActionGenerateGenesisState(0xc00072a340)
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  |     cmd/prysmctl/testnet/generate_genesis.go:179 +0x1c9
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  | github.com/prysmaticlabs/prysm/v4/cmd/prysmctl/testnet.glob..func1(0x2fad200?)
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  |     cmd/prysmctl/testnet/generate_genesis.go:70 +0x2e
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  | github.com/urfave/cli/v2.(*Command).Run(0x2fad200, 0xc00072a340, {0xc000730100, 0x8, 0x8})
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  |     external/com_github_urfave_cli_v2/command.go:274 +0x9eb
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  | github.com/urfave/cli/v2.(*Command).Run(0x2fad0a0, 0xc00072a280, {0xc0002325a0, 0x9, 0x9})
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  |     external/com_github_urfave_cli_v2/command.go:267 +0xc4d
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  | github.com/urfave/cli/v2.(*Command).Run(0xc00072e580, 0xc00072a1c0, {0xc000124000, 0xa, 0xa})
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  |     external/com_github_urfave_cli_v2/command.go:267 +0xc4d
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  | github.com/urfave/cli/v2.(*App).RunContext(0xc000736000, {0xcfacd0?, 0xc000126000}, {0xc000124000, 0xa, 0xa})
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  |     external/com_github_urfave_cli_v2/app.go:332 +0x616
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  | github.com/urfave/cli/v2.(*App).Run(...)
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  |     external/com_github_urfave_cli_v2/app.go:309
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  | main.main()
2023-09-11 16:42:05 eth-pos-devnet-create-beacon-chain-genesis-1  |     cmd/prysmctl/main.go:23 +0x8e```

**Comment by farhana-k** [comment]
hi,
this error happened since the lastcommit (sept 8).... try using image: gcr.io/prysmaticlabs/prysm/cmd/prysmctl:latest instead of gcr.io/prysmaticlabs/prysm/cmd/prysmctl:local-devnet in docker-compose.yml

**Comment by dewindtk** [comment]
Hi! Thanks for the tip. I have found an alternative in https://github.com/OffchainLabs/eth-pos-devnet/issues/36
