### ISSUE TITLE
NewSlotTickerWithIntervals Panics if a One Second Slot is Used

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#13280]
### Discussed in https://github.com/prysmaticlabs/prysm/discussions/13267

<div type='discussions-op-text'>

<sup>Originally posted by **montekki** December  6, 2023</sup>
Hi all, is it possible to run a local devnet with `SECONDS_PER_SLOT: 1` ? Beacon client is panicking with it with:

```
2023-12-05 17:19:30 time="2023-12-05 16:19:30" level=info msg="Due to number of peers required for sync being set at 0, entering regular sync immediately." genesisTime=2023-12-05 16:19:44 +0000 UTC prefix=initial-sync
2023-12-05 17:19:30 panic: invalid decreasing offsets
2023-12-05 17:19:30 
2023-12-05 17:19:30 goroutine 4810 [running]:
2023-12-05 17:19:30 github.com/prysmaticlabs/prysm/v4/time/slots.NewSlotTickerWithIntervals({0x40009fcf20?, 0xdd1ce0?, 0x3942ca0?}, {0x400072c610?, 0x0?, 0x0?})
2023-12-05 17:19:30     time/slots/slotticker.go:190 +0x1b4
2023-12-05 17:19:30 github.com/prysmaticlabs/prysm/v4/beacon-chain/blockchain.(*Service).spawnProcessAttestationsRoutine.func1()
2023-12-05 17:19:30     beacon-chain/blockchain/receive_attestation.go:96 +0x224
2023-12-05 17:19:30 created by github.com/prysmaticlabs/prysm/v4/beacon-chain/blockchain.(*Service).spawnProcessAttestationsRoutine
2023-12-05 17:19:30     beacon-chain/blockchain/receive_attestation.go:72 +0x5c
```</div>

**Comment by v4lproik** [comment]
Hey! I would love to take this up :)

**Comment by nisdas** [comment]
Perfect, assigned to you !
