### ISSUE TITLE
runtime error: integer divide by zero

### ISSUE THREAD

**Issue by ligi** [prysmaticlabs/prysm#2649]
```
[2019-05-19 13:30:07] ERROR message-handler: Panicked when handling p2p message! Recovering... msg=data: <
  slot: 9223372036854798548
  beacon_block_root_hash32: "E6\037M-[w\331><\246?\322\2511\325\352\3716\323%\224\026\306\210K?\256\212p\013\351"
  epoch_boundary_root_hash32: "7c\223jI\\\262\276\204\255\363G*)\325y\245\014\325\207=\326\263#\313\006\013\337\237\327Q<"
  crosslink_data_root_hash32: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
  latest_crosslink: <
    epoch: 1152921504606846976
    crosslink_data_root_hash32: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
  >
  justified_epoch: 1152921504606849817
  justified_block_root_hash32: "|\331\241'\240\033\210\306\353z\367\367\275\023\007\000\353;^-s\275z\200*\310&\352\357\227O\346"
>
aggregation_bitfield: "\000\000\000\000\000\000\001\000\000\000"
custody_bitfield: "\000\000\000\000\000\000\000\000\000\000"
aggregate_signature: "signed"
 r=runtime error: integer divide by zero
goroutine 272 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        GOROOT/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
        GOROOT/src/runtime/debug/stack.go:16 +0x22
github.com/prysmaticlabs/prysm/shared/messagehandler.SafelyHandleMessage.func1(0x1610a60, 0xc0407625b0, 0x16186e0, 0xc0003fbc40)
        shared/messagehandler/messagehandler.go:31 +0x223
panic(0x11738c0, 0x1ff6940)
        GOROOT/src/runtime/panic.go:522 +0x1b5
github.com/prysmaticlabs/prysm/beacon-chain/core/state.ProcessEpoch(0x16187a0, 0xc034e47680, 0xc022c89000, 0x0, 0xc01104b946, 0x0, 0x0, 0x0)
        beacon-chain/core/state/transition.go:510 +0x475c
github.com/prysmaticlabs/prysm/beacon-chain/core/state.ExecuteStateTransition(0x16187a0, 0xc034e47680, 0xc022c89000, 0x0, 0x28bcc33c32843df1, 0x531f37961da89aed, 0xc0a0e368ab47940c, 0xafe809c05ceac634, 0xc01104b946, 0x0, ...)
        beacon-chain/core/state/transition.go:94 +0x2d7
github.com/prysmaticlabs/prysm/beacon-chain/attestation.(*Service).updateAttestation(0xc0005136d0, 0x16186e0, 0xc0003fbc40, 0x28bcc33c32843df1, 0x531f37961da89aed, 0xc0a0e368ab47940c, 0xafe809c05ceac634, 0xc022c89000, 0xc0407625b0, 0x0, ...)
        beacon-chain/attestation/service.go:229 +0xee
github.com/prysmaticlabs/prysm/beacon-chain/attestation.(*Service).UpdateLatestAttestation(0xc0005136d0, 0x16186e0, 0xc0003fbc40, 0xc0407625b0, 0xc000370f00, 0xc02b1394f0)
        beacon-chain/attestation/service.go:175 +0x162
github.com/prysmaticlabs/prysm/beacon-chain/attestation.(*Service).handleAttestation(0xc0005136d0, 0x16186e0, 0xc0003fbc40, 0x1610a60, 0xc0407625b0, 0x20, 0xc01104bed0)
        beacon-chain/attestation/service.go:148 +0x68
github.com/prysmaticlabs/prysm/shared/messagehandler.SafelyHandleMessage(0x16186e0, 0xc0003fbc40, 0xc01104bf58, 0x1610a60, 0xc0407625b0)
        shared/messagehandler/messagehandler.go:46 +0x9a
github.com/prysmaticlabs/prysm/beacon-chain/attestation.(*Service).attestationPool(0xc0005136d0)
        beacon-chain/attestation/service.go:141 +0xdf
created by github.com/prysmaticlabs/prysm/beacon-chain/attestation.(*Service).Start
        beacon-chain/attestation/service.go:75 +0x98


```

**Comment by prestonvanloon** [comment]
I think this has been resolved. I'm not sure how to replicate it at the moment. 

I'll close for now, but if you see it again please reopen. Thanks!
