### ISSUE TITLE
bls error panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by i6du** [prysmaticlabs/prysm#2859]
go version go1.12.6 darwin/amd64

code

```

package main

import (
	"encoding/base64"

	"github.com/prysmaticlabs/prysm/shared/bls"
)

func main() {

	token, err := base64.RawURLEncoding.DecodeString("7JylYw6E0deEDZKLXCjXVSCToi5_9ZfzYFeXm3Pp7wA")
	if err != nil {
		panic(err)
	}

	b64token := base64.RawURLEncoding.EncodeToString(token)
	println("secret", b64token)

	secret, err := bls.SecretKeyFromBytes(token)
	if err != nil {
		panic(err)
	}

	sign := secret.Sign([]byte("123"), 1)

	println("sign.Marshal len", len(sign.Marshal()))

}

```

error

```

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10b776a]

goroutine 1 [running]:
github.com/phoreproject/bls.(*FR).Copy(...)
	/Users/z/go/pkg/mod/github.com/phoreproject/bls@v0.0.0-20190621015719-e008a268030e/fr.go:31
github.com/phoreproject/bls.(*FR).ToRepr(0x0, 0x0)
	/Users/z/go/pkg/mod/github.com/phoreproject/bls@v0.0.0-20190621015719-e008a268030e/fr.go:317 +0x2a
github.com/phoreproject/bls/g1pubs.SignWithDomain(0x333231, 0x0, 0x0, 0x0, 0xc00000e030, 0x1, 0xf397f57f2ea29320)
	/Users/z/go/pkg/mod/github.com/phoreproject/bls@v0.0.0-20190621015719-e008a268030e/g1pubs/bls.go:129 +0x7e
github.com/prysmaticlabs/prysm/shared/bls.(*SecretKey).Sign(0xc00000e038, 0xc000080f5d, 0x3, 0x3, 0x1, 0x0)
	/Users/z/go/pkg/mod/github.com/prysmaticlabs/prysm@v0.0.0-20190625165747-9bd614702745/shared/bls/bls.go:74 +0x89
main.main()
	/Users/z/git/6du/u6du/tmp.go:24 +0x18c

Process finished with exit code 2

```

**Comment by nisdas** [comment]
Hey we use the [phore](https://github.com/phoreproject/bls) library as our underlying BLS library. This issue would be better raised there but as far as I understand from the library, the given token maps to an invalid FR point leading to the bytes being marshalled to an invalid secret key. This leads to the panic when trying to sign a message.  @meyer9 would be able to dig into this issue better

**Comment by meyer9** [comment]
I'll look into it tonight. I think this might happen when the private key is too big.

**Comment by meyer9** [comment]
Ah, you're using `DeserializeSecretKey` which should use the output from `SerializeSecretKey`.

You should use `DeriveSecretKey` which can take arbitrary bytes.
