### ISSUE TITLE
Initial sync panics 

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#3409]
Saw the following panic during initial sync for a syncing node launches the first time and trying to catch up 

```
[2019-09-05 08:27:20]  INFO p2p: New peer connected. peer=16Uiu2HAkv3DMENZGJZSuzdNMsy35fR6wtf82nzbxFqThy1yuBMCH
[2019-09-05 08:27:21] ERROR sync: Panic occurred error=runtime error: invalid memory address or nil pointer dereference topic=/eth2/beacon_block/ssz
goroutine 307 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	GOROOT/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	GOROOT/src/runtime/debug/stack.go:16 +0x22
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1.1(0xc000185420)
	beacon-chain/sync/subscriber.go:94 +0x176
panic(0x4e7e6e0, 0x5f0b7c0)
	GOROOT/src/runtime/panic.go:522 +0x1b5
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).beaconBlockSubscriber(0xc000185180, 0x538b7c0, 0xc000694210, 0x5382100, 0xc0006fa180, 0x0, 0x637ee01)
	beacon-chain/sync/subscriber_beacon_blocks.go:27 +0x66
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1(0xc000020300, 0x2c5, 0x300, 0xc00067a300)
	beacon-chain/sync/subscriber.go:120 +0x553
created by github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func2
	beacon-chain/sync/subscriber.go:142 +0xff
[2019-09-05 08:27:22]  INFO powchain: Minimum number of validators reached for beacon-chain to start ChainStartTime=2019-09-05 08:26:21 -0700 PDT
[2019-09-05 08:27:22]  INFO blockchain: ChainStart time reached, starting the beacon chain!
[2019-09-05 08:27:24]  WARN sync: Ignored incoming attestation that points to a block that isn't in the database.
```

**Comment by nisdas** [comment]
two reasons either `block` was nil or `headState.FinalizedCheckpoint.Epoch` the FinalizedEpoch did not exist. Since this is before the genesis state is created, I am guessing finalized checkpoint is the source of the panic. We shouldn't be listening to gossiped blocks or attestations before we have processed all our deposit logs, which is what seems like happened over here

**Comment by rauljordan** [comment]
No longer relevant
