### ISSUE TITLE
Safe discv5

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#3509]
The upstream p2p discv5 package has several panics and unsafe slice access.

We should fork the code changes or write a new discv5 to change the API to be safer at runtime. 

https://github.com/fjl/go-ethereum/tree/discover-v5-rebase/p2p

Example panic that killed the testnet:
```
panic: runtime error: slice bounds out of range

goroutine 12088 [running]:
github.com/ethereum/go-ethereum/p2p/enode.splitNodeItemKey(0xc001fe2986, 0x7, 0x3d, 0xaeeeac7c345cdb61, 0x1c12ec867effb1db, 0x3bddc7511ad2647e, 0xd1f5326af3a951c1, 0xc001fe2983, 0x7, 0x3d, ...)
        external/com_github_ethereum_go_ethereum/p2p/enode/nodedb.go:175 +0x1fb
github.com/ethereum/go-ethereum/p2p/enode.(*DB).expireNodes(0xc000803a00)
        external/com_github_ethereum_go_ethereum/p2p/enode/nodedb.go:339 +0x1a0
github.com/ethereum/go-ethereum/p2p/enode.(*DB).expirer(0xc000803a00)
        external/com_github_ethereum_go_ethereum/p2p/enode/nodedb.go:317 +0x84
created by github.com/ethereum/go-ethereum/p2p/enode.(*DB).ensureExpirer.func1
        external/com_github_ethereum_go_ethereum/p2p/enode/nodedb.go:306 +0x3e
```

**Comment by rauljordan** [comment]
Can we close @nisdas ?
