### ISSUE TITLE
Latest docker beacon-chain image panic on initial syncing

### ISSUE THREAD

**Issue by Magicking** [prysmaticlabs/prysm#3756]
```
%> docker run -v /home/magicking/tmp/prysm-data:/root/.eth2 -p 4000:4000 gcr.io/prysmaticlabs/prysm/beacon-chain:latest --verbosity debug
2019/10/12 04:35:58 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
time="2019-10-12 04:35:58" level=info msg="Using custom chain parameters" config=demo prefix=node
time="2019-10-12 04:35:59" level=info msg="Checking DB" database-path="/root/.eth2/beaconchaindata" prefix=node
time="2019-10-12 04:35:59" level=debug msg="ECDSA private key generated" prefix=p2p
time="2019-10-12 04:35:59" level=info msg="Fetching testnet cluster address" endpoint="https://prylabs.net/contract" prefix=node
time="2019-10-12 04:35:59" level=info msg="Starting beacon node" prefix=node version="Git commit: 1dbb67af810c20b8ea5887da9f89e37af6a1da65. Built at: 2019-10
-12 03:34:27+00:00"
[...]
time="2019-10-12 04:36:05" level=debug msg="Deposit registered from deposit contract" merkleTreeIndex=39 prefix=powchain publicKey=0xb87eb1ff710c9ebbf4a7052b
33781cfe66f9a31e9ea265ba890c5fe462cc549dcada1af337064ffd695419819fd6cbd5
time="2019-10-12 04:36:05" level=debug msg="Deposit registered from deposit contract" merkleTreeIndex=40 prefix=powchain publicKey=0x99394633075f47eccd12d51d
ac71fe7eb8c6b4ce15b290cdb184062045597b4512718e2d3b5c1e6583693ebe29d254ae
time="2019-10-12 04:36:05" level=debug msg="Received 58 blocks" peer=16Uiu2HAm8sWmFqhyZ1EAhJpyXRbcT31wVETGEEKQsghRzHxFuYY5 prefix=initial-sync
time="2019-10-12 04:36:05" level=debug msg="Deposit registered from deposit contract" merkleTreeIndex=41 prefix=powchain publicKey=0xb99144a7d5624f9874a4c0b9
57b9f39ab2abc91a7aa5c9e219b34184503798c8a588b903f291771bf95116da634d6dfd
time="2019-10-12 04:36:05" level=debug msg="Received 60 blocks" peer=16Uiu2HAm2ex6j3tYRhUwiNdRkgW3s52hw3DCfSCy7GPYYQm29Gtf prefix=initial-sync
time="2019-10-12 04:36:05" level=info msg="Processing block 1/31560 - estimated time remaining 175h19m40s" blocksPerSecond=0.1 peers="2/5" prefix=initial-syn
c
panic: could not process block from fork choice service: pre state of slot 1 does not exist

goroutine 255 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).Start(0xc000942660)
        beacon-chain/sync/initial-sync/service.go:107 +0x98d
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
        shared/service_registry.go:44 +0x23e
```

`--clear-db` is not present but database was wiped clean by hand before.

**Comment by Magicking** [comment]
Seems to be related to #3665

**Comment by ethgasstation** [comment]
I am having this same issue on initial sync

**Comment by soc1c** [comment]
Having the same issue. Any workarounds?

**Comment by prestonvanloon** [comment]
This is due to not having the correct genesis time. Please use `--no-genesis-delay` flag for testnet access.

**Comment by soc1c** [comment]
That worked @prestonvanloon

**Comment by Magicking** [comment]
Tested today using guide from https://prylabs.net/participate (e.g: `--no-genesis-delay`) worked like a charm!
