### ISSUE TITLE
Initial sync stuck at slot 101323. Peers serving non-canonical block

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#3858]
In the current running testnet, block at slot 101323 has a parent that is older than a finalized epoch.

101285 is the parent of block at slot 101323
101288 is finalized
syncing continues until 101323 then we see the following error
```
[2019-10-26 14:07:23]  INFO initial-sync: Processing block 101323/132617 - estimated time remaining 5h25m58s blocksPerSecond=1.6 peers=1/8
panic: could not process block from fork choice service: block from slot 101323 is not a descendent of the current finalized block

goroutine 260 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).Start(0xc0007abe90)
        beacon-chain/sync/initial-sync/service.go:106 +0x97d
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
        shared/service_registry.go:44 +0x23e
```

**Comment by prestonvanloon** [comment]
Related: https://github.com/prysmaticlabs/prysm/issues/3848
