### ISSUE TITLE
Ethereum API: Index out of range error when querying validator balances by epoch

### ISSUE THREAD

**Issue by ppratscher** [prysmaticlabs/prysm#4020]
```
client.ListValidatorBalances(context.Background(), &ethpb.GetValidatorBalancesRequest{QueryFilter: &ethpb.GetValidatorBalancesRequest_Epoch{Epoch: 4000}})
```
returns `rpc error: code = Unknown desc = runtime error: index out of range [345] with length 345`

Also please note the inconsistent naming, while the api call is called **List**ValidatorBalances the parameters are called **Get**ValidatorBalances

**Comment by rauljordan** [comment]
Great find, this is due to:

```go
if len(req.Indices) == 0 && len(req.PublicKeys) == 0 {
		// return everything.
		for i := 0; i < len(headState.Balances); i++ {
			res = append(res, &ethpb.ValidatorBalances_Balance{
				PublicKey: headState.Validators[i].PublicKey,
				Index:     uint64(i),
				Balance:   balances[i],
			})
		}
	}
```
in our ListValidatorBalances implementation. If the balances come from the archive, we shouldn't be appending to the `res` slice from `headState`, but rather from the archived balances. Will resolve this soon.

**Comment by rauljordan** [comment]
Full stack trace:

```
{"error":"runtime error: index out of range [256] with length 256","message":"gRPC panicked!","severity":"ERROR","stack":"goroutine 121244735 [running]:\nruntime/debug.Stack(0xc0000e8690, 0x14ffe08, 0x5)\n\tGOROOT/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/prysmaticlabs/prysm/shared/traceutil.RecoveryHandlerFunc(0x187e000, 0xc00f10b110, 0x1413fc0, 0xc009f63140, 0x41a55e, 0x7fdb56d8c228)\n\tshared/traceutil/recovery_interceptor_option.go:29 +0x155\ngithub.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom(0x187e000, 0xc00f10b110, 0x1413fc0, 0xc009f63140, 0x16be810, 0x40ef76, 0x203001)\n\texternal/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:52 +0x5a\ngithub.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1(0x187e000, 0xc00f10b110, 0xc0002bc140, 0xc00063b968)\n\texternal/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:26 +0x77\npanic(0x1413fc0, 0xc009f63140)\n\tGOROOT/src/runtime/panic.go:679 +0x1b2\ngithub.com/prysmaticlabs/prysm/beacon-chain/rpc/beacon.(*Server).ListValidatorBalances(0xc000416000, 0x187e000, 0xc0108922d0, 0xc009741180, 0xc000416000, 0x0, 0x0)\n\tbeacon-chain/rpc/beacon/validators.go:130
```
