### ISSUE TITLE
archival service panics

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#4036]
Reported by Peter from Bitfly. Beacon node crashed due to the following:
```
time="2019-11-18 17:37:05" level=info msg="Finished applying state transition" attestations=8 deposits=0 prefix=blockchain slot=50745
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1098b43]

goroutine 191 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/archiver.(*Service).run(0xc000c8b1d0, 0x1889b00, 0xc000c78a80)
        beacon-chain/archiver/service.go:142 +0x433
created by github.com/prysmaticlabs/prysm/beacon-chain/archiver.(*Service).Start
        beacon-chain/archiver/service.go:54 +0x50
```
He did mention after restart it seems to work again

**Comment by rauljordan** [comment]
Closed by #4042
