### ISSUE TITLE
Index out of range error while syncing

### ISSUE THREAD

**Issue by ppratscher** [prysmaticlabs/prysm#4116]
While syncing our node (latest master) crashed with the following error:
```
time="2019-11-26 13:15:29" level=info msg="Processing block 23541/107037 - estimated time remaining 45m2s" blocksPerSecond=30.9 peers="1/0" prefix=initial-sync
panic: runtime error: index out of range [-1]

goroutine 227 [running]:
github.com/libp2p/go-libp2p-peerstore/pstoremem.(*addrSegments).get(...)
	external/com_github_libp2p_go_libp2p_peerstore/pstoremem/addr_book.go:41
github.com/libp2p/go-libp2p-peerstore/pstoremem.(*memoryAddrBook).Addrs(0xc000317b00, 0x0, 0x0, 0x0, 0x0, 0x0)
	external/com_github_libp2p_go_libp2p_peerstore/pstoremem/addr_book.go:236 +0x41c
github.com/libp2p/go-libp2p/p2p/host/routed.(*RoutedHost).Connect(0xc000300ce0, 0x1898ea0, 0xc001538600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5038fb, 0x1898ee0)
	external/com_github_libp2p_go_libp2p/p2p/host/routed/routed.go:62 +0xd8
github.com/libp2p/go-libp2p/p2p/host/routed.(*RoutedHost).NewStream(0xc000300ce0, 0x1898ea0, 0xc001538600, 0x0, 0x0, 0xc00210c890, 0x1, 0x1, 0xc000fd7b00, 0xc004214680, ...)
	external/com_github_libp2p_go_libp2p/p2p/host/routed/routed.go:179 +0x1b0
github.com/prysmaticlabs/prysm/beacon-chain/p2p.(*Service).Send(0xc000298780, 0x1898ea0, 0xc001538600, 0x14a69e0, 0xc00501b900, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	beacon-chain/p2p/sender.go:28 +0x3fa
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).requestBlocks(0xc000091e00, 0x1898e20, 0xc001008600, 0xc00501b900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	beacon-chain/sync/initial-sync/round_robin.go:252 +0x351
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).roundRobinSync(0xc000091e00, 0x0, 0xed55b8312, 0x23f4f00, 0x0, 0x0)
	beacon-chain/sync/initial-sync/round_robin.go:230 +0x1061
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).Start(0xc000091e00)
	beacon-chain/sync/initial-sync/service.go:131 +0xb80
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
	shared/service_registry.go:44 +0x23e
```

After a restart the node continued to sync.

**Comment by terencechain** [comment]
The fix is happening in #4115
