### ISSUE TITLE
Beacon node panic: no peers left to request blocks

### ISSUE THREAD

**Issue by torfbolt** [prysmaticlabs/prysm#4212]
After update to the latest beacon-chain client I did a node restart. It waits for 3 connected peers and ~10s after the 3rd one is connected I got this panic:

```
[2019-12-06 20:50:53]  INFO initial-sync: Waiting for enough peer handshakes before syncing handshakes=2/3
[2019-12-06 20:50:57]  INFO p2p: New peer connected peer=16Uiu2HAm5bcvviYBZL4oVEUPfbW3XCdTBuJT51KCLuNZfgeLvvct
panic: no peers left to request blocks

goroutine 216 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).Start(0xc001548f00)
        beacon-chain/sync/initial-sync/service.go:132 +0xf1c
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
        shared/service_registry.go:44 +0x23e
```

The second time I tried restarting it worked, so the error is not 100% reproducible.

**Comment by calumtomeny** [comment]
I get the same error after a minute or two every time I try to sync:

[2019-12-07 22:14:26]  INFO initial-sync: Processing block 9032/188932 - estimated time remaining 6h19m32s blocksPerSecond=7.9 peers=1/3
[2019-12-07 22:14:26]  INFO initial-sync: Processing block 9033/188932 - estimated time remaining 6h17m8s blocksPerSecond=8.0 peers=1/3
[2019-12-07 22:14:26]  INFO initial-sync: Processing block 9034/188932 - estimated time remaining 6h14m47s blocksPerSecond=8.0 peers=1/3
[2019-12-07 22:14:26]  INFO initial-sync: Processing block 9035/188932 - estimated time remaining 6h12m27s blocksPerSecond=8.1 peers=1/3
[2019-12-07 22:14:26]  INFO initial-sync: Processing block 9037/188932 - estimated time remaining 6h10m9s blocksPerSecond=8.1 peers=1/3
[2019-12-07 22:14:26]  INFO initial-sync: Processing block 9038/188932 - estimated time remaining 6h7m52s blocksPerSecond=8.2 peers=1/3
[2019-12-07 22:14:26]  INFO initial-sync: Processing block 9039/188932 - estimated time remaining 6h5m38s blocksPerSecond=8.2 peers=1/3
[2019-12-07 22:14:26]  INFO initial-sync: Processing block 9041/188932 - estimated time remaining 6h3m24s blocksPerSecond=8.2 peers=1/3
[2019-12-07 22:14:26]  INFO initial-sync: Processing block 9042/188932 - estimated time remaining 6h1m13s blocksPerSecond=8.3 peers=1/3
[2019-12-07 22:14:26]  INFO initial-sync: Processing block 9045/188932 - estimated time remaining 5h59m3s blocksPerSecond=8.3 peers=1/3
[2019-12-07 22:14:26]  INFO initial-sync: Processing block 9046/188932 - estimated time remaining 5h56m55s blocksPerSecond=8.4 peers=1/3
[2019-12-07 22:14:26]  INFO initial-sync: Processing block 9047/188932 - estimated time remaining 5h54m48s blocksPerSecond=8.4 peers=1/3
panic: no peers left to request blocks

goroutine 127 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).Start(0xc001029c80)
	beacon-chain/sync/initial-sync/service.go:133 +0xf1c
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
	shared/service_registry.go:44 +0x23e

**Comment by Phistr90** [comment]
Same. Now when I retry I even cant get enough peers to start syncing.

**Comment by Phistr90** [comment]
Preston told me on Discord:

> If you know how to port forward 13000 to your computer from your router, you can add flag p2p-host-ip=$(curl -s ident.me) That will tell peers how to connect to you, you should get way more peers

That helped for me.

**Comment by mog3n** [comment]
> Preston told me on Discord:
> 
> > If you know how to port forward 13000 to your computer from your router, you can add flag p2p-host-ip=$(curl -s ident.me) That will tell peers how to connect to you, you should get way more peers
> 
> That helped for me.

So a simple port forward at 13000 UDP should fix the issue?

**Comment by prestonvanloon** [comment]
@mog3n it's TCP port 13000. The issue here is that you maybe struggling to find peers that accept inbound connections and when you do find those peers they may go away at any time. 

One potential solution is to change your set up so you can accept inbound connections. To do this, you can port forward TCP 13000 in your router to your local machine. Then you can add flag `--p2p-host-ip=$(curl -s ident.me)` which will advertise your public IP to peers.

**Comment by torfbolt** [comment]
Sure, without 13000 open it will be harder, but the client still shouldn't crash with a panic. Or is this really a p2p network state that is not recoverable?

**Comment by prestonvanloon** [comment]
I agree it shouldn't panic. The above suggestion is a workaround until we have a resilient solution.

**Comment by rauljordan** [comment]
Our beacon node in latest master is significantly more resilient to these types of issues. If you all are still seeing this with latest master please mention this and we'll reopen.
