### ISSUE TITLE
panic: could not process blockCopy from fork choice service: pre state of slot 217810 does not exist

### ISSUE THREAD

**Issue by ethers** [prysmaticlabs/prysm#4277]
I think a restart is just going to lead to the same error. How to recover?

[2019-12-13 07:49:11]  INFO initial-sync: Waiting for enough peer handshakes before syncing handshakes=2/3
[2019-12-13 07:49:11]  INFO p2p: Peer connected active=3 peer=16Uiu2HAmUYj89iS7jCXrnrGcrvdDgfBXB1H5zUis1GJXS7ovn467
[2019-12-13 07:49:16]  INFO initial-sync: Processing block 217810/227806 - estimated time remaining 55h32m0s blocksPerSecond=0.1 peers=3/3
panic: could not process blockCopy from fork choice service: pre state of slot 217810 does not exist

goroutine 205 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).Start(0xc0015aeba0)
	beacon-chain/sync/initial-sync/service.go:132 +0xf47
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
	shared/service_registry.go:44 +0x23e

**Comment by ethers** [comment]
just noticed if dupe of #4099 please close. thanks
