### ISSUE TITLE
runtime error: slice bounds out of range [:273522048] with capacity 496

### ISSUE THREAD

**Issue by xrow** [prysmaticlabs/prysm#4363]
Hi,

I have my beacon node running for some days. I find some funny errors. I tough I better report. MAybe they are fixed by now. I am runing version 0.27

```
time="2019-12-24 06:22:40" level=error msg="Panic occurred" error="runtime error: slice bounds out of range [:273522048] with capacity 496" prefix=sync topic="/eth2/beacon_block/ssz"
--
  | goroutine 58133928 [running]:
  | runtime/debug.Stack(0x0, 0x0, 0x0)
  | GOROOT/src/runtime/debug/stack.go:24 +0x9d
  | runtime/debug.PrintStack()
  | GOROOT/src/runtime/debug/stack.go:16 +0x22
  | github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1.1(0xc00bd57c80, 0xc0001dccb0)
  | beacon-chain/sync/subscriber.go:109 +0x1e9
  | panic(0x1425f00, 0xc00b44c420)
  | GOROOT/src/runtime/panic.go:679 +0x1b2
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x1448f80, 0xc01018b3b0, 0x199, 0x18b5180, 0x1448f80, 0xc000d6af90, 0xe5, 0x1f0, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0x13c0
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14a11c0, 0xc000011f60, 0x196, 0x18b5180, 0x14a11c0, 0xc000d6af90, 0xe5, 0x1f0, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:153 +0x1284
  | github.com/prysmaticlabs/go-ssz/types.(*compositeSliceSSZ).Unmarshal(0x2421e70, 0x1268a00, 0xc0082918c8, 0x197, 0x18b5180, 0x1268a00, 0xc000d6af88, 0x1d2, 0x1f8, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/slice_composite.go:137 +0x44e
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14a9c80, 0xc008291860, 0x199, 0x18b5180, 0x14a9c80, 0xc000d6aeac, 0x2ae, 0x2d4, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0xf8d
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14b86c0, 0xc00bd57d38, 0x196, 0x18b5180, 0x14b86c0, 0xc000d6aeac, 0x2ae, 0x2d4, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:153 +0x1284
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14573e0, 0xc00bd57d00, 0x199, 0x18b5180, 0x14573e0, 0xc000d6ae00, 0x35a, 0x380, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0xf8d
  | github.com/prysmaticlabs/go-ssz.Unmarshal(0xc000d6ae00, 0x35a, 0x380, 0x14a7100, 0xc00bd57d00, 0x7f7689715d98, 0x0)
  | external/com_github_prysmaticlabs_go_ssz/ssz.go:106 +0x335
  | github.com/prysmaticlabs/prysm/beacon-chain/p2p/encoder.SszNetworkEncoder.Decode(0x0, 0xc000d6ae00, 0x35a, 0x380, 0x14a7100, 0xc00bd57d00, 0x143e2e0, 0xc008f19849)
  | beacon-chain/p2p/encoder/ssz.go:85 +0x69
  | github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1(0xc000d6ae00, 0x35a, 0x380, 0xc0007a4500)
  | beacon-chain/sync/subscriber.go:128 +0x3bf
  | created by github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func2
  | beacon-chain/sync/subscriber.go:172 +0x296
  | time="2019-12-24 06:22:46" level=error msg="Panic occurred" error="runtime error: slice bounds out of range [:1162221441] with capacity 496" prefix=sync topic="/eth2/beacon_block/ssz"
  | goroutine 58134793 [running]:
  | runtime/debug.Stack(0x0, 0x0, 0x0)
  | GOROOT/src/runtime/debug/stack.go:24 +0x9d
  | runtime/debug.PrintStack()
  | GOROOT/src/runtime/debug/stack.go:16 +0x22
  | github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1.1(0xc010669980, 0xc0001dccb0)
  | beacon-chain/sync/subscriber.go:109 +0x1e9
  | panic(0x1425f00, 0xc00ea72ee0)
  | GOROOT/src/runtime/panic.go:679 +0x1b2
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x1448f80, 0xc0120cff10, 0x199, 0x18b5180, 0x1448f80, 0xc000d70c10, 0xe5, 0x1f0, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0x13c0
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14a11c0, 0xc012e49528, 0x196, 0x18b5180, 0x14a11c0, 0xc000d70c10, 0xe5, 0x1f0, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:153 +0x1284
  | github.com/prysmaticlabs/go-ssz/types.(*compositeSliceSSZ).Unmarshal(0x2421e70, 0x1268a00, 0xc00c67e888, 0x197, 0x18b5180, 0x1268a00, 0xc000d70c08, 0x1d2, 0x1f8, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/slice_composite.go:137 +0x44e
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14a9c80, 0xc00c67e820, 0x199, 0x18b5180, 0x14a9c80, 0xc000d70b2c, 0x2ae, 0x2d4, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0xf8d
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14b86c0, 0xc010669a38, 0x196, 0x18b5180, 0x14b86c0, 0xc000d70b2c, 0x2ae, 0x2d4, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:153 +0x1284
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14573e0, 0xc010669a00, 0x199, 0x18b5180, 0x14573e0, 0xc000d70a80, 0x35a, 0x380, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0xf8d
  | github.com/prysmaticlabs/go-ssz.Unmarshal(0xc000d70a80, 0x35a, 0x380, 0x14a7100, 0xc010669a00, 0x7f76897156d0, 0x0)
  | external/com_github_prysmaticlabs_go_ssz/ssz.go:106 +0x335
  | github.com/prysmaticlabs/prysm/beacon-chain/p2p/encoder.SszNetworkEncoder.Decode(0x0, 0xc000d70a80, 0x35a, 0x380, 0x14a7100, 0xc010669a00, 0x143e2e0, 0xc005c63299)
  | beacon-chain/p2p/encoder/ssz.go:85 +0x69
  | github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1(0xc000d70a80, 0x35a, 0x380, 0xc0007a4500)
  | beacon-chain/sync/subscriber.go:128 +0x3bf
  | created by github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func2
  | beacon-chain/sync/subscriber.go:172 +0x296
  | time="2019-12-24 06:22:52" level=error msg="Panic occurred" error="runtime error: slice bounds out of range [:932472454] with capacity 496" prefix=sync topic="/eth2/beacon_block/ssz"
  | goroutine 58135673 [running]:
  | runtime/debug.Stack(0x0, 0x0, 0x0)
  | GOROOT/src/runtime/debug/stack.go:24 +0x9d
  | runtime/debug.PrintStack()
  | GOROOT/src/runtime/debug/stack.go:16 +0x22
  | github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1.1(0xc00fa7a800, 0xc0001dccb0)
  | beacon-chain/sync/subscriber.go:109 +0x1e9
  | panic(0x1425f00, 0xc00bb4da20)
  | GOROOT/src/runtime/panic.go:679 +0x1b2
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x1448f80, 0xc0138a0930, 0x199, 0x18b5180, 0x1448f80, 0xc003000c10, 0xe5, 0x1f0, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0x13c0
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14a11c0, 0xc00ce185e0, 0x196, 0x18b5180, 0x14a11c0, 0xc003000c10, 0xe5, 0x1f0, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:153 +0x1284
  | github.com/prysmaticlabs/go-ssz/types.(*compositeSliceSSZ).Unmarshal(0x2421e70, 0x1268a00, 0xc00d349728, 0x197, 0x18b5180, 0x1268a00, 0xc003000c08, 0x1d2, 0x1f8, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/slice_composite.go:137 +0x44e
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14a9c80, 0xc00d3496c0, 0x199, 0x18b5180, 0x14a9c80, 0xc003000b2c, 0x2ae, 0x2d4, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0xf8d
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14b86c0, 0xc00fa7a8b8, 0x196, 0x18b5180, 0x14b86c0, 0xc003000b2c, 0x2ae, 0x2d4, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:153 +0x1284
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14573e0, 0xc00fa7a880, 0x199, 0x18b5180, 0x14573e0, 0xc003000a80, 0x35a, 0x380, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0xf8d
  | github.com/prysmaticlabs/go-ssz.Unmarshal(0xc003000a80, 0x35a, 0x380, 0x14a7100, 0xc00fa7a880, 0x7f7689716460, 0x0)
  | external/com_github_prysmaticlabs_go_ssz/ssz.go:106 +0x335
  | github.com/prysmaticlabs/prysm/beacon-chain/p2p/encoder.SszNetworkEncoder.Decode(0x0, 0xc003000a80, 0x35a, 0x380, 0x14a7100, 0xc00fa7a880, 0x143e2e0, 0xc00b4a5271)
  | beacon-chain/p2p/encoder/ssz.go:85 +0x69
  | github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1(0xc003000a80, 0x35a, 0x380, 0xc0007a4500)
  | beacon-chain/sync/subscriber.go:128 +0x3bf
  | created by github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func2
  | beacon-chain/sync/subscriber.go:172 +0x296
  | time="2019-12-24 06:22:58" level=error msg="Panic occurred" error="runtime error: slice bounds out of range [:3089996204] with capacity 496" prefix=sync topic="/eth2/beacon_block/ssz"
  | goroutine 58137203 [running]:
  | runtime/debug.Stack(0x0, 0x0, 0x0)
  | GOROOT/src/runtime/debug/stack.go:24 +0x9d
  | runtime/debug.PrintStack()
  | GOROOT/src/runtime/debug/stack.go:16 +0x22
  | github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1.1(0xc014e79200, 0xc0001dccb0)
  | beacon-chain/sync/subscriber.go:109 +0x1e9
  | panic(0x1425f00, 0xc007207f20)
  | GOROOT/src/runtime/panic.go:679 +0x1b2
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x1448f80, 0xc01217b3b0, 0x199, 0x18b5180, 0x1448f80, 0xc003000190, 0xe5, 0x1f0, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0x13c0
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14a11c0, 0xc00cfba068, 0x196, 0x18b5180, 0x14a11c0, 0xc003000190, 0xe5, 0x1f0, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:153 +0x1284
  | github.com/prysmaticlabs/go-ssz/types.(*compositeSliceSSZ).Unmarshal(0x2421e70, 0x1268a00, 0xc0125d6068, 0x197, 0x18b5180, 0x1268a00, 0xc003000188, 0x1d2, 0x1f8, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/slice_composite.go:137 +0x44e
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14a9c80, 0xc0125d6000, 0x199, 0x18b5180, 0x14a9c80, 0xc0030000ac, 0x2ae, 0x2d4, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0xf8d
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14b86c0, 0xc014e792b8, 0x196, 0x18b5180, 0x14b86c0, 0xc0030000ac, 0x2ae, 0x2d4, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:153 +0x1284
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14573e0, 0xc014e79280, 0x199, 0x18b5180, 0x14573e0, 0xc003000000, 0x35a, 0x380, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0xf8d
  | github.com/prysmaticlabs/go-ssz.Unmarshal(0xc003000000, 0x35a, 0x380, 0x14a7100, 0xc014e79280, 0x7f7689716460, 0x0)
  | external/com_github_prysmaticlabs_go_ssz/ssz.go:106 +0x335
  | github.com/prysmaticlabs/prysm/beacon-chain/p2p/encoder.SszNetworkEncoder.Decode(0x0, 0xc003000000, 0x35a, 0x380, 0x14a7100, 0xc014e79280, 0x143e2e0, 0xc006d5cbc9)
  | beacon-chain/p2p/encoder/ssz.go:85 +0x69
  | github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1(0xc003000000, 0x35a, 0x380, 0xc0007a4500)
  | beacon-chain/sync/subscriber.go:128 +0x3bf
  | created by github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func2
  | beacon-chain/sync/subscriber.go:172 +0x296
  | time="2019-12-24 06:23:03" level=info msg="New peer connected" peer=16Uiu2HAmAy68aHhCEhiTaQX3dWD5eci2dmYiog778ymqYnYy5xLc prefix=p2p
  | time="2019-12-24 06:23:03" level=info msg="New peer connected" peer=16Uiu2HAmUYj89iS7jCXrnrGcrvdDgfBXB1H5zUis1GJXS7ovn467 prefix=p2p
  | time="2019-12-24 06:23:04" level=error msg="Panic occurred" error="runtime error: slice bounds out of range [:2324285323] with capacity 496" prefix=sync topic="/eth2/beacon_block/ssz"
  | goroutine 58138676 [running]:
  | runtime/debug.Stack(0x0, 0x0, 0x0)
  | GOROOT/src/runtime/debug/stack.go:24 +0x9d
  | runtime/debug.PrintStack()
  | GOROOT/src/runtime/debug/stack.go:16 +0x22
  | github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1.1(0xc0093fd100, 0xc0001dccb0)
  | beacon-chain/sync/subscriber.go:109 +0x1e9
  | panic(0x1425f00, 0xc003cea320)
  | GOROOT/src/runtime/panic.go:679 +0x1b2
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x1448f80, 0xc00a10f8f0, 0x199, 0x18b5180, 0x1448f80, 0xc000e42890, 0xe5, 0x1f0, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0x13c0
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14a11c0, 0xc00cfba1a8, 0x196, 0x18b5180, 0x14a11c0, 0xc000e42890, 0xe5, 0x1f0, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:153 +0x1284
  | github.com/prysmaticlabs/go-ssz/types.(*compositeSliceSSZ).Unmarshal(0x2421e70, 0x1268a00, 0xc010a69b38, 0x197, 0x18b5180, 0x1268a00, 0xc000e42888, 0x1d2, 0x1f8, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/slice_composite.go:137 +0x44e
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14a9c80, 0xc010a69ad0, 0x199, 0x18b5180, 0x14a9c80, 0xc000e427ac, 0x2ae, 0x2d4, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0xf8d
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14b86c0, 0xc0093fd1b8, 0x196, 0x18b5180, 0x14b86c0, 0xc000e427ac, 0x2ae, 0x2d4, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:153 +0x1284
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14573e0, 0xc0093fd180, 0x199, 0x18b5180, 0x14573e0, 0xc000e42700, 0x35a, 0x380, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0xf8d
  | github.com/prysmaticlabs/go-ssz.Unmarshal(0xc000e42700, 0x35a, 0x380, 0x14a7100, 0xc0093fd180, 0x7f7689716460, 0x0)
  | external/com_github_prysmaticlabs_go_ssz/ssz.go:106 +0x335
  | github.com/prysmaticlabs/prysm/beacon-chain/p2p/encoder.SszNetworkEncoder.Decode(0x0, 0xc000e42700, 0x35a, 0x380, 0x14a7100, 0xc0093fd180, 0x143e2e0, 0xc0049f6411)
  | beacon-chain/p2p/encoder/ssz.go:85 +0x69
  | github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1(0xc000e42700, 0x35a, 0x380, 0xc0007a4500)
  | beacon-chain/sync/subscriber.go:128 +0x3bf
  | created by github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func2
  | beacon-chain/sync/subscriber.go:172 +0x296
  | time="2019-12-24 06:23:10" level=error msg="Panic occurred" error="runtime error: slice bounds out of range [:2016915091] with capacity 496" prefix=sync topic="/eth2/beacon_block/ssz"
  | goroutine 58141155 [running]:
  | runtime/debug.Stack(0x0, 0x0, 0x0)
  | GOROOT/src/runtime/debug/stack.go:24 +0x9d
  | runtime/debug.PrintStack()
  | GOROOT/src/runtime/debug/stack.go:16 +0x22
  | github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1.1(0xc007676700, 0xc0001dccb0)
  | beacon-chain/sync/subscriber.go:109 +0x1e9
  | panic(0x1425f00, 0xc00f19abe0)
  | GOROOT/src/runtime/panic.go:679 +0x1b2
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x1448f80, 0xc01335a850, 0x199, 0x18b5180, 0x1448f80, 0xc000de8890, 0xe5, 0x1f0, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0x13c0
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14a11c0, 0xc012046100, 0x196, 0x18b5180, 0x14a11c0, 0xc000de8890, 0xe5, 0x1f0, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:153 +0x1284
  | github.com/prysmaticlabs/go-ssz/types.(*compositeSliceSSZ).Unmarshal(0x2421e70, 0x1268a00, 0xc0145a1588, 0x197, 0x18b5180, 0x1268a00, 0xc000de8888, 0x1d2, 0x1f8, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/slice_composite.go:137 +0x44e
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14a9c80, 0xc0145a1520, 0x199, 0x18b5180, 0x14a9c80, 0xc000de87ac, 0x2ae, 0x2d4, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0xf8d
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14b86c0, 0xc0076767b8, 0x196, 0x18b5180, 0x14b86c0, 0xc000de87ac, 0x2ae, 0x2d4, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:153 +0x1284
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14573e0, 0xc007676780, 0x199, 0x18b5180, 0x14573e0, 0xc000de8700, 0x35a, 0x380, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0xf8d
  | github.com/prysmaticlabs/go-ssz.Unmarshal(0xc000de8700, 0x35a, 0x380, 0x14a7100, 0xc007676780, 0x7f7689715d98, 0x0)
  | external/com_github_prysmaticlabs_go_ssz/ssz.go:106 +0x335
  | github.com/prysmaticlabs/prysm/beacon-chain/p2p/encoder.SszNetworkEncoder.Decode(0x0, 0xc000de8700, 0x35a, 0x380, 0x14a7100, 0xc007676780, 0x143e2e0, 0xc00a088ee9)
  | beacon-chain/p2p/encoder/ssz.go:85 +0x69
  | github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1(0xc000de8700, 0x35a, 0x380, 0xc0007a4500)
  | beacon-chain/sync/subscriber.go:128 +0x3bf
  | created by github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func2
  | beacon-chain/sync/subscriber.go:172 +0x296
  | time="2019-12-24 06:23:16" level=error msg="Panic occurred" error="runtime error: slice bounds out of range [:2594002822] with capacity 496" prefix=sync topic="/eth2/beacon_block/ssz"
  | goroutine 58142602 [running]:
  | runtime/debug.Stack(0x0, 0x0, 0x0)
  | GOROOT/src/runtime/debug/stack.go:24 +0x9d
  | runtime/debug.PrintStack()
  | GOROOT/src/runtime/debug/stack.go:16 +0x22
  | github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1.1(0xc00f5bf500, 0xc0001dccb0)
  | beacon-chain/sync/subscriber.go:109 +0x1e9
  | panic(0x1425f00, 0xc007c6fe80)
  | GOROOT/src/runtime/panic.go:679 +0x1b2
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x1448f80, 0xc0138fe000, 0x199, 0x18b5180, 0x1448f80, 0xc001a66890, 0xe5, 0x1f0, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0x13c0
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14a11c0, 0xc00928c9f0, 0x196, 0x18b5180, 0x14a11c0, 0xc001a66890, 0xe5, 0x1f0, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:153 +0x1284
  | github.com/prysmaticlabs/go-ssz/types.(*compositeSliceSSZ).Unmarshal(0x2421e70, 0x1268a00, 0xc005dc0138, 0x197, 0x18b5180, 0x1268a00, 0xc001a66888, 0x1d2, 0x1f8, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/slice_composite.go:137 +0x44e
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14a9c80, 0xc005dc00d0, 0x199, 0x18b5180, 0x14a9c80, 0xc001a667ac, 0x2ae, 0x2d4, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0xf8d
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14b86c0, 0xc00f5bf5b8, 0x196, 0x18b5180, 0x14b86c0, 0xc001a667ac, 0x2ae, 0x2d4, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:153 +0x1284
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14573e0, 0xc00f5bf580, 0x199, 0x18b5180, 0x14573e0, 0xc001a66700, 0x35a, 0x380, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0xf8d
  | github.com/prysmaticlabs/go-ssz.Unmarshal(0xc001a66700, 0x35a, 0x380, 0x14a7100, 0xc00f5bf580, 0x7f76897171f0, 0x0)
  | external/com_github_prysmaticlabs_go_ssz/ssz.go:106 +0x335
  | github.com/prysmaticlabs/prysm/beacon-chain/p2p/encoder.SszNetworkEncoder.Decode(0x0, 0xc001a66700, 0x35a, 0x380, 0x14a7100, 0xc00f5bf580, 0x143e2e0, 0xc00edc298f)
  | beacon-chain/p2p/encoder/ssz.go:85 +0x69
  | github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1(0xc001a66700, 0x35a, 0x380, 0xc0007a4500)
  | beacon-chain/sync/subscriber.go:128 +0x3bf
  | created by github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func2
  | beacon-chain/sync/subscriber.go:172 +0x296
  | time="2019-12-24 06:23:22" level=error msg="Panic occurred" error="runtime error: slice bounds out of range [:296363649] with capacity 496" prefix=sync topic="/eth2/beacon_block/ssz"
  | goroutine 58143851 [running]:
  | runtime/debug.Stack(0x0, 0x0, 0x0)
  | GOROOT/src/runtime/debug/stack.go:24 +0x9d
  | runtime/debug.PrintStack()
  | GOROOT/src/runtime/debug/stack.go:16 +0x22
  | github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1.1(0xc014070c80, 0xc0001dccb0)
  | beacon-chain/sync/subscriber.go:109 +0x1e9
  | panic(0x1425f00, 0xc006390600)
  | GOROOT/src/runtime/panic.go:679 +0x1b2
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x1448f80, 0xc00c5e3960, 0x199, 0x18b5180, 0x1448f80, 0xc000e43690, 0xe5, 0x1f0, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0x13c0
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14a11c0, 0xc0138339b0, 0x196, 0x18b5180, 0x14a11c0, 0xc000e43690, 0xe5, 0x1f0, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:153 +0x1284
  | github.com/prysmaticlabs/go-ssz/types.(*compositeSliceSSZ).Unmarshal(0x2421e70, 0x1268a00, 0xc009e002d8, 0x197, 0x18b5180, 0x1268a00, 0xc000e43688, 0x1d2, 0x1f8, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/slice_composite.go:137 +0x44e
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14a9c80, 0xc009e00270, 0x199, 0x18b5180, 0x14a9c80, 0xc000e435ac, 0x2ae, 0x2d4, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0xf8d
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14b86c0, 0xc014070d38, 0x196, 0x18b5180, 0x14b86c0, 0xc000e435ac, 0x2ae, 0x2d4, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:153 +0x1284
  | github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x2421e70, 0x14573e0, 0xc014070d00, 0x199, 0x18b5180, 0x14573e0, 0xc000e43500, 0x35a, 0x380, 0x0, ...)
  | external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0xf8d
  | github.com/prysmaticlabs/go-ssz.Unmarshal(0xc000e43500, 0x35a, 0x380, 0x14a7100, 0xc014070d00, 0x7f7689717f80, 0x0)
  | external/com_github_prysmaticlabs_go_ssz/ssz.go:106 +0x335
  | github.com/prysmaticlabs/prysm/beacon-chain/p2p/encoder.SszNetworkEncoder.Decode(0x0, 0xc000e43500, 0x35a, 0x380, 0x14a7100, 0xc014070d00, 0x143e2e0, 0xc003d39d41)
  | beacon-chain/p2p/encoder/ssz.go:85 +0x69
  | github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1(0xc000e43500, 0x35a, 0x380, 0xc0007a4500)
  | beacon-chain/sync/subscriber.go:128 +0x3bf
  | created by github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func2
  | beacon-chain/sync/subscriber.go:172 +0x296

```

**Comment by rauljordan** [comment]
Hi @xrow this is a known bug that occurred with some other types of nodes syncing with the wrong configuration with Prysm nodes. This has now been fixed and will no longer be a problem in our upcoming testnet restart this January. Please let us know if this ever happens again.
