### ISSUE TITLE
Slice out of bounds when initializing deposit cache

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#4415]
Not sure how to reproduce but this behavior is currently occurring in dev testnet. It looks like only 16701 deposits were saved, but there are 16786 valid deposits. This is on v0.9.2 branch.

```
panic: runtime error: slice bounds out of range [16768:16701] [recovered]
        panic: runtime error: slice bounds out of range [16768:16701]

goroutine 1 [running]:
main.main.func2(0xc0005f6f50)
        beacon-chain/main.go:131 +0x12f
panic(0x169b0e0, 0xc00a45f800)
        GOROOT/src/runtime/panic.go:679 +0x1b2
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).initDepositCaches(0xc00010d8c0, 0x1b31460, 0xc00051e540, 0xc0087de000, 0x413d, 0x4c00, 0x8ca0d2, 0x7ffc6dc41e45)
        beacon-chain/powchain/service.go:418 +0x385
github.com/prysmaticlabs/prysm/beacon-chain/powchain.NewService(0x1b31460, 0xc00051e540, 0xc000f59600, 0x18f50f6c2592f343, 0xe326f5d3, 0x43e686)
        beacon-chain/powchain/service.go:206 +0x7d5
github.com/prysmaticlabs/prysm/beacon-chain/node.(*BeaconNode).registerPOWChainService(0xc0005f77a0, 0xc00010db80, 0x0, 0x0)
        beacon-chain/node/node.go:338 +0x273
github.com/prysmaticlabs/prysm/beacon-chain/node.NewBeaconNode(0xc00010db80, 0x5, 0x5, 0x0)
        beacon-chain/node/node.go:114 +0x37a
main.startNode(0xc00010db80, 0x0, 0xc0000fbcb0)
        beacon-chain/main.go:152 +0x92
github.com/urfave/cli.HandleAction(0x151a620, 0x1959908, 0xc00010db80, 0xc00010db80, 0x0)
        external/com_github_urfave_cli/app.go:514 +0xbe
github.com/urfave/cli.(*App).Run(0xc0000c6a80, 0xc0000c6000, 0x1c, 0x1c, 0x0, 0x0)
        external/com_github_urfave_cli/app.go:274 +0x5f6
main.main()
        beacon-chain/main.go:135 +0x1ed
```

**Comment by prestonvanloon** [comment]
Resolved by #4422
