### ISSUE TITLE
Chain node stop sync

### ISSUE THREAD

**Issue by msc82** [prysmaticlabs/prysm#4542]
```
[2020-01-14 13:06:07]  INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=1
[2020-01-14 13:06:07]  INFO blockchain: Finished applying state transition attestations=29 deposits=0 slot=32608
[2020-01-14 13:06:07]  INFO sync: Processed ancestor block with slot 32608 and cleared pending block cache
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11b7580]

goroutine 193 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).processPendingBlocks(0xc00272a000, 0x1b4c840, 0xc00b7d80c0, 0x0, 0x0)
        beacon-chain/sync/pending_blocks_queue.go:54 +0x3e0
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).processPendingBlocksQueue.func1()
        beacon-chain/sync/pending_blocks_queue.go:28 +0x3c
github.com/prysmaticlabs/prysm/shared/runutil.RunEvery.func1(0xc0026de230, 0x2542688, 0x5b, 0xc00341a1e0, 0x1b4c780, 0xc0006e5f80)
        shared/runutil/every.go:22 +0xec
created by github.com/prysmaticlabs/prysm/shared/runutil.RunEvery
        shared/runutil/every.go:17 +0x136
```

**Comment by prestonvanloon** [comment]
We haven't seen reports of this recently. Closing, but please re-open if you are still having issues. Thanks!
