### ISSUE TITLE
Panic: could not process block from fork choice service: pre state of slot 35xxx does not exist

### ISSUE THREAD

**Issue by KuDeTa** [prysmaticlabs/prysm#4554]
On latest pull, as of 18:00 GMT 14/1/20.

```
[2020-01-15 10:20:18]  INFO initial-sync: Processing block 35374/39101 - estimated time remaining 1h28m44s blocksPerSecond=0.7 peers=4/5
[2020-01-15 10:20:21]  INFO initial-sync: Processing block 35374/39101 - estimated time remaining 1h22m49s blocksPerSecond=0.8 peers=4/5
[2020-01-15 10:20:21]  INFO initial-sync: Processing block 35377/39101 - estimated time remaining 1h17m35s blocksPerSecond=0.8 peers=4/5
[2020-01-15 10:20:22]  INFO initial-sync: Processing block 35378/39101 - estimated time remaining 1h13m0s blocksPerSecond=0.8 peers=4/5
[2020-01-15 10:20:22]  INFO initial-sync: Processing block 35379/39101 - estimated time remaining 1h8m55s blocksPerSecond=0.9 peers=4/5
[2020-01-15 10:20:23]  INFO initial-sync: Processing block 35383/39101 - estimated time remaining 1h5m13s blocksPerSecond=0.9 peers=4/5
[2020-01-15 10:20:23]  INFO initial-sync: Processing block 35386/39101 - estimated time remaining 1h1m55s blocksPerSecond=1.0 peers=4/5
[2020-01-15 10:20:23]  INFO initial-sync: Processing block 35386/39101 - estimated time remaining 58m58s blocksPerSecond=1.1 peers=4/5
[2020-01-15 10:20:23]  INFO initial-sync: Processing block 35390/39101 - estimated time remaining 56m13s blocksPerSecond=1.1 peers=4/5
[2020-01-15 10:20:23]  INFO initial-sync: Processing block 35390/39101 - estimated time remaining 53m46s blocksPerSecond=1.1 peers=4/5
[2020-01-15 10:20:23]  INFO initial-sync: Processing block 35390/39101 - estimated time remaining 51m32s blocksPerSecond=1.2 peers=4/5
[2020-01-15 10:20:23]  INFO initial-sync: Processing block 35395/39101 - estimated time remaining 49m24s blocksPerSecond=1.2 peers=4/5
[2020-01-15 10:20:23]  INFO initial-sync: Processing block 35398/39101 - estimated time remaining 47m28s blocksPerSecond=1.3 peers=4/5
[2020-01-15 10:20:23]  INFO initial-sync: Processing block 35403/39101 - estimated time remaining 45m39s blocksPerSecond=1.4 peers=4/5
[2020-01-15 10:20:23]  INFO initial-sync: Processing block 35410/39101 - estimated time remaining 43m56s blocksPerSecond=1.4 peers=4/5
[2020-01-15 10:20:23]  INFO initial-sync: Processing block 35414/39101 - estimated time remaining 42m22s blocksPerSecond=1.4 peers=4/5
[2020-01-15 10:20:23]  INFO initial-sync: Processing block 35417/39101 - estimated time remaining 40m56s blocksPerSecond=1.5 peers=4/5
[2020-01-15 10:20:23]  INFO initial-sync: Processing block 35418/39101 - estimated time remaining 39m36s blocksPerSecond=1.6 peers=4/5
[2020-01-15 10:20:23]  INFO initial-sync: Processing block 35418/39101 - estimated time remaining 38m21s blocksPerSecond=1.6 peers=4/5
[2020-01-15 10:20:23]  INFO initial-sync: Processing block 35434/39101 - estimated time remaining 37m2s blocksPerSecond=1.6 peers=4/5
[2020-01-15 10:20:23]  INFO initial-sync: Processing block 35447/39101 - estimated time remaining 35m49s blocksPerSecond=1.7 peers=4/5
[2020-01-15 10:20:23]  INFO initial-sync: Processing block 35450/39101 - estimated time remaining 34m46s blocksPerSecond=1.8 peers=4/5
[2020-01-15 10:20:23]  INFO initial-sync: Processing block 35451/39101 - estimated time remaining 33m47s blocksPerSecond=1.8 peers=4/5
[2020-01-15 10:20:23]  INFO initial-sync: Processing block 35454/39101 - estimated time remaining 32m51s blocksPerSecond=1.9 peers=4/5
[2020-01-15 10:20:23]  INFO initial-sync: Processing block 35380/39101 - estimated time remaining 32m38s blocksPerSecond=1.9 peers=1/5
[2020-01-15 10:20:23]  INFO forkchoice: Executing state transition on block root=0xb81eac08... slot=35380
[2020-01-15 10:20:24]  INFO blockchain: Finished applying state transition attestations=5 deposits=0 slot=35380
[2020-01-15 10:20:24]  INFO initial-sync: Processing block 35380/39102 - estimated time remaining 31m48s blocksPerSecond=1.9 peers=1/5
**panic: could not process block from fork choice service: pre state of slot 35380 does not exist**
goroutine 221 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).Start(0xc0003764e0)
	beacon-chain/sync/initial-sync/service.go:119 +0xd0d
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
	shared/service_registry.go:44 +0x23e
```

and again, at a lower block

```
[2020-01-15 12:19:52]  INFO initial-sync: Processing block 35319/39699 - estimated time remaining 58m24s blocksPerSecond=1.2 peers=3/7
[2020-01-15 12:19:52]  INFO initial-sync: Processing block 35325/39699 - estimated time remaining 56m4s blocksPerSecond=1.3 peers=3/7
[2020-01-15 12:19:52]  INFO initial-sync: Processing block 35327/39699 - estimated time remaining 53m58s blocksPerSecond=1.4 peers=3/7
[2020-01-15 12:19:52]  INFO initial-sync: Processing block 35334/39699 - estimated time remaining 51m57s blocksPerSecond=1.4 peers=3/7
[2020-01-15 12:19:52]  INFO initial-sync: Processing block 35336/39699 - estimated time remaining 50m8s blocksPerSecond=1.4 peers=3/7
[2020-01-15 12:19:52]  INFO initial-sync: Processing block 35337/39699 - estimated time remaining 48m28s blocksPerSecond=1.5 peers=3/7
[2020-01-15 12:19:52]  INFO initial-sync: Processing block 35342/39699 - estimated time remaining 46m50s blocksPerSecond=1.6 peers=3/7
[2020-01-15 12:19:52]  INFO initial-sync: Processing block 35345/39699 - estimated time remaining 45m21s blocksPerSecond=1.6 peers=3/7
[2020-01-15 12:19:52]  INFO initial-sync: Processing block 35345/39699 - estimated time remaining 43m58s blocksPerSecond=1.6 peers=3/7
[2020-01-15 12:20:44]  INFO initial-sync: Processing block 35355/39703 - estimated time remaining 24h9m20s blocksPerSecond=0.1 peers=3/7
[2020-01-15 12:20:44]  INFO initial-sync: Processing block 35357/39703 - estimated time remaining 12h4m20s blocksPerSecond=0.1 peers=3/7
[2020-01-15 12:20:46]  INFO initial-sync: Processing block 35369/39703 - estimated time remaining 8h1m33s blocksPerSecond=0.1 peers=3/7
[2020-01-15 12:20:46]  INFO initial-sync: Processing block 35370/39703 - estimated time remaining 6h1m5s blocksPerSecond=0.2 peers=3/7
[2020-01-15 12:20:46]  INFO initial-sync: Processing block 35376/39703 - estimated time remaining 4h48m28s blocksPerSecond=0.2 peers=3/7
[2020-01-15 12:20:46]  INFO initial-sync: Processing block 35385/39703 - estimated time remaining 3h59m53s blocksPerSecond=0.3 peers=3/7
[2020-01-15 12:20:46]  INFO initial-sync: Processing block 35388/39703 - estimated time remaining 3h25m28s blocksPerSecond=0.3 peers=3/7
[2020-01-15 12:20:46]  INFO initial-sync: Processing block 35390/39703 - estimated time remaining 2h59m42s blocksPerSecond=0.4 peers=3/7
[2020-01-15 12:20:46]  INFO initial-sync: Processing block 35390/39703 - estimated time remaining 2h39m44s blocksPerSecond=0.5 peers=3/7
[2020-01-15 12:20:47]  INFO initial-sync: Processing block 35362/39703 - estimated time remaining 2h24m42s blocksPerSecond=0.5 peers=1/7
panic: could not process block from fork choice service: pre state of slot 35362 does not exist

goroutine 210 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).Start(0xc002b84c00)
	beacon-chain/sync/initial-sync/service.go:119 +0xd0d
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
	shared/service_registry.go:44 +0x23e
```

**Comment by tzapu** [comment]
seeing it as well but at a different block
```
time="2020-01-15 12:23:27" level=info msg="Processing block 35561/39717 - estimated time remaining 53m16s" blocksPerSecond=1.3 peers="1/29" prefix=initial-sync
panic: could not process block from fork choice service: pre state of slot 35561 does not exist

goroutine 193 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).Start(0xc0003eb680)
        beacon-chain/sync/initial-sync/service.go:119 +0xd0d
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
        shared/service_registry.go:44 +0x23e
```

**Comment by tzapu** [comment]
and
```
time="2020-01-15 12:30:31" level=info msg="Processing block 35638/39752 - estimated time remaining 41m33s" blocksPerSecond=1.6 peers="1/30" prefix=initial-sync
panic: could not process block from fork choice service: pre state of slot 35638 does not exist

goroutine 192 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).Start(0xc00289a000)
        beacon-chain/sync/initial-sync/service.go:119 +0xd0d
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
        shared/service_registry.go:44 +0x23e
```

**Comment by tzapu** [comment]
after which it resets sync around block 35000

**Comment by KuDeTa** [comment]
Yeah, on latest attempt i reset to 35138


...
[2020-01-15 12:38:50]  INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=2
[2020-01-15 12:38:51]  INFO p2p: Peer connected active=6 peer=16Uiu2HAmAsyW714qpiYz9dNEoDyLa29SuzXwU4sY3fQrRtUxN1bT
[2020-01-15 12:38:55]  INFO initial-sync: Processing block 35138/39794 - estimated time remaining 25h52m0s blocksPerSecond=0.1 peers=3/6
[2020-01-15 12:39:00]  INFO initial-sync: Processing block 35140/39795 - estimated time remaining 12h55m50s blocksPerSecond=0.1 peers=3/6
[2020-01-15 12:39:01]  INFO initial-sync: Processing block 35141/39795 - estimated time remaining 8h37m6s blocksPerSecond=0.1 peers=3/6
[2020-01-15 12:39:02]  INFO initial-sync: Processing block 35142/39795 - estimated time remaining 6h27m45s blocksPerSecond=0.2 peers=3/6
[2020-01-15 12:39:02]  INFO initial-sync: Processing block 35143/39795 - estimated time remaining 5h10m8s blocksPerSecond=0.2 peers=3/6
[2020-01-15 12:39:03]  INFO initial-sync: Processing block 35144/39795 - estimated time remaining 4h18m23s blocksPerSecond=0.3 peers=3/6
[2020-01-15 12:39:03]  INFO initial-sync: Processing block 35145/39795 - estimated time remaining 3h41m25s blocksPerSecond=0.3 peers=3/6
[2020-01-15 12:39:04]  INFO initial-sync: Processing block 35146/39795 - estimated time remaining 3h13m42s blocksPerSecond=0.4 peers=3/6
[2020-01-15 12:39:04]  INFO initial-sync: Processing block 35147/39795 - estimated time remaining 2h52m8s blocksPerSecond=0.5 peers=3/6
[2020-01-15 12:39:05]  INFO initial-sync: Processing block 35148/39795 - estimated time remaining 2h34m54s blocksPerSecond=0.5 peers=3/6
[2020-01-15 12:39:05]  INFO initial-sync: Processing block 35149/39795 - estimated time remaining 2h20m47s blocksPerSecond=0.6 peers=3/6
[2020-01-15 12:39:05]  INFO initial-sync: Processing block 35151/39795 - estimated time remaining 2h9m0s blocksPerSecond=0.6 peers=3/6
[2020-01-15 12:39:06]  INFO initial-sync: Processing block 35152/39795 - estimated time remaining 1h59m3s blocksPerSecond=0.7 peers=3/6
[2020-01-15 12:39:07]  INFO initial-sync: Processing block 35154/39795 - estimated time remaining 1h50m30s blocksPerSecond=0.7 peers=3/6
[2020-01-15 12:39:07]  INFO initial-sync: Processing block 35155/39795 - estimated time remaining 1h43m6s blocksPerSecond=0.8 peers=3/6

**Comment by prestonvanloon** [comment]
We haven't seen reports of this issue in a few days. Closing for now, but please reopen if you are experiencing continued issues.
