### ISSUE TITLE
gRPC panic when using GetValidatorParticipation

### ISSUE THREAD

**Issue by guybrush** [prysmaticlabs/prysm#4555]
Getting this in the logs every few seconds. 

Note: The node is used by eth2-beaconchain-explorer@770d4b3.

```
time="2020-01-15 11:52:47" level=error msg="gRPC panicked!" error="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 294323 [running]:
runtime/debug.Stack(0xc0000e2690, 0x17b0842, 0x5)
	GOROOT/src/runtime/debug/stack.go:24 +0x9d
github.com/prysmaticlabs/prysm/shared/traceutil.RecoveryHandlerFunc(0x1b4e9e0, 0xc01131a5a0, 0x1599000, 0x262bfd0, 0x1b736c0, 0x16)
	shared/traceutil/recovery_interceptor_option.go:29 +0x155
github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom(0x1b4e9e0, 0xc01131a5a0, 0x1599000, 0x262bfd0, 0x1974600, 0x203003, 0x178b480)
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:52 +0x5a
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1(0x1b4e9e0, 0xc01131a5a0, 0xc0027ae020, 0xc0019d9968)
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:26 +0x77
panic(0x1599000, 0x262bfd0)
	GOROOT/src/runtime/panic.go:679 +0x1b2
github.com/prysmaticlabs/prysm/beacon-chain/rpc/beacon.(*Server).GetValidatorParticipation(0xc0027ca000, 0x1b4e9e0, 0xc01131a660, 0xc01131a5d0, 0xc0027ca000, 0x0, 0x0)
	beacon-chain/rpc/beacon/validators.go:454 +0x35d
github.com/prysmaticlabs/ethereumapis/eth/v1alpha1._BeaconChain_GetValidatorParticipation_Handler.func1(0x1b4e9e0, 0xc01131a660, 0x173e300, 0xc01131a5d0, 0x180690f, 0x3c, 0x1b4e9e0, 0xc01131a660)
	bazel-out/k8-fastbuild/bin/external/com_github_prysmaticlabs_ethereumapis/eth/v1alpha1/linux_amd64_stripped/go_proto%/github.com/prysmaticlabs/ethereumapis/eth/v1alpha1/beacon_chain.pb.go:3089 +0x86
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1(0x1b4e9e0, 0xc01131a5a0, 0x173e300, 0xc01131a5d0, 0xc00f599ca0, 0xc00f599cc0, 0x3, 0x3, 0x1b5a500, 0xc00943e7c0)
	external/com_github_grpc_ecosystem_go_grpc_middleware/tracing/opentracing/server_interceptors.go:31 +0x165
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x1b4e9e0, 0xc01131a5a0, 0x173e300, 0xc01131a5d0, 0x3c, 0xc0119f0460, 0x12, 0x1)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x1b4e9e0, 0xc01131a5a0, 0x173e300, 0xc01131a5d0, 0xc00f599ca0, 0xc00f599ce0, 0xc00de32780, 0x460ada, 0xc00de32780, 0xc0078e88a8)
	external/com_github_grpc_ecosystem_go_grpc_prometheus/server_metrics.go:107 +0xad
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x1b4e9e0, 0xc01131a5a0, 0x173e300, 0xc01131a5d0, 0x166c660, 0x1213dff, 0x1b4e9e0, 0x20)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1(0x1b4e9e0, 0xc01131a5a0, 0x173e300, 0xc01131a5d0, 0xc00f599ca0, 0xc00f599d00, 0x0, 0x0, 0x0, 0x0)
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:30 +0xe2
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x1b4e9e0, 0xc01131a5a0, 0x173e300, 0xc01131a5d0, 0xc0007b40e0, 0xc00472da00, 0xc0078e89e8, 0x43eef8)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x1b4e9e0, 0xc01131a5a0, 0x173e300, 0xc01131a5d0, 0xc00f599ca0, 0xc00f599cc0, 0xc0078e8a58, 0x533358, 0x169ec20, 0xc01131a5a0)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:34 +0xd5
github.com/prysmaticlabs/ethereumapis/eth/v1alpha1._BeaconChain_GetValidatorParticipation_Handler(0x1738d60, 0xc0027ca000, 0x1b4e9e0, 0xc01131a5a0, 0xc0119f02d0, 0xc0027b4180, 0x1b4e9e0, 0xc01131a5a0, 0xc014038038, 0x3)
	bazel-out/k8-fastbuild/bin/external/com_github_prysmaticlabs_ethereumapis/eth/v1alpha1/linux_amd64_stripped/go_proto%/github.com/prysmaticlabs/ethereumapis/eth/v1alpha1/beacon_chain.pb.go:3091 +0x14b
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0027c4000, 0x1b62180, 0xc01153a000, 0xc00472da00, 0xc0027b45d0, 0x263f140, 0x0, 0x0, 0x0)
	external/org_golang_google_grpc/server.go:998 +0x46a
google.golang.org/grpc.(*Server).handleStream(0xc0027c4000, 0x1b62180, 0xc01153a000, 0xc00472da00, 0x0)
	external/org_golang_google_grpc/server.go:1278 +0xd97
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00a688020, 0xc0027c4000, 0x1b62180, 0xc01153a000, 0xc00472da00)
	external/org_golang_google_grpc/server.go:717 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	external/org_golang_google_grpc/server.go:715 +0xa1
"
```

**Comment by ppratscher** [comment]
Can confirm, we are experiencing the same error on our prod https://beaconcha.in node
