### ISSUE TITLE
panic: no peers left to request blocks

### ISSUE THREAD

**Issue by KuDeTa** [prysmaticlabs/prysm#4565]
[prysm.txt](https://github.com/prysmaticlabs/prysm/files/4072807/prysm.txt)

Unable to sync on latest pull (as of 9:00 GMT 15/1/20).

Eventually, we run out of peers:

```[2020-01-16 15:51:41] DEBUG initial-sync: Request failed, trying to round robin with other peers error=max dial attempts exceeded
failed to send request to peer
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).requestBlocks
	beacon-chain/sync/initial-sync/round_robin.go:278
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync.func2.1
	beacon-chain/sync/initial-sync/round_robin.go:122
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357 peer=16Uiu2HAmQuAsKeXe8vkhWzMyhHg4WrrhEmu6SXsDwzD9ADUCExNH remaining peers=0
panic: no peers left to request blocks

goroutine 215 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).Start(0xc00cb67980)
	beacon-chain/sync/initial-sync/service.go:119 +0xd0d
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
	shared/service_registry.go:44 +0x23e
```

Full debug attached.

**Comment by KuDeTa** [comment]
solved with latest pull (17/1/20 @ 09:00 GMT)

**Comment by 0xKiwi** [comment]
Duplicate of #4212 4212

**Comment by AndreMiras** [comment]
I'm running on `Prysm/Git commit: e7ecd9329a57bf2f84f8266eeb62565ba08b4f91. Built at: 2020-01-19 03:31:48+00:00` docker and I had the issue today actually.
