### ISSUE TITLE
6609 Segmentation fault during sync & peers quick drop from 15/50 to 1/50 in 4 seconds

### ISSUE THREAD

**Issue by somuchid** [prysmaticlabs/prysm#4618]
commit: {STABLE_GIT_COMMIT}. Built at: 2020-01-22T10:03:59-05:00
```
[2020-01-22 08:24:45]  INFO initial-sync: Processing block 90367/90423 - estimated time remaining 24s blocksPerSecond=2.2 peers=15/50
[2020-01-22 08:24:46]  INFO initial-sync: Processing block 90368/90423 - estimated time remaining 23s blocksPerSecond=2.3 peers=15/50
[2020-01-22 08:24:50]  INFO initial-sync: Processing block 90369/90424 - estimated time remaining 28s blocksPerSecond=1.9 peers=1/50
[2020-01-22 08:24:50]  INFO forkchoice: Executing state transition on block root=0xff82eeb3... slot=90369
[2020-01-22 08:24:51]  INFO blockchain: Finished applying state transition attestations=6 deposits=0 slot=90369
[2020-01-22 08:24:51]  INFO initial-sync: Processing block 90370/90424 - estimated time remaining 30s blocksPerSecond=1.8 peers=1/50
[2020-01-22 08:24:51]  INFO forkchoice: Executing state transition on block root=0x23348808... slot=90370
[2020-01-22 08:24:52]  INFO blockchain: Finished applying state transition attestations=15 deposits=0 slot=90370
[2020-01-22 08:24:52]  INFO initial-sync: Processing block 90371/90424 - estimated time remaining 30s blocksPerSecond=1.8 peers=1/50
[2020-01-22 08:24:52]  INFO forkchoice: Executing state transition on block root=0x97b4c038... slot=90371
[2020-01-22 08:24:53]  INFO blockchain: Finished applying state transition attestations=12 deposits=0 slot=90371
[2020-01-22 08:24:53]  INFO initial-sync: Processing block 90372/90424 - estimated time remaining 29s blocksPerSecond=1.8 peers=1/50
[2020-01-22 08:24:53]  INFO forkchoice: Executing state transition on block root=0x968775fd... slot=90372
[2020-01-22 08:24:53]  INFO blockchain: Finished applying state transition attestations=12 deposits=0 slot=90372
[2020-01-22 08:24:53]  INFO initial-sync: Processing block 90373/90424 - estimated time remaining 30s blocksPerSecond=1.7 peers=1/50
[2020-01-22 08:24:53]  INFO forkchoice: Executing state transition on block root=0xb892d650... slot=90373
[2020-01-22 08:24:54]  INFO blockchain: Finished applying state transition attestations=25 deposits=0 slot=90373
[2020-01-22 08:24:54]  INFO initial-sync: Processing block 90374/90424 - estimated time remaining 28s blocksPerSecond=1.8 peers=1/50
[2020-01-22 08:24:54]  INFO forkchoice: Executing state transition on block root=0x6d19c792... slot=90374
runtime: invalid pc-encoded table f=runtime.aeshash32 pc=0x491f03 targetpc=0x491f0b tab=[0/0]0x0
	value=0 until pc=0x491f03
fatal error: invalid runtime symbol table

goroutine 0 [idle]:
runtime: unexpected return pc for runtime.sigtramp called from 0x7feae280f540
stack: frame={sp:0xc0004c5968, fp:0xc0004c59c0} stack=[0xc0004be000,0xc0004c6000)
000000c0004c5868:  0000000000000000  0000000000000000 
000000c0004c5878:  0000000000000000  0000000000000000 
000000c0004c5888:  0000000000000000  0000000000000000 
000000c0004c5898:  000000c0004c5af0  000000c0004c59c0 
000000c0004c58a8:  000000c0004c5958  0000000000476f20 <runtime.sigtrampgo+496> 
000000c0004c58b8:  000000c00000001b  000000c0004c5af0 
000000c0004c58c8:  000000c0004c59c0  000000c000807c80 
000000c0004c58d8:  0000000000000000  0000000000000000 
000000c0004c58e8:  0000000000000000  0000000000000000 
000000c0004c58f8:  0000000000000000  0000000000000000 
000000c0004c5908:  0000000000000000  000000c000807c80 
000000c0004c5918:  0000000000000000  0000000000000000 
000000c0004c5928:  0000000000000000  0000000000000000 
000000c0004c5938:  0000000000000000  0000000000000000 
000000c0004c5948:  0000000000000000  0000000000000000 
000000c0004c5958:  000000c0004c59b0  0000000000493c63 <runtime.sigtramp+67> 
000000c0004c5968: <000000000000001b  000000c0004c5af0 
000000c0004c5978:  000000c0004c59c0  00000000533b73fe 
000000c0004c5988:  00000000fad56928  0000000084ee8cb7 
000000c0004c5998:  000000009fea806f  000000c0004c59b0 
000000c0004c59a8:  00000000d1434b7b  0000000001b83300 
000000c0004c59b8: !00007feae280f540 >0000000000000007 
000000c0004c59c8:  0000000000000000  000000c0004be000 
000000c0004c59d8:  0000000000000000  0000000000008000 
000000c0004c59e8:  00000000324c23fc  00000000ed2a4572 
000000c0004c59f8:  000000000ea56eee  0000000013ba32de 
000000c0004c5a08:  000000009fea806f  0000000084ee8cb7 
000000c0004c5a18:  00000000fad56928  00000000533b73fe 
000000c0004c5a28:  000000004d81c520  000000c0128ce780 
000000c0004c5a38:  0000000001b83300  00000000d1434b7b 
000000c0004c5a48:  000000009fea806f  000000005e3bf7fe 
000000c0004c5a58:  000000007418eaf9  000000c01e365840 
000000c0004c5a68:  0000000000a77638 <github.com/minio/sha256-simd.blockAvx2+632>  0000000000000286 
000000c0004c5a78:  002b000000000033  0000000000000000 
000000c0004c5a88:  0000000000000000  0000000000000000 
000000c0004c5a98:  0000000000000000  000000c0004c5b80 
000000c0004c5aa8:  0000000000000000  0000000000000000 
000000c0004c5ab8:  0000000000000000 
runtime.throw(0x17d852c, 0x1c)
	GOROOT/src/runtime/panic.go:774 +0x72
runtime.pcvalue(0x1cbcb78, 0x26806e0, 0x9d6da, 0x491f0b, 0xc0004c53d0, 0x2583c01, 0x448)
	GOROOT/src/runtime/symtab.go:723 +0x53d
runtime.funcspdelta(0x1cbcb78, 0x26806e0, 0x491f0b, 0xc0004c53d0, 0xc000000448)
	GOROOT/src/runtime/symtab.go:775 +0x5f
runtime.gentraceback(0xa77638, 0xc01e365840, 0x0, 0xc000807c80, 0x0, 0xc0004c5628, 0x40, 0x0, 0x0, 0x6, ...)
	GOROOT/src/runtime/traceback.go:220 +0x1598
runtime.sigprof(0xa77638, 0xc01e365840, 0x0, 0xc000807c80, 0xc0004b8000)
	GOROOT/src/runtime/proc.go:3760 +0x417
runtime.sighandler(0xc00000001b, 0xc0004c5af0, 0xc0004c59c0, 0xc000807c80)
	GOROOT/src/runtime/signal_sighandler.go:38 +0x706
runtime.sigtrampgo(0x1b, 0xc0004c5af0, 0xc0004c59c0)
	GOROOT/src/runtime/signal_unix.go:352 +0x1f0
runtime: unexpected return pc for runtime.sigtramp called from 0x7feae280f540
stack: frame={sp:0xc0004c5968, fp:0xc0004c59c0} stack=[0xc0004be000,0xc0004c6000)
000000c0004c5868:  0000000000000000  0000000000000000 
000000c0004c5878:  0000000000000000  0000000000000000 
000000c0004c5888:  0000000000000000  0000000000000000 
000000c0004c5898:  000000c0004c5af0  000000c0004c59c0 
000000c0004c58a8:  000000c0004c5958  0000000000476f20 <runtime.sigtrampgo+496> 
000000c0004c58b8:  000000c00000001b  000000c0004c5af0 
000000c0004c58c8:  000000c0004c59c0  000000c000807c80 
000000c0004c58d8:  0000000000000000  0000000000000000 
000000c0004c58e8:  0000000000000000  0000000000000000 
000000c0004c58f8:  0000000000000000  0000000000000000 
000000c0004c5908:  0000000000000000  000000c000807c80 
000000c0004c5918:  0000000000000000  0000000000000000 
000000c0004c5928:  0000000000000000  0000000000000000 
000000c0004c5938:  0000000000000000  0000000000000000 
000000c0004c5948:  0000000000000000  0000000000000000 
000000c0004c5958:  000000c0004c59b0  0000000000493c63 <runtime.sigtramp+67> 
000000c0004c5968: <000000000000001b  000000c0004c5af0 
000000c0004c5978:  000000c0004c59c0  00000000533b73fe 
000000c0004c5988:  00000000fad56928  0000000084ee8cb7 
000000c0004c5998:  000000009fea806f  000000c0004c59b0 
000000c0004c59a8:  00000000d1434b7b  0000000001b83300 
000000c0004c59b8: !00007feae280f540 >0000000000000007 
000000c0004c59c8:  0000000000000000  000000c0004be000 
000000c0004c59d8:  0000000000000000  0000000000008000 
000000c0004c59e8:  00000000324c23fc  00000000ed2a4572 
000000c0004c59f8:  000000000ea56eee  0000000013ba32de 
000000c0004c5a08:  000000009fea806f  0000000084ee8cb7 
000000c0004c5a18:  00000000fad56928  00000000533b73fe 
000000c0004c5a28:  000000004d81c520  000000c0128ce780 
000000c0004c5a38:  0000000001b83300  00000000d1434b7b 
000000c0004c5a48:  000000009fea806f  000000005e3bf7fe 
000000c0004c5a58:  000000007418eaf9  000000c01e365840 
000000c0004c5a68:  0000000000a77638 <github.com/minio/sha256-simd.blockAvx2+632>  0000000000000286 
000000c0004c5a78:  002b000000000033  0000000000000000 
000000c0004c5a88:  0000000000000000  0000000000000000 
000000c0004c5a98:  0000000000000000  000000c0004c5b80 
000000c0004c5aa8:  0000000000000000  0000000000000000 
000000c0004c5ab8:  0000000000000000 
runtime.sigtramp(0x7, 0x0, 0xc0004be000, 0x0, 0x8000, 0x324c23fc, 0xed2a4572, 0xea56eee, 0x13ba32de, 0x9fea806f, ...)
	GOROOT/src/runtime/sys_linux_amd64.s:357 +0x43

goroutine 289 [running]:
pchain.sh: line 1:  6609 Segmentation fault      (core dumped) ~/commands/binary/pchain --datadir=$HOME/prysmData --http-web3provider=http://localhost:8545 --web3provider=ws://localhost:8546 --min-sync-peers=10 --enable-upnp --peer /ip4/148.251.128.119/tcp/13000/p2p/16Uiu2HAmAsyW714qpiYz9dNEoDyLa29SuzXwU4sY3fQrRtUxN1bT --p2p-host-ip=$(curl -s v4.ident.me) --cache-proposer-indices --cache-filtered-block-tree --enable-ssz-cache --cpuprofile=$HOME/logs/cpu0118 --p2p-max-peers=50
```

**Comment by somuchid** [comment]
same problem happened again today at first run, after running new binary of latest pull. commit 5df77848bb5fd3bb0c3cfaf5a5fc95f3f743e2d6
[2020-01-23 09:10:00]  INFO initial-sync: Processing block 97793/97850 - estimated time remaining 34s blocksPerSecond=1.6 peers=1/50
[2020-01-23 09:10:00]  INFO forkchoice: Executing state transition on block root=0xe466e43c... slot=97793
[2020-01-23 09:10:01]  INFO blockchain: Finished applying state transition attestations=18 deposits=0 slot=97793
[2020-01-23 09:10:01]  INFO initial-sync: Processing block 97794/97850 - estimated time remaining 33s blocksPerSecond=1.6 peers=1/50
[2020-01-23 09:10:01]  INFO forkchoice: Executing state transition on block root=0xe1ab3abb... slot=97794
[2020-01-23 09:10:02]  INFO blockchain: Finished applying state transition attestations=15 deposits=1 slot=97794
[2020-01-23 09:10:02]  INFO initial-sync: Processing block 97795/97850 - estimated time remaining 35s blocksPerSecond=1.6 peers=1/50
[2020-01-23 09:10:02]  INFO forkchoice: Executing state transition on block root=0x24a07ffb... slot=97795
[2020-01-23 09:10:03]  INFO blockchain: Finished applying state transition attestations=17 deposits=0 slot=97795
[2020-01-23 09:10:03]  INFO initial-sync: Processing block 97796/97850 - estimated time remaining 36s blocksPerSecond=1.5 peers=1/50
[2020-01-23 09:10:03]  INFO forkchoice: Executing state transition on block root=0x7568b967... slot=97796
[2020-01-23 09:10:04]  INFO blockchain: Finished applying state transition attestations=23 deposits=0 slot=97796
[2020-01-23 09:10:04]  INFO initial-sync: Processing block 97797/97850 - estimated time remaining 36s blocksPerSecond=1.4 peers=1/50
[2020-01-23 09:10:04]  INFO forkchoice: Executing state transition on block root=0x3bd3e50f... slot=97797
[2020-01-23 09:10:05]  INFO blockchain: Finished applying state transition attestations=12 deposits=0 slot=97797
[2020-01-23 09:10:05]  INFO initial-sync: Processing block 97798/97850 - estimated time remaining 37s blocksPerSecond=1.4 peers=1/50
[2020-01-23 09:10:05]  INFO forkchoice: Executing state transition on block root=0xbf0be61a... slot=97798
[2020-01-23 09:10:06]  INFO blockchain: Finished applying state transition attestations=14 deposits=0 slot=97798
[2020-01-23 09:10:06]  INFO initial-sync: Processing block 97799/97850 - estimated time remaining 37s blocksPerSecond=1.4 peers=1/50
[2020-01-23 09:10:06]  INFO forkchoice: Executing state transition on block root=0x28788d9f... slot=97799
[2020-01-23 09:10:07]  INFO blockchain: Finished applying state transition attestations=18 deposits=0 slot=97799
[2020-01-23 09:10:07]  INFO initial-sync: Processing block 97800/97850 - estimated time remaining 38s blocksPerSecond=1.3 peers=1/50
[2020-01-23 09:10:07]  INFO forkchoice: Executing state transition on block root=0x4388c202... slot=97800
[2020-01-23 09:10:08]  INFO blockchain: Finished applying state transition attestations=17 deposits=0 slot=97800
[2020-01-23 09:10:08]  INFO initial-sync: Processing block 97801/97850 - estimated time remaining 40s blocksPerSecond=1.2 peers=1/50
[2020-01-23 09:10:08]  INFO forkchoice: Executing state transition on block root=0xcf401d46... slot=97801
[2020-01-23 09:10:08]  INFO blockchain: Finished applying state transition attestations=18 deposits=0 slot=97801
[2020-01-23 09:10:08]  INFO initial-sync: Processing block 97802/97850 - estimated time remaining 40s blocksPerSecond=1.2 peers=1/50
[2020-01-23 09:10:08]  INFO forkchoice: Executing state transition on block root=0x6a60a1e6... slot=97802
[2020-01-23 09:10:09]  INFO blockchain: Finished applying state transition attestations=10 deposits=0 slot=97802
[2020-01-23 09:10:09]  INFO initial-sync: Processing block 97803/97850 - estimated time remaining 40s blocksPerSecond=1.1 peers=1/50
[2020-01-23 09:10:09]  INFO forkchoice: Executing state transition on block root=0x8424dae8... slot=97803
[2020-01-23 09:10:10]  INFO blockchain: Finished applying state transition attestations=12 deposits=0 slot=97803
[2020-01-23 09:10:10]  INFO initial-sync: Processing block 97804/97850 - estimated time remaining 43s blocksPerSecond=1.1 peers=1/50
[2020-01-23 09:10:10]  INFO forkchoice: Executing state transition on block root=0x33773b18... slot=97804
[2020-01-23 09:10:11]  INFO blockchain: Finished applying state transition attestations=16 deposits=0 slot=97804
[2020-01-23 09:10:11]  INFO initial-sync: Processing block 97805/97850 - estimated time remaining 40s blocksPerSecond=1.1 peers=1/50
[2020-01-23 09:10:11]  INFO forkchoice: Executing state transition on block root=0x8cc56d42... slot=97805
[2020-01-23 09:10:12]  INFO blockchain: Finished applying state transition attestations=13 deposits=0 slot=97805
[2020-01-23 09:10:12]  INFO initial-sync: Processing block 97806/97851 - estimated time remaining 42s blocksPerSecond=1.1 peers=1/50
[2020-01-23 09:10:12]  INFO forkchoice: Executing state transition on block root=0xc19528b1... slot=97806
[2020-01-23 09:10:13]  INFO blockchain: Finished applying state transition attestations=12 deposits=0 slot=97806
[2020-01-23 09:10:13]  INFO initial-sync: Processing block 97807/97851 - estimated time remaining 44s blocksPerSecond=1.0 peers=1/50
[2020-01-23 09:10:13]  INFO forkchoice: Executing state transition on block root=0xfbb95e06... slot=97807
[2020-01-23 09:10:14]  INFO blockchain: Finished applying state transition attestations=12 deposits=0 slot=97807
[2020-01-23 09:10:14]  INFO initial-sync: Processing block 97808/97851 - estimated time remaining 45s blocksPerSecond=0.9 peers=1/50
[2020-01-23 09:10:14]  INFO forkchoice: Executing state transition on block root=0xdc136c20... slot=97808
[2020-01-23 09:10:15]  INFO blockchain: Finished applying state transition attestations=33 deposits=0 slot=97808
[2020-01-23 09:10:15]  INFO initial-sync: Processing block 97809/97851 - estimated time remaining 46s blocksPerSecond=0.9 peers=1/50
[2020-01-23 09:10:15]  INFO forkchoice: Executing state transition on block root=0xea65265d... slot=97809
runtime: invalid pc-encoded table f=runtime.aeshash32 pc=0x491f03 targetpc=0x491f0b tab=[0/0]0x0
	value=0 until pc=0x491f03
fatal error: invalid runtime symbol table

goroutine 0 [idle]:
runtime: unexpected return pc for runtime.sigtramp called from 0x7fdbd1f20540
stack: frame={sp:0xc0004bb968, fp:0xc0004bb9c0} stack=[0xc0004b4000,0xc0004bc000)
000000c0004bb868:  0000000000000000  0000000000000000 
000000c0004bb878:  0000000000000000  0000000000000000 
000000c0004bb888:  0000000000000000  0000000000000000 
000000c0004bb898:  000000c0004bbaf0  000000c0004bb9c0 
000000c0004bb8a8:  000000c0004bb958  0000000000476f20 <runtime.sigtrampgo+496> 
000000c0004bb8b8:  000000c00000001b  000000c0004bbaf0 
000000c0004bb8c8:  000000c0004bb9c0  000000c00f894000 
000000c0004bb8d8:  0000000000000000  0000000000000000 
000000c0004bb8e8:  0000000000000000  0000000000000000 
000000c0004bb8f8:  0000000000000000  0000000000000000 
000000c0004bb908:  0000000000000000  000000c00f894000 
000000c0004bb918:  0000000000000000  0000000000000000 
000000c0004bb928:  0000000000000000  0000000000000000 
000000c0004bb938:  0000000000000000  0000000000000000 
000000c0004bb948:  0000000000000000  0000000000000000 
000000c0004bb958:  000000c0004bb9b0  0000000000493c63 <runtime.sigtramp+67> 
000000c0004bb968: <000000000000001b  000000c0004bbaf0 
000000c0004bb978:  000000c0004bb9c0  00000000dd3303be 
000000c0004bb988:  000000008f783145  00000000c18a2c7b 
000000c0004bb998:  00000000a2c7bc18  000000c0004bb9b0 
000000c0004bb9a8:  00000000466bab85  0000000001b855e0 
000000c0004bb9b8: !00007fdbd1f20540 >0000000000000007 
000000c0004bb9c8:  0000000000000000  000000c0004b4000 
000000c0004bb9d8:  0000000000000000  0000000000008000 
000000c0004bb9e8:  0000000074e9a8ac  00000000bd2a4ab9 
000000c0004bb9f8:  0000000065c34f29  000000000628b1ef 
000000c0004bba08:  00000000a2c7bc18  00000000c18a2c7b 
000000c0004bba18:  000000008f783145  00000000dd3303be 
000000c0004bba28:  000000009d7019d4  000000c00e5dcb00 
000000c0004bba38:  0000000001b855e0  00000000466bab85 
000000c0004bba48:  00000000eb299f01  000000009b58a83b 
000000c0004bba58:  00000000d373e783  000000c01e473840 
000000c0004bba68:  0000000000a77614 <github.com/minio/sha256-simd.blockAvx2+596>  0000000000000286 
000000c0004bba78:  002b000000000033  0000000000000000 
000000c0004bba88:  0000000000000000  0000000000000000 
000000c0004bba98:  0000000000000000  000000c0004bbb80 
000000c0004bbaa8:  0000000000000000  0000000000000000 
000000c0004bbab8:  0000000000000000 
runtime.throw(0x17da37d, 0x1c)
	GOROOT/src/runtime/panic.go:774 +0x72
runtime.pcvalue(0x1cbeef8, 0x2683840, 0x9d75a, 0x491f0b, 0xc0004bb3d0, 0x2586901, 0x448)
	GOROOT/src/runtime/symtab.go:723 +0x53d
runtime.funcspdelta(0x1cbeef8, 0x2683840, 0x491f0b, 0xc0004bb3d0, 0xc000000448)
	GOROOT/src/runtime/symtab.go:775 +0x5f
runtime.gentraceback(0xa77614, 0xc01e473840, 0x0, 0xc00f894000, 0x0, 0xc0004bb628, 0x40, 0x0, 0x0, 0x6, ...)
	GOROOT/src/runtime/traceback.go:220 +0x1598
runtime.sigprof(0xa77614, 0xc01e473840, 0x0, 0xc00f894000, 0xc0004ae000)
	GOROOT/src/runtime/proc.go:3760 +0x417
runtime.sighandler(0xc00000001b, 0xc0004bbaf0, 0xc0004bb9c0, 0xc00f894000)
	GOROOT/src/runtime/signal_sighandler.go:38 +0x706
runtime.sigtrampgo(0x1b, 0xc0004bbaf0, 0xc0004bb9c0)
	GOROOT/src/runtime/signal_unix.go:352 +0x1f0
runtime: unexpected return pc for runtime.sigtramp called from 0x7fdbd1f20540
stack: frame={sp:0xc0004bb968, fp:0xc0004bb9c0} stack=[0xc0004b4000,0xc0004bc000)
000000c0004bb868:  0000000000000000  0000000000000000 
000000c0004bb878:  0000000000000000  0000000000000000 
000000c0004bb888:  0000000000000000  0000000000000000 
000000c0004bb898:  000000c0004bbaf0  000000c0004bb9c0 
000000c0004bb8a8:  000000c0004bb958  0000000000476f20 <runtime.sigtrampgo+496> 
000000c0004bb8b8:  000000c00000001b  000000c0004bbaf0 
000000c0004bb8c8:  000000c0004bb9c0  000000c00f894000 
000000c0004bb8d8:  0000000000000000  0000000000000000 
000000c0004bb8e8:  0000000000000000  0000000000000000 
000000c0004bb8f8:  0000000000000000  0000000000000000 
000000c0004bb908:  0000000000000000  000000c00f894000 
000000c0004bb918:  0000000000000000  0000000000000000 
000000c0004bb928:  0000000000000000  0000000000000000 
000000c0004bb938:  0000000000000000  0000000000000000 
000000c0004bb948:  0000000000000000  0000000000000000 
000000c0004bb958:  000000c0004bb9b0  0000000000493c63 <runtime.sigtramp+67> 
000000c0004bb968: <000000000000001b  000000c0004bbaf0 
000000c0004bb978:  000000c0004bb9c0  00000000dd3303be 
000000c0004bb988:  000000008f783145  00000000c18a2c7b 
000000c0004bb998:  00000000a2c7bc18  000000c0004bb9b0 
000000c0004bb9a8:  00000000466bab85  0000000001b855e0 
000000c0004bb9b8: !00007fdbd1f20540 >0000000000000007 
000000c0004bb9c8:  0000000000000000  000000c0004b4000 
000000c0004bb9d8:  0000000000000000  0000000000008000 
000000c0004bb9e8:  0000000074e9a8ac  00000000bd2a4ab9 
000000c0004bb9f8:  0000000065c34f29  000000000628b1ef 
000000c0004bba08:  00000000a2c7bc18  00000000c18a2c7b 
000000c0004bba18:  000000008f783145  00000000dd3303be 
000000c0004bba28:  000000009d7019d4  000000c00e5dcb00 
000000c0004bba38:  0000000001b855e0  00000000466bab85 
000000c0004bba48:  00000000eb299f01  000000009b58a83b 
000000c0004bba58:  00000000d373e783  000000c01e473840 
000000c0004bba68:  0000000000a77614 <github.com/minio/sha256-simd.blockAvx2+596>  0000000000000286 
000000c0004bba78:  002b000000000033  0000000000000000 
000000c0004bba88:  0000000000000000  0000000000000000 
000000c0004bba98:  0000000000000000  000000c0004bbb80 
000000c0004bbaa8:  0000000000000000  0000000000000000 
000000c0004bbab8:  0000000000000000 
runtime.sigtramp(0x7, 0x0, 0xc0004b4000, 0x0, 0x8000, 0x74e9a8ac, 0xbd2a4ab9, 0x65c34f29, 0x628b1ef, 0xa2c7bc18, ...)
	GOROOT/src/runtime/sys_linux_amd64.s:357 +0x43

goroutine 294 [running]:
pchain.sh: line 1:  7168 Segmentation fault      (core dumped) ~/commands/binary/pchain --datadir=$HOME/prysmData --http-web3provider=http://localhost:8545 --web3provider=ws://localhost:8546 --min-sync-peers=10 --enable-upnp --peer /ip4/148.251.128.119/tcp/13000/p2p/16Uiu2HAmAsyW714qpiYz9dNEoDyLa29SuzXwU4sY3fQrRtUxN1bT --p2p-host-ip=$(curl -s v4.ident.me) --cache-proposer-indices --cache-filtered-block-tree --enable-ssz-cache --cpuprofile=$HOME/logs/cpu0118 --p2p-max-peers=50

**Comment by prestonvanloon** [comment]
I haven't seen this in some time. Closing for inactivity. Please re-open if this is still a valid issue.

Thanks
