### ISSUE TITLE
beacon-chain fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by mondsen** [prysmaticlabs/prysm#4829]
I am running on a 2x vCPU (VPS) with 4 GB RAM in Docker. My node crashed after roughly 17h with the fatal error: concurrent map iteration and map write. 

Full log for my node (see line 252409)
[log.zip](https://github.com/prysmaticlabs/prysm/files/4184722/log.zip)

**Comment by prestonvanloon** [comment]
Relevant logs:
```
fatal error: concurrent map iteration and map write

goroutine 212 [running]:
runtime.throw(0x1836c14, 0x26)
        GOROOT/src/runtime/panic.go:774 +0x72 fp=0xc011fc96e0 sp=0xc011fc96b0 pc=0x461f62
runtime.mapiternext(0xc011fc9a08)
        GOROOT/src/runtime/map.go:858 +0x579 fp=0xc011fc9768 sp=0xc011fc96e0 pc=0x441bb9
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).processPendingAtts(0xc0000d7100, 0x1baef00, 0xc02fb591d0, 0x0, 0x0)
        beacon-chain/sync/pending_attestations_queue.go:46 +0xa38 fp=0xc011fc9eb8 sp=0xc011fc9768 pc=0x11f8d08
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).processPendingAttsQueue.func1()
        beacon-chain/sync/pending_attestations_queue.go:27 +0x3c fp=0xc011fc9ef0 sp=0xc011fc9eb8 pc=0x120883c
github.com/prysmaticlabs/prysm/shared/runutil.RunEvery.func1(0xc00cd7a370, 0x25d5a88, 0x59, 0xc003f361c0, 0x1baee40, 0xc00cd52c80)
        shared/runutil/every.go:22 +0xec fp=0xc011fc9fb0 sp=0xc011fc9ef0 pc=0xfff69c
runtime.goexit()
        GOROOT/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc011fc9fb8 sp=0xc011fc9fb0 pc=0x492561
created by github.com/prysmaticlabs/prysm/shared/runutil.RunEvery
        shared/runutil/every.go:17 +0x136
```

This will be fixed in #4833

**Comment by prestonvanloon** [comment]
This is still happening in commit 0882908d2c9587d6a88a9d3cd45b7f0448b8329a.

```
goroutine 117869 [running]:
runtime.throw(0x1830f7f, 0x21)
        GOROOT/src/runtime/panic.go:774 +0x72 fp=0xc013d757a8 sp=0xc013d75778 pc=0x461f62
runtime.mapaccess1(0x15b3f20, 0xc000653c20, 0xc013d758f0, 0xc00000ca68)
        GOROOT/src/runtime/map.go:411 +0x269 fp=0xc013d757f0 sp=0xc013d757a8 pc=0x440489
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).savePendingAtt(...)
        beacon-chain/sync/pending_attestations_queue.go:137
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).validateAggregatedAtt(0xc000460c00, 0x1bb3500, 0xc01ae3ef00, 0xc01abd5680, 0x0)
        beacon-chain/sync/validate_aggregate_proof.go:85 +0x2ed fp=0xc013d759f8 sp=0xc013d757f0 pc=0x12077dd
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).validateAggregateAndProof(0xc000460c00, 0x1bb3500, 0xc01ae3edb0, 0xc00ca5f140, 0x27, 0xc01f00fe60, 0x0)
        beacon-chain/sync/validate_aggregate_proof.go:63 +0x3e6 fp=0xc013d75c50 sp=0xc013d759f8 pc=0x12072a6
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).validateAggregateAndProof-fm(0x1bb34c0, 0xc01b2aad20, 0xc00ca5f140, 0x27, 0xc01f00fe60, 0xc00c2e2040)
        beacon-chain/sync/validate_aggregate_proof.go:28 +0x5c fp=0xc013d75c98 sp=0xc013d75c50 pc=0x12101dc
github.com/prysmaticlabs/prysm/beacon-chain/sync.wrapAndReportValidation.func1(0x1bb34c0, 0xc01b2aad20, 0xc00ca5f140, 0x27, 0xc01f00fe60, 0xc013be6a00)
        beacon-chain/sync/subscriber.go:184 +0x1c0 fp=0xc013d75d48 sp=0xc013d75c98 pc=0x120ed80
github.com/libp2p/go-libp2p-pubsub.(*topicVal).validateMsg(0xc000653fb0, 0x1bb3440, 0xc00004afc0, 0xc00ca5f140, 0x27, 0xc01f00fe60, 0xc01ae34600)
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:335 +0x8a fp=0xc013d75dd0 sp=0xc013d75d48 pc=0xfc2e4a
```

**Comment by KuDeTa** [comment]
[PrsymaticFanboyDebugLog.txt](https://github.com/prysmaticlabs/prysm/files/4208602/PrsymaticFanboyDebugLog.txt)


Image | gcr.io/prysmaticlabs/prysm/beacon-chain:latest@sha256:20046246d79d74bcb07db54390a3feb477d2a365472797831d6857322f8f52ba
-- | --
CMD | --datadir=/data  --p2p-host-ip=5.42.129.6 --web3provider=ws://goerli-node:9546/  --http-web3provider=http://goerli-node:9545/ --p2p-max-peers 120  --deposit-contract=0x4689a3C63CE249355C8a573B5974db21D2d1b8Ef

**Comment by prestonvanloon** [comment]
I think that is an old image @KuDeTa. Can you update to a more recent image? I believe this has been resolved.
