### ISSUE TITLE
Initial sync not possible due to "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by mangoleap** [prysmaticlabs/prysm#4843]
```
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]: time="2020-02-12 15:34:24" level=error msg="gRPC panicked!" error="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 39477 [running]: 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]: runtime/debug.Stack(0x40000e8690, 0x14fba7e, 0x5) 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]:         GOROOT/src/runtime/debug/stack.go:24 +0x88 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]: github.com/prysmaticlabs/prysm/shared/traceutil.RecoveryHandlerFunc(0x18c20c0, 0x40008f3ad0, 0x12e2120, 0x2361dd0, 0x4002ec7348, 0xbfa264) 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]:         shared/traceutil/recovery_interceptor_option.go:29 +0x110 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]: github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom(0x18c20c0, 0x40008f3ad0, 0x12e2120, 0x2361dd0, 0x16c0788, 0x0, 0x0) 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]:         external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:52 +0x50 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]: github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1(0x18c20c0, 0x40008f3ad0, 0x4000010170, 0x4002ec7928) 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]:         external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:26 +0x68 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]: panic(0x12e2120, 0x2361dd0) 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]:         GOROOT/src/runtime/panic.go:679 +0x194 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]: github.com/prysmaticlabs/prysm/beacon-chain/state.(*BeaconState).Slot(...) 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]:         beacon-chain/state/getters.go:114 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]: github.com/prysmaticlabs/prysm/beacon-chain/rpc/beacon.(*Server).GetValidatorPerformance(0x4001294000, 0x18c20c0, 0x40008f3b90, 0x4004207ec0, 0x4001294000, 0x422d80, 0x0) 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]:         beacon-chain/rpc/beacon/validators.go:590 +0x58 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]: github.com/prysmaticlabs/ethereumapis/eth/v1alpha1._BeaconChain_GetValidatorPerformance_Handler.func1(0x18c20c0, 0x40008f3b90, 0x1473c20, 0x4004207ec0, 0x1550549, 0x3a, 0x18c20c0, 0x40008f3b90) 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]:         bazel-out/aarch64-fastbuild/bin/external/com_github_prysmaticlabs_ethereumapis/eth/v1alpha1/linux_arm64_stripped/go_proto%/github.com/prysmaticlabs/ethereumapis/eth/v1alpha1/beacon_chain.pb.go:3364 +0x7c 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]: github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1(0x18c20c0, 0x40008f3ad0, 0x1473c20, 0x4004207ec0, 0x40088426e0, 0x4008842700, 0x3, 0x3, 0x18cdee0, 0x40035e0180) 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]:         external/com_github_grpc_ecosystem_go_grpc_middleware/tracing/opentracing/server_interceptors.go:31 +0xfc 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]: github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x18c20c0, 0x40008f3ad0, 0x1473c20, 0x4004207ec0, 0x3a, 0x40048a1400, 0x7f80219798, 0x8) 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]:         external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x58 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]: github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x18c20c0, 0x40008f3ad0, 0x1473c20, 0x4004207ec0, 0x40088426e0, 0x4008842760, 0x4003d28838, 0x100e874, 0x4008842820, 0x20) 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]:         external/com_github_grpc_ecosystem_go_grpc_prometheus/server_metrics.go:107 +0x8c 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]: github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x18c20c0, 0x40008f3ad0, 0x1473c20, 0x4004207ec0, 0x18c2000, 0x20, 0x20, 0x4008842820) 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]:         external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x58 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]: github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1(0x18c20c0, 0x40008f3ad0, 0x1473c20, 0x4004207ec0, 0x40088426e0, 0x40088427c0, 0x0, 0x0, 0x0, 0x0) 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]:         external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:30 +0x98 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]: github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x18c20c0, 0x40008f3ad0, 0x1473c20, 0x4004207ec0, 0x4001172120, 0x4000daaf00, 0x4003d289a8, 0x94a91c) 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]:         external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x58 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]: github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x18c20c0, 0x40008f3ad0, 0x1473c20, 0x4004207ec0, 0x40088426e0, 0x4008842700, 0x13e7f80, 0x40008f3ad0, 0x50, 0x1417900) 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]:         external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:34 +0xbc 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]: github.com/prysmaticlabs/ethereumapis/eth/v1alpha1._BeaconChain_GetValidatorPerformance_Handler(0x1496de0, 0x4001294000, 0x18c20c0, 0x40008f3ad0, 0x40048a13b0, 0x40012761b0, 0x18c20c0, 0x40008f3ad0, 0x40014581c0, 0x36) 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]:         bazel-out/aarch64-fastbuild/bin/external/com_github_prysmaticlabs_ethereumapis/eth/v1alpha1/linux_arm64_stripped/go_proto%/github.com/prysmaticlabs/ethereumapis/eth/v1alpha1/beacon_chain.pb.go:3366 +0x128 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]: google.golang.org/grpc.(*Server).processUnaryRPC(0x40005e2c00, 0x18d5ec0, 0x4001306900, 0x4000daaf00, 0x4001276600, 0x2375450, 0x0, 0x0, 0x0) 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]:         external/org_golang_google_grpc/server.go:998 +0x38c 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]: google.golang.org/grpc.(*Server).handleStream(0x40005e2c00, 0x18d5ec0, 0x4001306900, 0x4000daaf00, 0x0) 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]:         external/org_golang_google_grpc/server.go:1278 +0xb0c 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]: google.golang.org/grpc.(*Server).serveStreams.func1.1(0x4001158080, 0x40005e2c00, 0x18d5ec0, 0x4001306900, 0x4000daaf00) 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]:         external/org_golang_google_grpc/server.go:717 +0x94 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]: created by google.golang.org/grpc.(*Server).serveStreams.func1 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]:         external/org_golang_google_grpc/server.go:715 +0x8c 
Feb 12 15:34:24 ethnode-9538ecf1 beacon-chain[1695]: " 

```

**Comment by prestonvanloon** [comment]
Hi @mangoleap, which version or commit of Prysm did this error occur?

**Comment by rauljordan** [comment]
Hi @mangoleap just a follow-up on this - are you still seeing this issue? Is it still reproducible if you try to sync?
