### ISSUE TITLE
gRPC panicked! runtime error: index out of range with length 0

### ISSUE THREAD

**Issue by guybrush** [prysmaticlabs/prysm#4986]
I got this with a07e604e

```
level=error msg="gRPC panicked!" error="runtime error: index out of range [28812] with length 0" stack="goroutine 12853 [running]:
runtime/debug.Stack(0xc0000e8690, 0x1815065, 0x5)
	GOROOT/src/runtime/debug/stack.go:24 +0x9d
github.com/prysmaticlabs/prysm/shared/traceutil.RecoveryHandlerFunc(0x1bc9dc0, 0xc02a61c810, 0x1714b00, 0xc023728040, 0x3, 0xc00001f2e0)
	shared/traceutil/recovery_interceptor_option.go:29 +0x155
github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom(0x1bc9dc0, 0xc02a61c810, 0x1714b00, 0xc023728040, 0x19daab8, 0x43e8b6, 0xc00001f368)
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:52 +0x5a
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1(0x1bc9dc0, 0xc02a61c810, 0xc0000d22e0, 0xc00001f968)
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:26 +0x77
panic(0x1714b00, 0xc023728040)
	GOROOT/src/runtime/panic.go:679 +0x1b2
github.com/prysmaticlabs/prysm/beacon-chain/rpc/beacon.(*Server).GetValidatorPerformance(0xc017c7a0f0, 0x1bc9dc0, 0xc02a61ca80, 0xc0226bb480, 0xc017c7a0f0, 0x0, 0x0)
	beacon-chain/rpc/beacon/validators.go:610 +0x1374
github.com/prysmaticlabs/ethereumapis/eth/v1alpha1._BeaconChain_GetValidatorPerformance_Handler.func1(0x1bc9dc0, 0xc02a61ca80, 0x177ee20, 0xc0226bb480, 0x186a1ac, 0x3a, 0x1bc9dc0, 0xc02a61ca80)
	bazel-out/k8-fastbuild/bin/external/com_github_prysmaticlabs_ethereumapis/eth/v1alpha1/linux_amd64_stripped/go_proto%/github.com/prysmaticlabs/ethereumapis/eth/v1alpha1/beacon_chain.pb.go:3752 +0x86
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1(0x1bc9dc0, 0xc02a61c810, 0x177ee20, 0xc0226bb480, 0xc01cb1c200, 0xc01cb1c220, 0x3, 0x3, 0x1bd5fa0, 0xc0226bb580)
	external/com_github_grpc_ecosystem_go_grpc_middleware/tracing/opentracing/server_interceptors.go:31 +0x165
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x1bc9dc0, 0xc02a61c810, 0x177ee20, 0xc0226bb480, 0x3a, 0xc017c2c780, 0x12, 0x1)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x1bc9dc0, 0xc02a61c810, 0x177ee20, 0xc0226bb480, 0xc01cb1c200, 0xc01cb1c240, 0xc022986370, 0x460d0a, 0xc022986370, 0xc017a508a8)
	external/com_github_grpc_ecosystem_go_grpc_prometheus/server_metrics.go:107 +0xad
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x1bc9dc0, 0xc02a61c810, 0x177ee20, 0xc0226bb480, 0x16cc460, 0x1268fef, 0x1bc9dc0, 0x20)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1(0x1bc9dc0, 0xc02a61c810, 0x177ee20, 0xc0226bb480, 0xc01cb1c200, 0xc01cb1c260, 0x0, 0x0, 0x0, 0x0)
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:30 +0xe2
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x1bc9dc0, 0xc02a61c810, 0x177ee20, 0xc0226bb480, 0xc00f2ba120, 0xc00046e700, 0xc017a509e8, 0x43f128)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x1bc9dc0, 0xc02a61c810, 0x177ee20, 0xc0226bb480, 0xc01cb1c200, 0xc01cb1c220, 0xc017a50a58, 0x5335d8, 0x16ff5c0, 0xc02a61c810)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:34 +0xd5
github.com/prysmaticlabs/ethereumapis/eth/v1alpha1._BeaconChain_GetValidatorPerformance_Handler(0x17d9820, 0xc017c7a0f0, 0x1bc9dc0, 0xc02a61c810, 0xc0268e3db0, 0xc00f2aa330, 0x1bc9dc0, 0xc02a61c810, 0xc00b370140, 0x32)
	bazel-out/k8-fastbuild/bin/external/com_github_prysmaticlabs_ethereumapis/eth/v1alpha1/linux_amd64_stripped/go_proto%/github.com/prysmaticlabs/ethereumapis/eth/v1alpha1/beacon_chain.pb.go:3754 +0x14b
google.golang.org/grpc.(*Server).processUnaryRPC(0xc017b6c600, 0x1bde2e0, 0xc014c48180, 0xc00046e700, 0xc00f2aa780, 0x26f6d28, 0x0, 0x0, 0x0)
	external/org_golang_google_grpc/server.go:998 +0x46a
google.golang.org/grpc.(*Server).handleStream(0xc017b6c600, 0x1bde2e0, 0xc014c48180, 0xc00046e700, 0x0)
	external/org_golang_google_grpc/server.go:1278 +0xd97
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc01fa0ce40, 0xc017b6c600, 0x1bde2e0, 0xc014c48180, 0xc00046e700)
	external/org_golang_google_grpc/server.go:717 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	external/org_golang_google_grpc/server.go:715 +0xa1
"
```

**Comment by guybrush** [comment]
relevant: #4990

**Comment by prestonvanloon** [comment]
Are you also running eth2stats client?
Did this error occur while syncing?

**Comment by handelaar2** [comment]
In my case (I had the same issue ( #4990 ) which I closed to avoid double issue-recording):
eth2stats: **yes**
Did this error occur while syncing: **direct at startup of beacon** (see beacon.log in #4990)
