### ISSUE TITLE
panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#5105]
```
Executing tests from //beacon-chain/core/blocks/fuzz:block_header_fuzz_with_libfuzzer
-----------------------------------------------------------------------------
INFO: Seed: 1043437889
INFO: Loaded 1 modules   (61969 inline 8-bit counters): 61969 [0x1bb9020, 0x1bc8231),
INFO: Loaded 1 PC tables (61969 PCs): 61969 [0x1bc8238,0x1cba348),
INFO: 3 Extra Counters
INFO:      104 files found in external/sigp_beacon_fuzz_corpora/0-9-4/mainnet/block_header
INFO: seed corpus: files: 104 min: 302b max: 302b total: 31408b rss: 51Mb
#64     pulse  ft: 4 corp: 1/302b exec/s: 32 rss: 84Mb
#106    INITED ft: 4 corp: 1/302b exec/s: 35 rss: 85Mb
#128    pulse  ft: 4 corp: 1/302b lim: 302 exec/s: 42 rss: 86Mb
panic: runtime error: integer divide by zero

goroutine 17 [running, locked to thread]:
github.com/prysmaticlabs/prysm/beacon-chain/core/epoch/precompute.attestationDelta(0x10c00040e050, 0x10c00085a3c0, 0x10c000410e40, 0x0, 0x0)
        beacon-chain/core/epoch/precompute/reward_penalty.go:81 +0x2b7
github.com/prysmaticlabs/prysm/beacon-chain/core/epoch/precompute.attestationDeltas(0x10c00040e050, 0x10c00085a3c0, 0x10c0013f5000, 0x100, 0x100, 0x303000000000000, 0x14c9, 0x0, 0x0, 0x14ca, ...)
        beacon-chain/core/epoch/precompute/reward_penalty.go:68 +0xdc
github.com/prysmaticlabs/prysm/beacon-chain/core/epoch/precompute.ProcessRewardsAndPenaltiesPrecompute(0x10c00040e050, 0x10c00085a3c0, 0x10c0013f5000, 0x100, 0x100, 0x100, 0x10c00085a3c0, 0x10c0013f5000)
        beacon-chain/core/epoch/precompute/reward_penalty.go:30 +0x185
github.com/prysmaticlabs/prysm/beacon-chain/core/state.ProcessEpochPrecompute(0x14f7500, 0x10c00046e3c0, 0x10c00040e050, 0x0, 0x0, 0x0)
        beacon-chain/core/state/transition.go:621 +0x2d1
github.com/prysmaticlabs/prysm/beacon-chain/core/state.ProcessSlots(0x14f7500, 0x10c000601dd0, 0x10c00040e050, 0x200000000000002, 0x0, 0x0, 0x0)
        beacon-chain/core/state/transition.go:315 +0x48b
github.com/prysmaticlabs/prysm/beacon-chain/core/blocks/fuzz.Fuzz(0x10c001580000, 0x2982b1, 0x2984b1, 0x10c000120140, 0x0, 0x10c0000ae058, 0x10c000078e90)
        beacon-chain/core/blocks/fuzz/fuzz.go:58 +0x435
main.LLVMFuzzerTestOneInput(...)
        generated_main.fuzz.go:15
main._cgoexpwrap_e9a935528231_LLVMFuzzerTestOneInput(0x6120000439c0, 0x12e, 0x612000000dc0)
        _cgo_gotypes.go:65 +0xc2
==14== ERROR: libFuzzer: deadly signal
    #0 0x594a51  (/home/preston/.cache/bazel/_bazel_preston/6e220e5720b8243fd605645eb29a29ba/execroot/prysm/bazel-out/k8-fastbuild/bin/beacon-chain/core/blocks/fuzz/block_header_fuzz_with_libfuzzer+0x594a51)
    #1 0x4df808  (/home/preston/.cache/bazel/_bazel_preston/6e220e5720b8243fd605645eb29a29ba/execroot/prysm/bazel-out/k8-fastbuild/bin/beacon-chain/core/blocks/fuzz/block_header_fuzz_with_libfuzzer+0x4df808)
    #2 0x4c4f73  (/home/preston/.cache/bazel/_bazel_preston/6e220e5720b8243fd605645eb29a29ba/execroot/prysm/bazel-out/k8-fastbuild/bin/beacon-chain/core/blocks/fuzz/block_header_fuzz_with_libfuzzer+0x4c4f73)
    #3 0x7fd127d7888f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1288f)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 4 ChangeASCIIInt-CopyPart-ShuffleBytes-ChangeBit-; base unit: 90dbf23cfad6a9ace0714349402f03b89ddb665b
artifact_prefix='./'; Test unit written to ./crash-4c20a23203c786fab4f30a51b7417d960a2d3134
stat::number_of_executed_units: 195
stat::average_exec_per_sec:     0
stat::new_units_added:          0
stat::slowest_unit_time_sec:    0
stat::peak_rss_mb:              88
```

**Comment by prestonvanloon** [comment]
The issue was here when `bp.CurrentEpoch` was zero.

https://github.com/prysmaticlabs/prysm/blob/de2ec8e575a8b9c9d6a188393e6778fa636670f4/beacon-chain/core/epoch/precompute/reward_penalty.go#L81
