### ISSUE TITLE
Proposer slashing: panic during panic

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#5131]
Capturing this bug from fuzzit. I think this is the relevant stack, but needs investigation.
```
FUZZER: goroutine 17 [runnable, locked to thread]:
FUZZER: github.com/prysmaticlabs/prysm/proto/beacon/p2p/v1.(*BeaconState).UnmarshalSSZ(0x10c0003c1b00, 0x10c00204e000, 0x298269, 0x532000, 0x5304d2, 0x532000)
FUZZER: 	bazel-out/k8-fastbuild/bin/proto/beacon/p2p/v1/generated.ssz.go:262 +0x687
FUZZER: github.com/prysmaticlabs/prysm/beacon-chain/testing.GetBeaconFuzzState(0x10c00008000a, 0x10c0000c4680)
FUZZER: 	beacon-chain/testing/beacon_fuzz_states.go:19 +0x13d
FUZZER: github.com/prysmaticlabs/prysm/beacon-chain/core/blocks/fuzz.BeaconFuzzProposerSlashing(0x10c0000c4680, 0x19a, 0x19a, 0x10c0000c4680, 0x0, 0x10c00007e058, 0x10c000083e90)
FUZZER: 	beacon-chain/core/blocks/fuzz/proposer_slashing_fuzz.go:23 +0x1ef
FUZZER: main.LLVMFuzzerTestOneInput(...)
FUZZER: 	proposer_slashing_fuzz_test_libfuzz_main_main.fuzz.go:15
FUZZER: main._cgoexpwrap_ee17a5a4f456_LLVMFuzzerTestOneInput(0x6140020c6a40, 0x19a, 0x621000010500)
FUZZER: 	_cgo_gotypes.go:65 +0xc2
```

[orgs_prysmaticlabs-gh_targets_proposer-slashing_jobs_K5N4nOIRcwrdcWhHn4f2_log.txt](https://github.com/prysmaticlabs/prysm/files/4350601/orgs_prysmaticlabs-gh_targets_proposer-slashing_jobs_K5N4nOIRcwrdcWhHn4f2_log.txt)

[crash.tar.gz](https://github.com/prysmaticlabs/prysm/files/4350606/crash.tar.gz)

https://app.fuzzit.dev/orgs/prysmaticlabs-gh/targets/proposer-slashing/K5N4nOIRcwrdcWhHn4f2

Commit 48e2e290dd30b09f21790eb92d8ff2fea3870099

**Comment by prestonvanloon** [comment]
This seems to be the relevant generated code
```go
        // Field (5) 'StateRoots'
        b.StateRoots = make([][]byte, 8192)
        for ii := 0; ii < 8192; ii++ {
                b.StateRoots[ii] = append(b.StateRoots[ii], buf[262280:524424][ii*32:(ii+1)*32]...) // line 262
        }
```

**Comment by prestonvanloon** [comment]
Looking at the logs a bit deeper, I think the relevant error is actually.
```
FUZZER: fatal error: unknown caller pc
FUZZER: 
FUZZER: runtime stack:
FUZZER: runtime.throw(0x2b3da2, 0x11)
FUZZER: 	GOROOT/src/runtime/panic.go:1112 +0x74
FUZZER: runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0x10c000001980, 0x0, 0x0, 0x7fffffff, 0x7f8a558f2b28, 0x0, 0x0, ...)
FUZZER: 	GOROOT/src/runtime/traceback.go:273 +0x19ff
FUZZER: runtime.scanstack(0x10c000001980, 0x10c00004ae98)
FUZZER: 	GOROOT/src/runtime/mgcmark.go:739 +0x162
FUZZER: runtime.markroot.func1()
FUZZER: 	GOROOT/src/runtime/mgcmark.go:226 +0xc3
FUZZER: runtime.markroot(0x10c00004ae98, 0xe)
FUZZER: 	GOROOT/src/runtime/mgcmark.go:199 +0x2f5
FUZZER: runtime.gcDrain(0x10c00004ae98, 0x7)
FUZZER: 	GOROOT/src/runtime/mgcmark.go:999 +0x10b
FUZZER: runtime.gcBgMarkWorker.func2()
FUZZER: 	GOROOT/src/runtime/mgc.go:1955 +0x16b
FUZZER: runtime.systemstack(0x7f8a59b63a20)
FUZZER: 	src/runtime/asm_amd64.s:370 +0x63
FUZZER: runtime.mstart()
FUZZER: 	GOROOT/src/runtime/proc.go:1041
```

Relevant: https://github.com/golang/go/issues/35158

**Comment by prestonvanloon** [comment]
I think this was resolved in go 1.14.1 

https://github.com/golang/go/issues/37782

Closing this for now and will reopen if fuzzer picks it up again.

**Comment by prestonvanloon** [comment]
This is still happening with go 1.14.1. https://app.fuzzit.dev/orgs/prysmaticlabs-gh/targets/proposer-slashing/HVZlMFw1gYncqUJeblqh

**Comment by rauljordan** [comment]
Was this resolved @prestonvanloon ?

**Comment by prestonvanloon** [comment]
I don't think so. I'm picking up fuzzing work again today and we'll see if it continues to fail.

**Comment by rauljordan** [comment]
Update on this @prestonvanloon ?

**Comment by prestonvanloon** [comment]
It still happens. golang/go#35158 is still open.

**Comment by nisdas** [comment]
@prestonvanloon Do you think we can remove it ? As we no longer use libfuzzer now.

**Comment by prestonvanloon** [comment]
@nisdas yeah, this is probably not an issue now that we aren't using libfuzzer symbols
