### ISSUE TITLE
binary fails inside docker container at start up on centos 8

### ISSUE THREAD

**Issue by xrow** [prysmaticlabs/prysm#5134]
Hi,

I try to run the binary distribution inside docker and it fails. If I run it outside docker it all works fine.

Here is how to reproduce on centos 8:

```
FROM centos:8

ENV VERSION=0.3.4
ENV HOME="/data"
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin

RUN curl -L -o /usr/bin/beacon-chain https://github.com/prysmaticlabs/prysm/releases/download/v$VERSION/beacon-chain-v$VERSION-linux-amd64 && \
	chmod 755 /usr/bin/beacon-chain && \
    chmod 755 /usr/bin/uid_entrypoint && \
    mkdir /data && chmod 777 /data && \
    chmod g=u /etc/passwd

VOLUME /data

WORKDIR /data

EXPOSE 4000/tcp
EXPOSE 13000/tcp

CMD /usr/bin/beacon-chain \
    --init-sync-no-verify \
	--p2p-port=4000 \
	--grpc-gateway-port=13000 \
    --datadir=/data
```

The output is when running `docker run -it --user 0 localhost/test:latest`

```
[root@False beacon]# docker run -it --user 0 localhost/test:latest 
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
terminate called after throwing an instance of 'Xbyak::Error'
  what():  can't protect
SIGABRT: abort
PC=0x7f3ba56d793f m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x12c6b80, 0xc0000b5d90, 0xa6ed73)
        GOROOT/src/runtime/cgocall.go:128 +0x5b fp=0xc0000b5d60 sp=0xc0000b5d28 pc=0x42334b
github.com/herumi/bls-eth-go-binary/bls._Cfunc_blsInit(0xf600000005, 0xc000000000)
        _cgo_gotypes.go:347 +0x4d fp=0xc0000b5d90 sp=0xc0000b5d60 pc=0xac844d
github.com/herumi/bls-eth-go-binary/bls.Init(0x5, 0x0, 0x0)
        bls.go:39 +0x36 fp=0xc0000b5de8 sp=0xc0000b5d90 pc=0xaca746
github.com/prysmaticlabs/prysm/shared/bls.init.0()
        shared/bls/bls.go:20 +0x2a fp=0xc0000b5e10 sp=0xc0000b5de8 pc=0xacf4da
runtime.doInit(0x25d97c0)
        GOROOT/src/runtime/proc.go:5222 +0x8a fp=0xc0000b5e40 sp=0xc0000b5e10 pc=0x45dbda
runtime.doInit(0x25de4c0)
        GOROOT/src/runtime/proc.go:5217 +0x57 fp=0xc0000b5e70 sp=0xc0000b5e40 pc=0x45dba7
runtime.doInit(0x25da3c0)
        GOROOT/src/runtime/proc.go:5217 +0x57 fp=0xc0000b5ea0 sp=0xc0000b5e70 pc=0x45dba7
runtime.doInit(0x25e9340)
        GOROOT/src/runtime/proc.go:5217 +0x57 fp=0xc0000b5ed0 sp=0xc0000b5ea0 pc=0x45dba7
runtime.doInit(0x25dbd60)
        GOROOT/src/runtime/proc.go:5217 +0x57 fp=0xc0000b5f00 sp=0xc0000b5ed0 pc=0x45dba7
runtime.doInit(0x25e9040)
        GOROOT/src/runtime/proc.go:5217 +0x57 fp=0xc0000b5f30 sp=0xc0000b5f00 pc=0x45dba7
runtime.doInit(0x25e1500)
        GOROOT/src/runtime/proc.go:5217 +0x57 fp=0xc0000b5f60 sp=0xc0000b5f30 pc=0x45dba7
runtime.main()
        GOROOT/src/runtime/proc.go:190 +0x1da fp=0xc0000b5fe0 sp=0xc0000b5f60 pc=0x4516da
runtime.goexit()
        GOROOT/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000b5fe8 sp=0xc0000b5fe0 pc=0x480201

goroutine 6 [select]:
github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc00008e720)
        external/com_github_ipfs_go_log/writer/writer.go:76 +0x144
created by github.com/ipfs/go-log/writer.NewMirrorWriter
        external/com_github_ipfs_go_log/writer/writer.go:41 +0xb9

goroutine 7 [syscall]:
os/signal.signal_recv(0x0)
        GOROOT/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        GOROOT/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        GOROOT/src/os/signal/signal_unix.go:29 +0x41

goroutine 8 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc00010cd20)
        external/com_github_dgraph_io_ristretto/policy.go:96 +0xbe
created by github.com/dgraph-io/ristretto.newDefaultPolicy
        external/com_github_dgraph_io_ristretto/policy.go:80 +0x129

goroutine 9 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc00007ab40)
        external/com_github_dgraph_io_ristretto/cache.go:257 +0xc8
created by github.com/dgraph-io/ristretto.NewCache
        external/com_github_dgraph_io_ristretto/cache.go:155 +0x1f3

goroutine 10 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc00018ddd0)
        external/com_github_dgraph_io_ristretto/policy.go:96 +0xbe
created by github.com/dgraph-io/ristretto.newDefaultPolicy
        external/com_github_dgraph_io_ristretto/policy.go:80 +0x129

goroutine 11 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc00007ac60)
        external/com_github_dgraph_io_ristretto/cache.go:257 +0xc8
created by github.com/dgraph-io/ristretto.NewCache
        external/com_github_dgraph_io_ristretto/cache.go:155 +0x1f3

goroutine 12 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc000232ea0)
        external/com_github_dgraph_io_ristretto/policy.go:96 +0xbe
created by github.com/dgraph-io/ristretto.newDefaultPolicy
        external/com_github_dgraph_io_ristretto/policy.go:80 +0x129

goroutine 13 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc00007ad80)
        external/com_github_dgraph_io_ristretto/cache.go:257 +0xc8
created by github.com/dgraph-io/ristretto.NewCache
        external/com_github_dgraph_io_ristretto/cache.go:155 +0x1f3

goroutine 14 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc0003200c0)
        external/com_github_dgraph_io_ristretto/policy.go:96 +0xbe
created by github.com/dgraph-io/ristretto.newDefaultPolicy
        external/com_github_dgraph_io_ristretto/policy.go:80 +0x129

goroutine 15 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc00007af60)
        external/com_github_dgraph_io_ristretto/cache.go:257 +0xc8
created by github.com/dgraph-io/ristretto.NewCache
        external/com_github_dgraph_io_ristretto/cache.go:155 +0x1f3

goroutine 16 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc000387170)
        external/com_github_dgraph_io_ristretto/policy.go:96 +0xbe
created by github.com/dgraph-io/ristretto.newDefaultPolicy
        external/com_github_dgraph_io_ristretto/policy.go:80 +0x129

goroutine 19 [runnable]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc00007b7a0)
        external/com_github_dgraph_io_ristretto/cache.go:255
created by github.com/dgraph-io/ristretto.NewCache
        external/com_github_dgraph_io_ristretto/cache.go:155 +0x1f3

rax    0x0
rbx    0x6
rcx    0x7f3ba56d793f
rdx    0x0
rdi    0x2
rsi    0x7ffca7116100
rbp    0x7f3ba5a5f860
rsp    0x7ffca7116100
r8     0x0
r9     0x7ffca7116100
r10    0x8
r11    0x246
r12    0x414f8e0
r13    0x2749790
r14    0x4146000
r15    0x9000
rip    0x7f3ba56d793f
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by xrow** [comment]
Hi, found out it is way simpler to reproduce under centos 8. 

```
[root@False beacon]# docker run -it -v $HOME/prysm:/data -p 4000:4000 -p 13000:13000 --name beacon-node   gcr.io/prysmaticlabs/prysm/beacon-chain:latest   --datadir=/data
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
terminate called after throwing an instance of 'Xbyak::Error'
  what():  can't protect
SIGABRT: abort
PC=0x7fc868a7efff m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x129ee60, 0xc000127db8, 0xa69b53)
        GOROOT/src/runtime/cgocall.go:133 +0x5b fp=0xc000127d88 sp=0xc000127d50 pc=0x4234ab
github.com/herumi/bls-eth-go-binary/bls._Cfunc_blsInit(0xf600000005, 0xc000000000)
        _cgo_gotypes.go:407 +0x4d fp=0xc000127db8 sp=0xc000127d88 pc=0xae051d
github.com/herumi/bls-eth-go-binary/bls.Init(0x5, 0x0, 0x0)
        bls.go:39 +0x36 fp=0xc000127e10 sp=0xc000127db8 pc=0xae2806
github.com/prysmaticlabs/prysm/shared/bls.init.0()
        shared/bls/bls.go:20 +0x2a fp=0xc000127e38 sp=0xc000127e10 pc=0xae6e0a
runtime.doInit(0x2585860)
        GOROOT/src/runtime/proc.go:5414 +0x8a fp=0xc000127e68 sp=0xc000127e38 pc=0x463f3a
runtime.doInit(0x258a240)
        GOROOT/src/runtime/proc.go:5409 +0x57 fp=0xc000127e98 sp=0xc000127e68 pc=0x463f07
runtime.doInit(0x2586460)
        GOROOT/src/runtime/proc.go:5409 +0x57 fp=0xc000127ec8 sp=0xc000127e98 pc=0x463f07
runtime.doInit(0x2595460)
        GOROOT/src/runtime/proc.go:5409 +0x57 fp=0xc000127ef8 sp=0xc000127ec8 pc=0x463f07
runtime.doInit(0x2587e00)
        GOROOT/src/runtime/proc.go:5409 +0x57 fp=0xc000127f28 sp=0xc000127ef8 pc=0x463f07
runtime.doInit(0x25958e0)
        GOROOT/src/runtime/proc.go:5409 +0x57 fp=0xc000127f58 sp=0xc000127f28 pc=0x463f07
runtime.doInit(0x258d6c0)
        GOROOT/src/runtime/proc.go:5409 +0x57 fp=0xc000127f88 sp=0xc000127f58 pc=0x463f07
runtime.main()
        GOROOT/src/runtime/proc.go:190 +0x1ce fp=0xc000127fe0 sp=0xc000127f88 pc=0x45731e
runtime.goexit()
        GOROOT/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000127fe8 sp=0xc000127fe0 pc=0x487dd1

goroutine 6 [select]:
github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc00008c720)
        external/com_github_ipfs_go_log/writer/writer.go:76 +0x128
created by github.com/ipfs/go-log/writer.NewMirrorWriter
        external/com_github_ipfs_go_log/writer/writer.go:41 +0xb9

goroutine 7 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc0001092f0)
        external/com_github_dgraph_io_ristretto/policy.go:96 +0xbe
created by github.com/dgraph-io/ristretto.newDefaultPolicy
        external/com_github_dgraph_io_ristretto/policy.go:80 +0x129

goroutine 8 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc00003cba0)
        external/com_github_dgraph_io_ristretto/cache.go:257 +0xc8
created by github.com/dgraph-io/ristretto.NewCache
        external/com_github_dgraph_io_ristretto/cache.go:155 +0x1f3

goroutine 9 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc0001a43c0)
        external/com_github_dgraph_io_ristretto/policy.go:96 +0xbe
created by github.com/dgraph-io/ristretto.newDefaultPolicy
        external/com_github_dgraph_io_ristretto/policy.go:80 +0x129

goroutine 10 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc00003ccc0)
        external/com_github_dgraph_io_ristretto/cache.go:257 +0xc8
created by github.com/dgraph-io/ristretto.NewCache
        external/com_github_dgraph_io_ristretto/cache.go:155 +0x1f3

goroutine 11 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc0001e9470)
        external/com_github_dgraph_io_ristretto/policy.go:96 +0xbe
created by github.com/dgraph-io/ristretto.newDefaultPolicy
        external/com_github_dgraph_io_ristretto/policy.go:80 +0x129

goroutine 12 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc00003cde0)
        external/com_github_dgraph_io_ristretto/cache.go:257 +0xc8
created by github.com/dgraph-io/ristretto.NewCache
        external/com_github_dgraph_io_ristretto/cache.go:155 +0x1f3

goroutine 13 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc0002f0660)
        external/com_github_dgraph_io_ristretto/policy.go:96 +0xbe
created by github.com/dgraph-io/ristretto.newDefaultPolicy
        external/com_github_dgraph_io_ristretto/policy.go:80 +0x129

goroutine 14 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc00003cfc0)
        external/com_github_dgraph_io_ristretto/cache.go:257 +0xc8
created by github.com/dgraph-io/ristretto.NewCache
        external/com_github_dgraph_io_ristretto/cache.go:155 +0x1f3

goroutine 15 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc0002ff800)
        external/com_github_dgraph_io_ristretto/policy.go:96 +0xbe
created by github.com/dgraph-io/ristretto.newDefaultPolicy
        external/com_github_dgraph_io_ristretto/policy.go:80 +0x129

goroutine 18 [runnable]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc00003d800)
        external/com_github_dgraph_io_ristretto/cache.go:255
created by github.com/dgraph-io/ristretto.NewCache
        external/com_github_dgraph_io_ristretto/cache.go:155 +0x1f3

rax    0x0
rbx    0x6
rcx    0x7fc868a7efff
rdx    0x0
rdi    0x2
rsi    0x7ffe97d5c9a0
rbp    0x7fc868de66e0
rsp    0x7ffe97d5ca18
r8     0x0
r9     0x7ffe97d5c9a0
r10    0x8
r11    0x246
r12    0x29fcee0
r13    0x2705ef0
r14    0x29fd000
r15    0x9000
rip    0x7fc868a7efff
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by prestonvanloon** [comment]
I think the BLS binaries were pre-compiled for ubuntu 18. We've seen issues with ubuntu 16 https://github.com/prysmaticlabs/prysm/issues/4691 as well which were resolved by using ubuntu 18. 

I'd recommend building from source with LLVM. This requires libgmp-dev installed on your system.

```
sudo apt-get install libgmp-dev # Unless you already have it

bazel run //beacon-chain --config=llvm -- --datadir=/path/to/datadir --otherflags --etc
```

Likewise with the validator
```
bazel run //validator --config=llvm -- --validator-flags
```

**Comment by xrow** [comment]
Here is my current progress. I gave up on bazel after it was failing with the `--output_base` param.

```
FROM centos:8

ENV VERSION=0.3.7

COPY bin/uid_entrypoint /usr/bin/uid_entrypoint

RUN dnf install -y 'dnf-command(config-manager)' && \
    dnf config-manager --add-repo https://copr.fedorainfracloud.org/coprs/vbatts/bazel/repo/epel-8/vbatts-bazel-epel-8.repo && \
    dnf install -y bazel gmp-c++ gmp-devel unzip python36 git gcc patch gcc-c++

RUN curl -L -o source.zip https://github.com/prysmaticlabs/prysm/archive/v$VERSION.zip && \
    unzip source.zip && \
    cd prysm-$VERSION && bazel --output_base=release build //beacon-chain:beacon-chain  && \
    cp bazel-bin/validator/linux_amd64_stripped/beacon-chain /usr/bin/beacon-chain
```

**Comment by prestonvanloon** [comment]
Can you elaborate on the output base issue? Why override the default?

**Comment by prestonvanloon** [comment]
My progress so far
```dockerfile
FROM centos:8

ENV VERSION=0.3.7

#COPY bin/uid_entrypoint /usr/bin/uid_entrypoint


RUN dnf install -y 'dnf-command(config-manager)' && \
    dnf install -y gmp-c++ gmp-devel unzip python36 git gcc patch gcc-c++ go

# Install bazelisk as bazel. Bazelisk downloads the appropriate version of bazel as required by Prysm.
RUN export PATH=$PATH:$(go env GOPATH)/bin
RUN go get github.com/bazelbuild/bazelisk
RUN ln -s $(go env GOPATH)/bin/bazelisk /usr/bin/bazel

# Download prysm
RUN curl -L -o source.zip https://github.com/prysmaticlabs/prysm/archive/v$VERSION.zip && \
    unzip source.zip
WORKDIR prysm-$VERSION

# Build beacon-chain with llvm and release configuration.
RUN ./bazel.sh build --config=release --config=llvm //beacon-chain:beacon-chain

# Copy binary to /usr/bin
RUN cp $(bazel info bazel-bin)/beacon-chain/linux_amd64_stripped/beacon-chain /usr/bin/beacon-chain
```

**Comment by prestonvanloon** [comment]
@xrow is this still a valid issue?

**Comment by xrow** [comment]
Yes please stay tuned for 2 more weeks. I let you know.

**Comment by terencechain** [comment]
@xrow what's your recommendation on how to proceed with this?

**Comment by xrow** [comment]
Hi,

I finally completed by build for the beacon chain. Is this something that can help you to build a proper centos release?

```
FROM centos:8

ENV VERSION=0.3.9
ENV TERM=linux
ENV LANG=en_US.UTF-8

COPY bin/uid_entrypoint /usr/bin/uid_entrypoint

RUN dnf install -y 'dnf-command(config-manager)' && \
    dnf install -y gmp-c++ gmp-devel unzip python36 git gcc patch gcc-c++ go ncurses-compat-libs

# Install bazelisk as bazel. Bazelisk downloads the appropriate version of bazel as required by Prysm.
RUN export PATH=$PATH:$(go env GOPATH)/bin
RUN go get github.com/bazelbuild/bazelisk
RUN ln -s $(go env GOPATH)/bin/bazelisk /usr/bin/bazel

# Download prysm
RUN curl -L -o source.zip https://github.com/prysmaticlabs/prysm/archive/v$VERSION.zip && \
    unzip source.zip
WORKDIR prysm-$VERSION

# Build beacon-chain with llvm and release configuration.
RUN ./bazel.sh build --config=release --config=llvm //beacon-chain:beacon-chain

# Copy binary to /usr/bin
RUN cp bazel-out/k8-opt/bin/beacon-chain/linux_amd64_stripped/beacon-chain /usr/bin/beacon-chain && \
    chmod 755 /usr/bin/beacon-chain

RUN	chmod 755 /usr/bin/uid_entrypoint && \
    mkdir /data && chmod 777 /data && \
    chmod g=u /etc/passwd

VOLUME /data

WORKDIR /data

EXPOSE 4000/tcp
EXPOSE 13000/tcp
EXPOSE 4001/tcp
EXPOSE 8080/tcp

CMD /usr/bin/beacon-chain --config-file=/etc/prysm/beacon-node.yaml

ENTRYPOINT [ "/usr/bin/uid_entrypoint" ]

USER 1001
```

**Comment by prestonvanloon** [comment]
At the moment, we provide the following docker images for beacon chain and validator binaries
- Minimal (default, go only image)
- Debug (built with debug symbols, additional tooling)
- Alpine (minimal build with an alpine base image)

Since we don't use traditional `Dockerfile`s to create docker images, can you help me understand what is missing from the three available flavors of docker images?

**Comment by xrow** [comment]
Hi,

our full stack is red hat based and sometimes supported. Therefore we like to run any software under a supported stack.

**Comment by prestonvanloon** [comment]
Alright, I suppose we can add another base to our docker image deployments for beacon-chain and validator.

**Comment by 0xKiwi** [comment]
Any update on this? @prestonvanloon

**Comment by prestonvanloon** [comment]
No

**Comment by prestonvanloon** [comment]
Closing this as obsolete. We do not use herumi anymore for validator signing, so this issue should no longer be relevant.
