### ISSUE TITLE
Attestation: panic: runtime error: slice bounds out of range [576460752303423480:0]

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#5135]
```
FUZZER: panic: runtime error: slice bounds out of range [576460752303423480:0]
FUZZER: 
FUZZER: goroutine 17 [running, locked to thread]:
FUZZER: github.com/prysmaticlabs/prysm/beacon-chain/cache.(*CommitteeCache).Committee(0x10c0004611c0, 0x0, 0x109233925671068b, 0x6fc288a71d6cead5, 0x2a5b3160c67e8a65, 0xb570fa314e252e1f, 0xdffffffffffffff, 0x0, 0x0, 0x0, ...)
FUZZER: 	beacon-chain/cache/committee.go:103 +0x5f4
FUZZER: github.com/prysmaticlabs/prysm/beacon-chain/core/helpers.BeaconCommitteeFromState(0x10c000626620, 0x0, 0xdffffffffffffff, 0x93110b9, 0x10c000626628, 0x0, 0x8caf463, 0x8bc5fa0)
FUZZER: 	beacon-chain/core/helpers/committee.go:76 +0x115
FUZZER: github.com/prysmaticlabs/prysm/beacon-chain/core/helpers.VerifyAttestationBitfieldLengths(0x10c000626620, 0x10c000581920, 0x2bf246, 0x1f)
FUZZER: 	beacon-chain/core/helpers/committee.go:333 +0x5a
FUZZER: github.com/prysmaticlabs/prysm/beacon-chain/core/blocks.ProcessAttestationNoVerify(0x9c56d20, 0x10c0000e0040, 0x10c000626620, 0x10c000581920, 0x0, 0x0, 0x0)
FUZZER: 	beacon-chain/core/blocks/block_operations.go:714 +0x576
FUZZER: github.com/prysmaticlabs/prysm/beacon-chain/core/blocks/fuzz.BeaconFuzzAttestation(0x10c000aa4000, 0xec, 0xec, 0x10c000aa4000, 0x0, 0x10c0000b6058, 0x10c000086e90)
FUZZER: 	beacon-chain/core/blocks/fuzz/attestation_fuzz.go:27 +0x35f
FUZZER: main.LLVMFuzzerTestOneInput(...)
FUZZER: 	attestation_fuzz_test_libfuzz_main_main.fuzz.go:15
FUZZER: main._cgoexpwrap_a5d1760088a2_LLVMFuzzerTestOneInput(0x61100068ac80, 0xec, 0x621000001500)
FUZZER: 	_cgo_gotypes.go:65 +0xc2
FUZZER: ==27== ERROR: libFuzzer: deadly signal
```

https://app.fuzzit.dev/orgs/prysmaticlabs-gh/targets/attestation/YxVNAO1h0jr651YFYOy6

**Comment by prestonvanloon** [comment]
Input data as proto string
```
aggregation_bits: "\377\001"
data: <
  committee_index: 1008806316530991103
  beacon_block_root: "y\326\21064\224z\010\344\336\000gA\rB\366\303+al7\177\236\323\207\314?\311\002\016\244\313"
  source: <
    root: "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
  >
  target: <
    root: "y\326\21064\224z\010\344\336\000gA\rB\366\303+al7\177\236\323\207\314?\311\002\016\244\313"
  >
>
signature: "\270>zs_\253M\274\260\022#\322{\347\356\305+\335\263uv\375\305R\316\372\233\231#\031\342)\366\013gh\374\336\327\022\314\363rQ\221h\247f\026\2308\237\335\0233\232|\021j\367\241\327\322\323\236\370\360\233\345\2631\013\026JF\377\237\327\200\350\274\333PN\372\371X\251\241\237J\342\354\330\\^"
```
