### ISSUE TITLE
fatal error: acquireSudog: found s.elem != nil in cache

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#5167]
This has happened with a few fuzz targets.

https://app.fuzzit.dev/orgs/prysmaticlabs-gh/targets/attestation/8XaQqowAnISV2GkZ1hio
https://app.fuzzit.dev/orgs/prysmaticlabs-gh/targets/voluntary-exit/fhMhyQSRXOm7mo8HT487

```
FUZZER: fatal error: acquireSudog: found s.elem != nil in cache
FUZZER: 
FUZZER: goroutine 17 [running, locked to thread]:
FUZZER: runtime.throw(0x299ba9, 0x2a)
FUZZER: 	GOROOT/src/runtime/panic.go:1114 +0x74 fp=0x10c000080908 sp=0x10c0000808d8 pc=0x8d45884
FUZZER: runtime.acquireSudog(0xaa5e7f4)
FUZZER: 	GOROOT/src/runtime/proc.go:351 +0x37e fp=0x10c000080978 sp=0x10c000080908 pc=0x8d4877e
FUZZER: runtime.semacquire1(0xaa5e7f4, 0x10c000080a00, 0x0, 0x0)
FUZZER: 	GOROOT/src/runtime/sema.go:115 +0x5d fp=0x10c0000809e0 sp=0x10c000080978 pc=0x8d586ad
FUZZER: runtime.semacquire(...)
FUZZER: 	GOROOT/src/runtime/sema.go:95
FUZZER: runtime.gcMarkDone()
FUZZER: 	GOROOT/src/runtime/mgc.go:1425 +0x40 fp=0x10c000080a38 sp=0x10c0000809e0 pc=0x8d2cc70
FUZZER: runtime.gcAssistAlloc(0x10c000000600)
FUZZER: 	GOROOT/src/runtime/mgcmark.go:450 +0x20c fp=0x10c000080a98 sp=0x10c000080a38 pc=0x8d2f94c
FUZZER: runtime.mallocgc(0x20, 0x0, 0x0, 0x10c000d7b180)
FUZZER: 	GOROOT/src/runtime/malloc.go:940 +0x919 fp=0x10c000080b38 sp=0x10c000080a98 pc=0x8d1e5a9
FUZZER: runtime.growslice(0x99466c0, 0x0, 0x0, 0x0, 0x20, 0x10c000d7b180, 0x0, 0x20)
FUZZER: 	GOROOT/src/runtime/slice.go:175 +0x150 fp=0x10c000080ba0 sp=0x10c000080b38 pc=0x8d5cc80
FUZZER: github.com/prysmaticlabs/prysm/proto/beacon/p2p/v1.(*BeaconState).UnmarshalSSZ(0x10c00050bc80, 0x10c0018f4000, 0x298269, 0x532000, 0x5304d2, 0x532000)
FUZZER: 	bazel-out/k8-opt/bin/proto/beacon/p2p/v1/generated.ssz.go:396 +0x400 fp=0x10c000080d28 sp=0x10c000080ba0 pc=0x9367cc0
FUZZER: github.com/prysmaticlabs/prysm/beacon-chain/testing.GetBeaconFuzzState(0x10c000c70002, 0xec)
FUZZER: 	beacon-chain/testing/beacon_fuzz_states.go:19 +0x13d fp=0x10c000080da8 sp=0x10c000080d28 pc=0x96441bd
FUZZER: github.com/prysmaticlabs/prysm/beacon-chain/core/blocks/fuzz.BeaconFuzzAttestation(0x10c000c7c000, 0xec, 0xec, 0x10c000c7c000, 0x0, 0x10c000100058, 0x10c000080e90)
FUZZER: 	beacon-chain/core/blocks/fuzz/attestation_fuzz.go:19 +0x1e4 fp=0x10c000080e40 sp=0x10c000080da8 pc=0x9644dc4
FUZZER: main.LLVMFuzzerTestOneInput(...)
FUZZER: 	attestation_fuzz_test_libfuzz_main_main.fuzz.go:15
```

[full_log.txt](https://github.com/prysmaticlabs/prysm/files/4366279/orgs_prysmaticlabs-gh_targets_attestation_jobs_8XaQqowAnISV2GkZ1hio_log.txt)

**Comment by prestonvanloon** [comment]
Looks like this has been an issue a few years ago and mentions memory corruption (https://github.com/golang/go/issues/10541) and it may be resolved with an update to the linux kernel (https://github.com/golang/go/issues/18067). My brief google search doesn't return much more than those two points.

I'll email the fuzzit team and ask for more info about the environment.

**Comment by prestonvanloon** [comment]
The last line of our code that panics looks like this

bazel-out/k8-opt/bin/proto/beacon/p2p/v1/generated.ssz.go
```go
        // Field (4) 'BlockRoots'
        b.BlockRoots = make([][]byte, 8192)
        for ii := 0; ii < 8192; ii++ {
                b.BlockRoots[ii] = append(b.BlockRoots[ii], buf[136:262280][ii*32:(ii+1)*32]...) // line 396
        }
```

**Comment by nisdas** [comment]
Still an issue ? @prestonvanloon

**Comment by prestonvanloon** [comment]
Yes

**Comment by nisdas** [comment]
Is this still relevant @prestonvanloon ?

**Comment by prestonvanloon** [comment]
This probably is no longer an issue. I created a fuzz test PR with the explicit failure case that was original reported. It is not failing now so I would say we can close this with the merge of #10935
