### ISSUE TITLE
Fatal error: mlock of signal stack failed

### ISSUE THREAD

**Issue by cleanunicorn** [prysmaticlabs/prysm#5171]
Operating system: Arch
```console
$ lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```

Running `beacon-chain` image in docker, latest image.
```
$ docker images | grep beacon-chain
gcr.io/prysmaticlabs/prysm/beacon-chain       latest              b96edb5366e6        50 years ago        60.1MB
```

It seems to be related to this issue.
https://github.com/golang/go/issues/37436

Which is a problem with the current go version.

The node keeps crashing and I am unable to validate any more.

```console
[2020-03-23 10:09:39]  INFO blockchain: Executing state transition on block root=0xe7ddd6f6... slot=528648
runtime: mlock of signal stack failed: 12
runtime: increase the mlock limit (ulimit -l) or
runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
fatal error: mlock failed

runtime stack:
runtime.throw(0x16db647, 0xc)
        GOROOT/src/runtime/panic.go:1112 +0x72
runtime.mlockGsignal(0xc014e1d080)
        GOROOT/src/runtime/os_linux_x86.go:72 +0x107
runtime.mpreinit(0xc005824e00)
        GOROOT/src/runtime/os_linux.go:341 +0x78
runtime.mcommoninit(0xc005824e00)
        GOROOT/src/runtime/proc.go:630 +0x108
runtime.allocm(0xc00004a800, 0x0, 0x1)
        GOROOT/src/runtime/proc.go:1390 +0x14e
runtime.newm(0x0, 0xc00004a800)
        GOROOT/src/runtime/proc.go:1704 +0x39
runtime.startm(0xc00004a800, 0x26df600)
        GOROOT/src/runtime/proc.go:1869 +0x12a
runtime.handoffp(0xc00004a800)
        GOROOT/src/runtime/proc.go:1896 +0x52
runtime.retake(0x3ef51753be8d, 0xc00004a800)
        GOROOT/src/runtime/proc.go:4628 +0x157
runtime.sysmon()
        GOROOT/src/runtime/proc.go:4537 +0x138
runtime.mstart1()
        GOROOT/src/runtime/proc.go:1097 +0xc3
runtime.mstart()
        GOROOT/src/runtime/proc.go:1062 +0x6e

goroutine 1 [chan receive, 2 minutes]:
github.com/prysmaticlabs/prysm/beacon-chain/node.(*BeaconNode).Start(0xc00007dc20)
        beacon-chain/node/node.go:209 +0x1dc
main.startNode(0xc000022380, 0xc00009cd00, 0x0)
        beacon-chain/main.go:175 +0xc3
gopkg.in/urfave/cli%2ev2.(*App).Run(0xc000578180, 0xc000120020, 0x2, 0x2, 0x0, 0x0)
        external/in_gopkg_urfave_cli_v2/app.go:270 +0x5e9
main.main()
        beacon-chain/main.go:154 +0x1a6
```

**Comment by prestonvanloon** [comment]
Have you seen https://golang.org/wiki/LinuxKernelSignalVectorBug? 

I'm tracking this issue, but unclear on a fast resolution or workaround we can make.

**Comment by prestonvanloon** [comment]
I'm going to go ahead and close this since it appears to be a bug in the linux kernel. 

The long term resolution is described here: https://github.com/golang/go/issues/37436#issuecomment-591327351

TL;DR update your linux kernel as advised in the error. 

If that still doesn't work, please reopen and we can investigate further.

**Comment by cleanunicorn** [comment]
I compiled the `.c` program they provide in the link and ran the binary. Unfortunately it did not crash. They say the program should crash immediately if the kernel has the bug or it will run for 60 seconds if it's not vulnerable.

```console
$ time ./a.out
0.00user 0.00system 1:00.01elapsed 0%CPU (0avgtext+0avgdata 1540maxresident)k
0inputs+0outputs (0major+90minor)pagefaults 0swaps
```
The kernel is in the version vulnerable error range but I don't know if it was compiled with GCC9 (vulnerable) or GCC8 (not vulnerable).

```console
$ uname -r
5.3.0-42-generic
```

**Comment by cleanunicorn** [comment]
Even though it seems it's not vulnerable, adding `--ulimit memlock=67108864` fixes the problem.

Thanks for the help, @prestonvanloon !
