### ISSUE TITLE
SIGSEGV in onAttestation() method

### ISSUE THREAD

**Issue by farazdagi** [prysmaticlabs/prysm#5427]
From time to time, I see this nil pointer dereference issue:

```
[2020-04-14 12:14:59]  INFO sync: Requesting parent block currentSlot=686768 parentRoot=bdb62d670fbd
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4d31c18]

goroutine 273 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).onAttestation(0xc00000c3c0, 0x569b300, 0xc04245e000, 0xc03db25f20, 0x0, 0x0, 0x0, 0x0, 0x0)
        beacon-chain/blockchain/process_attestation.go:129 +0x538
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveAttestationNoPubsub(0xc00000c3c0, 0x569b300, 0xc04242bfb0, 0xc03db25f20, 0x0, 0x0)
        beacon-chain/blockchain/receive_attestation.go:36 +0xee
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).processAttestation(0xc00000c3c0, 0xc00eb4f740)
        beacon-chain/blockchain/receive_attestation.go:113 +0x543
created by github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).Start
        beacon-chain/blockchain/service.go:233 +0xac5
```

**Comment by prestonvanloon** [comment]
Need nil checks here
https://github.com/prysmaticlabs/prysm/blob/b69c76c879c1c1a827ba8b475bb59f4bdefd703e/beacon-chain/blockchain/process_attestation.go#L129
