### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by MysticRyuujin** [prysmaticlabs/prysm#6281]
```
prysm@eth2test:~$ /data/prysm/prysm.sh beacon-chain --config-file=/data/prysm/configs/beacon.yaml
Latest Prysm version is v1.0.0-alpha.11.
Beacon chain is up to date.
Verifying binary integrity.
beacon-chain-v1.0.0-alpha.11-linux-amd64: OK
gpg: Signature made Fri 12 Jun 2020 02:44:07 PM CDT
gpg:                using RSA key 0AE0051D647BA3C1A917AF4072E33E4DF1A5036E
gpg: Good signature from "Preston Van Loon <preston@prysmaticlabs.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0AE0 051D 647B A3C1 A917  AF40 72E3 3E4D F1A5 036E
Verified /data/prysm/dist/beacon-chain-v1.0.0-alpha.11-linux-amd64 has been signed by Prysmatic Labs.
Starting Prysm beacon-chain --config-file=/data/prysm/configs/beacon.yaml
2020/06/16 10:07:58 maxprocs: Leaving GOMAXPROCS=16: CPU quota undefined
[2020-06-16 10:07:58]  INFO Logs will be made persistent logFileName=/data/prysm/logs/beacon/beacon.log
[2020-06-16 10:07:58]  INFO File logging initialized
[2020-06-16 10:07:58]  INFO node: Checking DB database-path=/data/prysm/beaconchaindata
[2020-06-16 10:07:58]  WARN node: Using default ETH1 connection provided by Prysmatic Labs. Please consider running your own ETH1 node for better uptime, security, and decentralization of ETH2. Visit https://docs.prylabs.network/docs/prysm-usage/setup-eth1 for more information.
[2020-06-16 10:07:58]  INFO node: Starting beacon node version=Prysm/v1.0.0-alpha.11/87ca73d60512ef488fe9551237bc9601c0f34809. Built at: 2020-06-12 19:11:43+00:00
[2020-06-16 10:07:58]  INFO gateway: Starting JSON-HTTP API address=127.0.0.1:3500
[2020-06-16 10:07:58]  INFO rpc: RPC-API listening on port address=127.0.0.1:4000
[2020-06-16 10:07:58]  WARN rpc: You are using an insecure gRPC connection! Provide a certificate and key to connect securely
[2020-06-16 10:07:59]  INFO blockchain: Blockchain data already exists in DB, initializing...
[2020-06-16 10:07:59]  INFO initial-sync: Starting initial chain sync...
[2020-06-16 10:07:59]  INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=0
[2020-06-16 10:07:59]  INFO slotutil: Chain genesis time reached genesisTime=2020-06-14 00:17:24 -0500 CDT genesisValidators=16392
[2020-06-16 10:07:59]  INFO p2p: Started discovery v5 ENR=enr:-LK4QH5rQjEDalAxcLec7niv0z2T_jn_c7QBX8XPXqz5HxRxOiJ44H6-X_LIskoLrE8Z0eakFC6bohBuT9hyc8--_iYBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCmW0iXAAAAAP__________gmlkgnY0gmlwhMCoDyOJc2VjcDI1NmsxoQIVF42c96N1Xsa0TBpVKMKiwdrwvH3RtwD2AAueRmtqP4N0Y3CCMsiDdWRwgi7g
[2020-06-16 10:07:59]  INFO p2p: Node started p2p server multiAddr=/ip4/192.168.15.35/tcp/13000/p2p/16Uiu2HAkvr1NYLszdUckTH4ec4rSnFhihoifZRkNdj4w8z5giHki
[2020-06-16 10:07:59]  INFO powchain: Connected to eth1 proof-of-work chain endpoint=https://goerli.prylabs.net
[2020-06-16 10:07:59]  INFO p2p: Peer Connected activePeers=3 direction=Outbound multiAddr=/ip4/206.189.206.45/tcp/13000/p2p/16Uiu2HAkyKnpsoLsQyhmjDcGKoffoQZJB61rAQqbuQy9Y9nuvmug peer=16Uiu2HAkyKnpsoLsQyhmjDcGKoffoQZJB61rAQqbuQy9Y9nuvmug
[2020-06-16 10:07:59]  INFO p2p: Peer Connected activePeers=3 direction=Outbound multiAddr=/ip4/70.120.156.208/tcp/13000/p2p/16Uiu2HAmBpUPRGbwtX1wYSuCQQmqXgAp1UtHUHZpqfW1TPDA72N7 peer=16Uiu2HAmBpUPRGbwtX1wYSuCQQmqXgAp1UtHUHZpqfW1TPDA72N7
[2020-06-16 10:07:59]  INFO p2p: Peer Connected activePeers=4 direction=Outbound multiAddr=/ip4/138.68.62.32/tcp/13000/p2p/16Uiu2HAmVNzhYrgda43ocN79KwGNtG769vQsBd9itcztUD3umR6V peer=16Uiu2HAmVNzhYrgda43ocN79KwGNtG769vQsBd9itcztUD3umR6V
[2020-06-16 10:07:59]  INFO p2p: Peer Connected activePeers=7 direction=Outbound multiAddr=/ip4/74.73.49.78/tcp/13000/p2p/16Uiu2HAm11UWAYX841xjbSuTx8jhceAmZuLk5qHRuA2WCqtEPDeN peer=16Uiu2HAm11UWAYX841xjbSuTx8jhceAmZuLk5qHRuA2WCqtEPDeN
[2020-06-16 10:08:00]  INFO p2p: Peer Connected activePeers=12 direction=Outbound multiAddr=/ip4/86.40.51.185/tcp/13000/p2p/16Uiu2HAmGWCCiUSXzW4zRPpNY5PAHiRw567FWJaqtMRfbYWrHmQy peer=16Uiu2HAmGWCCiUSXzW4zRPpNY5PAHiRw567FWJaqtMRfbYWrHmQy
[2020-06-16 10:08:00]  INFO p2p: Peer Connected activePeers=12 direction=Outbound multiAddr=/ip4/178.128.167.60/tcp/13000/p2p/16Uiu2HAm3kXDnWKiznH1DZkY65W2cjC3H9aZCfdPLLy9bSEQeTyC peer=16Uiu2HAm3kXDnWKiznH1DZkY65W2cjC3H9aZCfdPLLy9bSEQeTyC
[2020-06-16 10:08:00]  INFO p2p: Peer Connected activePeers=12 direction=Outbound multiAddr=/ip4/5.63.56.145/tcp/13000/p2p/16Uiu2HAmS1PsyeHWdB6H68E1PMKzUmsFws7Cqx5Jy71asJX6qKZc peer=16Uiu2HAmS1PsyeHWdB6H68E1PMKzUmsFws7Cqx5Jy71asJX6qKZc
[2020-06-16 10:08:00]  INFO p2p: Peer Connected activePeers=12 direction=Outbound multiAddr=/ip4/93.227.255.189/tcp/13000/p2p/16Uiu2HAm4iA5LC8Aby8ubh1maCkfBZvCbtY6WUvU87bgavHPhn3J peer=16Uiu2HAm4iA5LC8Aby8ubh1maCkfBZvCbtY6WUvU87bgavHPhn3J
[2020-06-16 10:08:00]  INFO p2p: Peer Connected activePeers=12 direction=Outbound multiAddr=/ip4/79.236.154.95/tcp/13000/p2p/16Uiu2HAmU5DSaxHsbRwftYES7Ybz6bPWr3f4R1WfNxEFPz1XwDni peer=16Uiu2HAmU5DSaxHsbRwftYES7Ybz6bPWr3f4R1WfNxEFPz1XwDni
[2020-06-16 10:08:00]  INFO p2p: Peer Connected activePeers=12 direction=Outbound multiAddr=/ip4/89.141.239.7/tcp/15000/p2p/16Uiu2HAmFKP86vtpHkgizzDzhCxEidsKPYF66SPaRc9NSkuMVoPT peer=16Uiu2HAmFKP86vtpHkgizzDzhCxEidsKPYF66SPaRc9NSkuMVoPT
[2020-06-16 10:08:00]  INFO p2p: Peer Connected activePeers=13 direction=Outbound multiAddr=/ip4/220.129.191.83/tcp/13000/p2p/16Uiu2HAmQMufCAw9dzdKyQq2JNbXuJNkDVa9cya2QEdyQkX6e3mq peer=16Uiu2HAmQMufCAw9dzdKyQq2JNbXuJNkDVa9cya2QEdyQkX6e3mq
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xd9c548]

goroutine 2744 [running]:
go.etcd.io/bbolt.(*Bucket).Stats(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        external/io_etcd_go_bbolt/bucket.go:400 +0xb8
github.com/prysmaticlabs/prombbolt.forEachWithBoltDB.func1.1.1(0x7f530166e040, 0x20, 0x20, 0x0, 0x0, 0x0)
        external/com_github_prysmaticlabs_prombbolt/bucketstatscollector.go:181 +0x4c
go.etcd.io/bbolt.(*Tx).ForEach.func1(0x7f530166e040, 0x20, 0x20, 0x7f530166e060, 0x26ce, 0x26ce, 0x26ce, 0x0)
        external/io_etcd_go_bbolt/tx.go:130 +0x8c
go.etcd.io/bbolt.(*Bucket).ForEach(0xc00a63e018, 0xc006e9cd40, 0x203001, 0x203001)
        external/io_etcd_go_bbolt/bucket.go:390 +0xfe
go.etcd.io/bbolt.(*Tx).ForEach(0xc00a63e000, 0xc006e9cd88, 0xc00075c000, 0xc00a63e000)
        external/io_etcd_go_bbolt/tx.go:129 +0x67
github.com/prysmaticlabs/prombbolt.forEachWithBoltDB.func1.1(0xc00a63e000, 0x0, 0xc00a63e000)
        external/com_github_prysmaticlabs_prombbolt/bucketstatscollector.go:177 +0x52
go.etcd.io/bbolt.(*DB).View(0xc00075c000, 0xc006e9ce30, 0x0, 0x0)
        external/io_etcd_go_bbolt/db.go:725 +0x8e
github.com/prysmaticlabs/prombbolt.forEachWithBoltDB.func1(0xc006bdaae0, 0xc006bdaae0, 0xc0007f72d0)
        external/com_github_prysmaticlabs_prombbolt/bucketstatscollector.go:176 +0x52
github.com/prysmaticlabs/prombbolt.(*bucketStatsCollector).Collect(0xc000a5e870, 0xc00a8e4180)
        external/com_github_prysmaticlabs_prombbolt/bucketstatscollector.go:189 +0x6c
github.com/prysmaticlabs/prombbolt.(*collector).Collect(0xc00089dd00, 0xc00a8e4180)
        external/com_github_prysmaticlabs_prombbolt/prombolt.go:53 +0x8e
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        external/com_github_prometheus_client_golang/prometheus/registry.go:443 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        external/com_github_prometheus_client_golang/prometheus/registry.go:454 +0x599
```

```
prysm@eth2test:~$ cat /data/prysm/configs/beacon.yaml
datadir: "/data/prysm"
log-file: "/data/prysm/logs/beacon/beacon.log"
#http-web3provider: "http://localhost:8545"
graffiti: "MysticRyuujin"
p2p-max-peers: 100
```

**Comment by MysticRyuujin** [comment]
If I had to guess, I'd guess unsafe shutdown load to db corruption?

**Comment by shayzluf** [comment]
@MysticRyuujin can you please add a link to the log file?

**Comment by MysticRyuujin** [comment]
Unfortunately I don't think my log fine contains any useful information. First, my log file was 11GB because 1) Logs don't rotate. 2) My logs were flooded with entries about being unable to process past logs due to a Nethermind RPC issue.

Second, Prysm don't actually log errors like the above error in the log file, the only way to see them is when interactively running. Maybe via journalctrl or something on the service could I see it, but again logs were way too big for me to be able to get that data from over a week ago.

**Comment by shayzluf** [comment]
Thank @MysticRyuujin for reporting. Log rotation can be a good issue to look into

**Comment by prestonvanloon** [comment]
Was there anything else interesting about your environment? Out of disk space?
Where you collecting prometheus metrics at the time?

**Comment by MysticRyuujin** [comment]
Not that I'm aware of. I'd just close this. I have no info beyond the log, and the suggestion that perhaps it was an unsafe shutdown.

**Comment by prestonvanloon** [comment]
OK, thanks. Let me know if you see it again please!
