### ISSUE TITLE
Panic when disabling dynamic attestation subnets

### ISSUE THREAD

**Issue by mcdee** [prysmaticlabs/prysm#6521]
Running the beacon node with `--disable-dynamic-committee-subnets` causes a panic.

### Has this worked before in a previous version?

No.

## 🔬 Minimal Reproduction

`beacon-chain --disable-dynamic-committee-subnets`

## 🔥 Error

```
panic: /eth2/%x/beacon_attestation_0 is not mapped to any message in GossipTopicMappings
goroutine 245 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).subscribe(0xc00000c1e0, 0xc00ce886a0, 0x1d, 0xc0006b6d20, 0xc0006b6d30, 0xc00ce886a0)
        beacon-chain/sync/subscriber.go:97 +0x18b
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).registerSubscribers(0xc00000c1e0)
        beacon-chain/sync/subscriber.go:77 +0x3a9
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).registerHandlers(0xc00000c1e0)
        beacon-chain/sync/service.go:244 +0x3dd
created by github.com/prysmaticlabs/prysm/beacon-chain/sync.NewRegularSync
        beacon-chain/sync/service.go:140 +0x32c
```

**Comment by dv8silencer** [comment]
This seems to be because in beacon-chain/sync/subscriber.go lines 75+
```
	if featureconfig.Get().DisableDynamicCommitteeSubnets {
		for i := uint64(0); i < params.BeaconNetworkConfig().AttestationSubnetCount; i++ {
			s.subscribe(
				fmt.Sprintf("/eth2/%%x/beacon_attestation_%d", i),
				s.validateCommitteeIndexBeaconAttestation,   /* validator */
				s.committeeIndexBeaconAttestationSubscriber, /* message handler */
			)
		}
	}
```
In the call to subscribe, when i=0, something like "/eth2/%x/beacon_attestation_0" is passed as the topic string:
```
func (s *Service) subscribe(topic string, validator pubsub.ValidatorEx, handle subHandler) *pubsub.Subscription {
	base := p2p.GossipTopicMappings[topic]
	if base == nil {
		panic(fmt.Sprintf("%s is not mapped to any message in GossipTopicMappings", topic))
	}
	return s.subscribeWithBase(base, s.addDigestToTopic(topic), validator, handle)
}
```

p2p.GossipTopicMappings["/eth2/%x/beacon_attestation_0"] is nil and causes the panic.

Within gossip_topic_mappings.go

```
var GossipTopicMappings = map[string]proto.Message{
	"/eth2/%x/beacon_block":               &pb.SignedBeaconBlock{},
	"/eth2/%x/beacon_attestation_%d":      &pb.Attestation{},
	"/eth2/%x/voluntary_exit":             &pb.SignedVoluntaryExit{},
	"/eth2/%x/proposer_slashing":          &pb.ProposerSlashing{},
	"/eth2/%x/attester_slashing":          &pb.AttesterSlashing{},
	"/eth2/%x/beacon_aggregate_and_proof": &pb.SignedAggregateAttestationAndProof{},
}
```

"/eth2/%x/beacon_attestation_%d" is set to &pb.Attestation{} but "/eth2/%x/beacon_attestation_0" (or _1, _2, _3...) are not set to anything.

Unfortunately I do not know enough about pub/sub and the consequences or semantics of DisableDynamicCommitteeSubnets for ETH2 to really solve this.  Changing beacon-chain/sync/subscriber.go lines 75+ to be something like 

```
	if featureconfig.Get().DisableDynamicCommitteeSubnets {
		for i := uint64(0); i < params.BeaconNetworkConfig().AttestationSubnetCount; i++ {
			p2p.GossipTopicMappings[fmt.Sprintf("/eth2/%%x/beacon_attestation_%d",i)] = &pb.Attestation{}
			s.subscribe(
				fmt.Sprintf("/eth2/%%x/beacon_attestation_%d", i),
				s.validateCommitteeIndexBeaconAttestation,   /* validator */
				s.committeeIndexBeaconAttestationSubscriber, /* message handler */
			)
		}
	}
```
(All that is added is p2p.GossipTopicMappings[fmt.Sprintf("/eth2/%%x/beacon_attestation_%d",i)] = &pb.Attestation{})

Fixes that panic but I have no idea if this is a meaningful solution.

**Comment by dv8silencer** [comment]
Code above refers to repo as of https://github.com/prysmaticlabs/prysm/tree/132ad5beb8c0836d004976068584607524f1bd0d

**Comment by handelaar2** [comment]
#6447 covers the same issue
