### ISSUE TITLE
--enable-finalized-deposits-cache panics in e2e 

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#6588]
```
time="2020-07-13 20:22:08" level=error msg="gRPC panicked!" error="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 3390 [running]:
runtime/debug.Stack(0xc000174000, 0x1b50643, 0x5)
	GOROOT/src/runtime/debug/stack.go:24 +0x9d
github.com/prysmaticlabs/prysm/shared/traceutil.RecoveryHandlerFunc(0x1f4efe0, 0xc001446450, 0x192d740, 0x2c057b0, 0xc002153080, 0x203000)
	shared/traceutil/recovery_interceptor_option.go:29 +0x155
github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom(0x1f4efe0, 0xc001446450, 0x192d740, 0x2c057b0, 0x1d205d8, 0xc002152fa0, 0x0)
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:53 +0x5a
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1(0x1f4efe0, 0xc001446450, 0xc000640088, 0xc002153ab0)
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:27 +0x77
panic(0x192d740, 0x2c057b0)
	GOROOT/src/runtime/panic.go:969 +0x166
github.com/prysmaticlabs/prysm/beacon-chain/cache/depositcache.(*DepositCache).FinalizedDeposits(0xc0004ed1f0, 0x1f4efe0, 0xc001446540, 0x0)
	beacon-chain/cache/depositcache/deposits_cache.go:252 +0xe8
github.com/prysmaticlabs/prysm/beacon-chain/rpc/validator.(*Server).depositTrie(0xc0002fc300, 0x1f4efe0, 0xc001446540, 0xc0017b1440, 0xc003388800, 0x20, 0x20)
	beacon-chain/rpc/validator/proposer.go:363 +0x382
github.com/prysmaticlabs/prysm/beacon-chain/rpc/validator.(*Server).deposits(0xc0002fc300, 0x1f4efe0, 0xc001446540, 0xc0038b8cc0, 0xc0038b8cc0, 0x0, 0x0, 0x0, 0xc001446540)
	beacon-chain/rpc/validator/proposer.go:299 +0x1e1
github.com/prysmaticlabs/prysm/beacon-chain/rpc/validator.(*Server).GetBlock(0xc0002fc300, 0x1f4efe0, 0xc001446540, 0xc0037c8180, 0x0, 0x0, 0x0)
	beacon-chain/rpc/validator/proposer.go:63 +0x3ff
github.com/prysmaticlabs/ethereumapis/eth/v1alpha1._BeaconNodeValidator_GetBlock_Handler.func1(0x1f4efe0, 0xc001446510, 0x1ac6fc0, 0xc0037c8180, 0xc0005b2758, 0x5a049d, 0x1a41740, 0xc001446510)
	bazel-out/k8-fastbuild/bin/external/com_github_prysmaticlabs_ethereumapis/eth/v1alpha1/linux_amd64_stripped/go_proto%/github.com/prysmaticlabs/ethereumapis/eth/v1alpha1/validator.pb.go:2473 +0x86
github.com/prysmaticlabs/prysm/beacon-chain/rpc.(*Service).validatorUnaryConnectionInterceptor(0xc00012a780, 0x1f4efe0, 0xc001446510, 0x1ac6fc0, 0xc0037c8180, 0xc0037e01c0, 0xc0037e01e0, 0x2da5608, 0x1f4efe0, 0xc001446510, ...)
	beacon-chain/rpc/service.go:393 +0x77
```

Nil pointer here: https://github.com/prysmaticlabs/prysm/blob/f7088e037cc1401500240ac3b180bee1c1d9b25e/beacon-chain/cache/depositcache/deposits_cache.go#L252

_Originally posted by @prestonvanloon in https://github.com/prysmaticlabs/prysm/pull/6391#issuecomment-657783540_

**Comment by rkapka** [comment]
I will take a look at this tomorrow.
