### ISSUE TITLE
Panic when beacon gets shut down

### ISSUE THREAD

**Issue by stefa2k** [prysmaticlabs/prysm#6924]
# 🐞 Bug Report

### Description

Beacon chain container gets shut down with `docker-compose down` and throws panic.

## 🔥 Error

```
time="2020-08-07 08:49:33" level=panic msg="Could not stop the following service: *blockchain.Service, could not get ancestor state: context canceled" prefix=registry
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
https://github.com/stefa2k/prysm-docker-compose with docker tag `HEAD-40b68d`
  </code>
</pre>

**Comment by protolambda** [comment]
Also getting a panic on shutdown (on attacknet node), may be related:
```
time="2020-08-15 15:41:55" level=panic msg="Could not stop the following service: *blockchain.Service, could not get ancestor state: context canceled" prefix=registry
panic: (*logrus.Entry) (0x5c8220,0xc002373490)

goroutine 35020 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000e0000, 0xc0008608d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        external/com_github_sirupsen_logrus/entry.go:259 +0x335
github.com/sirupsen/logrus.(*Entry).Log(0xc000843880, 0x0, 0xc000067ea0, 0x1, 0x1)
        external/com_github_sirupsen_logrus/entry.go:287 +0xeb
github.com/sirupsen/logrus.(*Entry).Logf(0xc000843880, 0x0, 0x623f6c, 0x2c, 0xc000067f20, 0x2, 0x2)
        external/com_github_sirupsen_logrus/entry.go:333 +0xe2
github.com/sirupsen/logrus.(*Entry).Panicf(...)
        external/com_github_sirupsen_logrus/entry.go:371
github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StopAll(0xc000903f00)
        shared/service_registry.go:57 +0x165
github.com/prysmaticlabs/prysm/beacon-chain/node.(*BeaconNode).Close(0xc00013c840)
        beacon-chain/node/node.go:279 +0xdf
created by github.com/prysmaticlabs/prysm/beacon-chain/node.(*BeaconNode).Start.func1
        beacon-chain/node/node.go:258 +0x189
```
