### ISSUE TITLE
Validator segfault

### ISSUE THREAD

**Issue by Bobface** [prysmaticlabs/prysm#7013]
# 🐞 Bug Report

### Description

The validator crashed after some time.
Git commit `859e59b6f7aa1eddc1f7abe359fd853b8f32a2cf`

## 🔥 Error

```
....
[2020-08-14 19:59:01] ERROR validator: Could not request attestation to sign at slot error=rpc error: code = InvalidArgument desc = invalid request: attestation slot 74638 not within attestation propagation range of 74662 to 74694 (current slot) pubKey=0xb6d4b447520b slot=74638
[2020-08-14 19:59:01]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=2332 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=32.072238056 oldBalance=32.072437218 percentChange=-0.00062% percentChangeSinceStart=0.22574% pubKey=0xb6d4b447520b startBalance=32
[2020-08-14 19:59:01]  INFO validator: Previous epoch aggregated voting summary attestationInclusionPct=0% correctlyVotedHeadPct=NaN% correctlyVotedSourcePct=NaN% correctlyVotedTargetPct=NaN% epoch=2332
[2020-08-14 19:59:01]  INFO validator: Vote summary since launch attestationsInclusionPct=95% averageInclusionDistance=1.38 slots correctlyVotedHeadPct=99% correctlyVotedSourcePct=100% correctlyVotedTargetPct=100% numberOfEpochs=1472 pctChangeCombinedBalance=0.22637%
[2020-08-14 19:59:01]  INFO validator: Attestation schedule attesters=1 pubKeys=[0xb6d4b447520b] slot=74685
[2020-08-14 19:59:02]  INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=2333 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=32.072238056 oldBalance=32.072437218 percentChange=-0.00062% percentChangeSinceStart=0.22574% pubKey=0xb6d4b447520b startBalance=32
[2020-08-14 19:59:02]  INFO validator: Previous epoch aggregated voting summary attestationInclusionPct=0% correctlyVotedHeadPct=NaN% correctlyVotedSourcePct=NaN% correctlyVotedTargetPct=NaN% epoch=2333
[2020-08-14 19:59:02]  INFO validator: Vote summary since launch attestationsInclusionPct=95% averageInclusionDistance=1.38 slots correctlyVotedHeadPct=99% correctlyVotedSourcePct=100% correctlyVotedTargetPct=100% numberOfEpochs=1473 pctChangeCombinedBalance=0.22637%
[2020-08-14 19:59:02]  INFO validator: Attestation schedule attesters=1 pubKeys=[0xb6d4b447520b] slot=74709
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1186808]

goroutine 144604 [running]:
github.com/prysmaticlabs/prysm/validator/client.isNewAttSlashable(0x0, 0x8f2, 0x91d, 0x2537140)
        validator/client/attest_protect.go:71 +0x38
github.com/prysmaticlabs/prysm/validator/client.(*validator).preAttSignValidations(0xc0001266e0, 0x195a5e0, 0xc00185c570, 0xc001d8bf80, 0xb0880b5247b4d4b6, 0xa64eccf4eeabed3a, 0x23fba5c9c2cd5c4c, 0x1f15ce36258c2dc1, 0x78363613e0fa3edf, 0xde12d9dd667fbb28, ...)
        validator/client/attest_protect.go:24 +0x1d9
github.com/prysmaticlabs/prysm/validator/client.(*validator).SubmitAttestation(0xc0001266e0, 0x195a5e0, 0xc00185c570, 0x123bd, 0xb0880b5247b4d4b6, 0xa64eccf4eeabed3a, 0x23fba5c9c2cd5c4c, 0x1f15ce36258c2dc1, 0x78363613e0fa3edf, 0xde12d9dd667fbb28)
        validator/client/attest.go:69 +0xc59
github.com/prysmaticlabs/prysm/validator/client.run.func1(0xc0019187f0, 0x1971820, 0xc0001266e0, 0x195a5a0, 0xc001dc5d40, 0x123bd, 0xc0017da770, 0x880b5247b4d4b601, 0x4eccf4eeabed3ab0, 0xfba5c9c2cd5c4ca6, ...)
        validator/client/runner.go:133 +0x1ea
created by github.com/prysmaticlabs/prysm/validator/client.run
        validator/client/runner.go:129 +0xd76
```

## 🌍  Your Environment

**Operating System:**

Ubuntu 20.04

**What version of Prysm are you running? (Which release)**
Git commit `859e59b6f7aa1eddc1f7abe359fd853b8f32a2cf`

**Comment by 0xKiwi** [comment]
Hello @Bobface , thank you for reporting this issue.

The commit you have reported to be running is pretty old, would you mind trying again from the latest head? The problem shouldn't be occurring anymore.

**Comment by Bobface** [comment]
Yes, I have updated to the latest head now. I'll see if it happens again!
