### ISSUE TITLE
eth2stats client causing beacon node runtime error when pulling for peers

### ISSUE THREAD

**Issue by KevinVitale** [prysmaticlabs/prysm#7034]
# 🐞 Bug Report

### Description

[I opened a ticket](https://github.com/Alethio/eth2stats-client/issues/53) on the _eth2stats_ first, not knowing if this was an issue for Prysm. **Please close it if it's an _eth2stats_ issue**. However, I looked at the logs of my beacon node and noticed the flood of runtime errors in the gRPC call (see below). These were being caused by the _eth2stats_ client trying to pull for peers.

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: ....

## 🔬 Minimal Reproduction

Run an _eth2stats_ client and connect it to your beacon node.

## 🔥 Error

```
beacon-chain  | time="2020-08-17 15:29:38" level=error msg="gRPC panicked!" error="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 3485295 [running]:
beacon-chain  | runtime/debug.Stack(0xc0000ea000, 0x5dffe7, 0x5)
beacon-chain  | 	GOROOT/src/runtime/debug/stack.go:24 +0x9d
beacon-chain  | github.com/prysmaticlabs/prysm/shared/traceutil.RecoveryHandlerFunc(0x9e60a0, 0xc095262b10, 0x3b4c80, 0x26bd590, 0xc0953a2860, 0xc012118000)
beacon-chain  | 	shared/traceutil/recovery_interceptor_option.go:29 +0x155
beacon-chain  | github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom(0x9e60a0, 0xc095262b10, 0x3b4c80, 0x26bd590, 0x7b2368, 0x7f6cebecaad0, 0x40010000000000)
beacon-chain  | 	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:53 +0x5a
beacon-chain  | github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1(0x9e60a0, 0xc095262b10, 0xc007cde018, 0xc081e23ab0)
beacon-chain  | 	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:27 +0x77
beacon-chain  | panic(0x3b4c80, 0x26bd590)
beacon-chain  | 	GOROOT/src/runtime/panic.go:969 +0x166
beacon-chain  | github.com/prysmaticlabs/prysm/beacon-chain/rpc/node.(*Server).ListPeers(0xc007cd8230, 0x9e60a0, 0xc095262ba0, 0xc0492625c0, 0xc007cd8230, 0xc0006484c0, 0x7b3af0)
beacon-chain  | 	beacon-chain/rpc/node/server.go:193 +0x325
beacon-chain  | github.com/prysmaticlabs/ethereumapis/eth/v1alpha1._Node_ListPeers_Handler.func1(0x9e60a0, 0xc095262ba0, 0x56c640, 0xc0492625c0, 0x3b2ee0, 0x284e868, 0x535880, 0x284e320)
beacon-chain  | 	bazel-out/k8-opt/bin/external/com_github_prysmaticlabs_ethereumapis/eth/v1alpha1/linux_amd64_stripped/go_proto%/github.com/prysmaticlabs/ethereumapis/eth/v1alpha1/node.pb.go:868 +0x86
beacon-chain  | github.com/prysmaticlabs/prysm/beacon-chain/rpc.(*Service).validatorUnaryConnectionInterceptor(0xc000648280, 0x9e60a0, 0xc095262ba0, 0x56c640, 0xc0492625c0, 0xc0492625e0, 0xc049262600, 0xc095262ba0, 0x9ff6e0, 0x284e320, ...)
beacon-chain  | 	beacon-chain/rpc/service.go:400 +0x77
beacon-chain  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x9e60a0, 0xc095262ba0, 0x56c640, 0xc0492625c0, 0x615a6e, 0x25, 0x9e60a0, 0xc095262ba0)
beacon-chain  | 	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x63
beacon-chain  | github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1(0x9e60a0, 0xc095262b10, 0x56c640, 0xc0492625c0, 0xc0492625e0, 0xc049262620, 0x3, 0x3, 0x9f1e80, 0xc054bfa8a0)
beacon-chain  | 	external/com_github_grpc_ecosystem_go_grpc_middleware/tracing/opentracing/server_interceptors.go:31 +0x165
beacon-chain  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x9e60a0, 0xc095262b10, 0x56c640, 0xc0492625c0, 0x25, 0xc0716fd090, 0xc0570b2120, 0x7f6dc9f88501)
beacon-chain  | 	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x63
beacon-chain  | github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x9e60a0, 0xc095262b10, 0x56c640, 0xc0492625c0, 0xc0492625e0, 0xc049262640, 0xc095262a20, 0xc02ff44a68, 0x15d8a96, 0xc049262680)
beacon-chain  | 	external/com_github_grpc_ecosystem_go_grpc_prometheus/server_metrics.go:107 +0xad
beacon-chain  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x9e60a0, 0xc095262b10, 0x56c640, 0xc0492625c0, 0x20, 0xc049262680, 0x203012, 0x203012)
beacon-chain  | 	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x63
beacon-chain  | github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1(0x9e60a0, 0xc095262b10, 0x56c640, 0xc0492625c0, 0xc0492625e0, 0xc049262660, 0x0, 0x0, 0x0, 0x0)
beacon-chain  | 	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:31 +0xbc
beacon-chain  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x9e60a0, 0xc095262b10, 0x56c640, 0xc0492625c0, 0xc0518f1200, 0xc049262580, 0xc02ff44b30, 0x15d9308)
beacon-chain  | 	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x63
beacon-chain  | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x9e60a0, 0xc095262b10, 0x56c640, 0xc0492625c0, 0xc0492625e0, 0xc049262600, 0xc02ff44ba0, 0x16f9c08, 0x4cccc0, 0xc095262b10)
beacon-chain  | 	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:34 +0xd5
beacon-chain  | github.com/prysmaticlabs/ethereumapis/eth/v1alpha1._Node_ListPeers_Handler(0x49e0e0, 0xc007cd8230, 0x9e60a0, 0xc095262b10, 0xc05575af60, 0xc007cd01b0, 0x9e60a0, 0xc095262b10, 0x0, 0x0)
beacon-chain  | 	bazel-out/k8-opt/bin/external/com_github_prysmaticlabs_ethereumapis/eth/v1alpha1/linux_amd64_stripped/go_proto%/github.com/prysmaticlabs/ethereumapis/eth/v1alpha1/node.pb.go:870 +0x14b
beacon-chain  | google.golang.org/grpc.(*Server).processUnaryRPC(0xc007ce4000, 0x9f99e0, 0xc05fd5bc80, 0xc0518f1200, 0xc007cd04e0, 0x26d4ff0, 0x0, 0x0, 0x0)
beacon-chain  | 	external/org_golang_google_grpc/server.go:1082 +0x50a
beacon-chain  | google.golang.org/grpc.(*Server).handleStream(0xc007ce4000, 0x9f99e0, 0xc05fd5bc80, 0xc0518f1200, 0x0)
beacon-chain  | 	external/org_golang_google_grpc/server.go:1405 +0xccb
beacon-chain  | google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc04c05e650, 0xc007ce4000, 0x9f99e0, 0xc05fd5bc80, 0xc0518f1200)
beacon-chain  | 	external/org_golang_google_grpc/server.go:746 +0xa1
beacon-chain  | created by google.golang.org/grpc.(*Server).serveStreams.func1
beacon-chain  | 	external/org_golang_google_grpc/server.go:744 +0xa1
beacon-chain  | "
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
  Ubuntu 18.04 LTS
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
  beacon-chain  | time="2020-08-17 13:46:52" level=info msg="Starting beacon node" prefix=node version="Prysm/v1.0.0-alpha.21/f193dc2f54a84ee63b014a1f3ce33c53f29f4aaf. Built at: 2020-08-17 08:49:31+00:00"
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by KevinVitale** [comment]
I retried eth2stats and this no longer seems to be an issue. Closing.
