### ISSUE TITLE
Crash on  shutdown

### ISSUE THREAD

**Issue by Belkaar** [prysmaticlabs/prysm#7054]
# 🐞 Bug Report

### Description

Got a crash during shutdown after finalize event.
Node reprocessed all blocks from 73xxx or something.

### Has this worked before in a previous version?

Don't know

## 🔬 Minimal Reproduction

Restart the node i guess. Not really reproducable for me, but I don't restart that often.

## 🔥 Error

<pre><code>
Aug 19 20:56:56 eth2-test prysm.sh[358]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 19 20:56:56 eth2-test prysm.sh[358]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1333454]
Aug 19 20:56:56 eth2-test prysm.sh[358]: goroutine 802969 [running]:
Aug 19 20:56:56 eth2-test prysm.sh[358]: github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).topicCollector(0x0, 0xc02d9891c0, 0x3a, 0x0, 0x0, 0x0)
Aug 19 20:56:56 eth2-test prysm.sh[358]:         beacon-chain/sync/rate_limiter.go:59 +0x44
Aug 19 20:56:56 eth2-test prysm.sh[358]: github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).beaconBlocksByRangeRPCHandler(0xc0006f8000, 0x1c97620, 0xc041752480, 0x1824e60, 0xc048cd7a00, 0x1cb0020, 0xc04ac97ce0, 0x0, 0x0)
Aug 19 20:56:56 eth2-test prysm.sh[358]:         beacon-chain/sync/rpc_beacon_blocks_by_range.go:54 +0x2c7
Aug 19 20:56:56 eth2-test prysm.sh[358]: github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).registerRPC.func1(0x1cb0020, 0xc04ac97ce0)
Aug 19 20:56:56 eth2-test prysm.sh[358]:         beacon-chain/sync/rpc.go:124 +0xeb0
Aug 19 20:56:56 eth2-test prysm.sh[358]: github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1(0xc02d9891c0, 0x3a, 0x7fe5d4b988b0, 0xc04ac97ce0, 0x1, 0x0)
Aug 19 20:56:56 eth2-test prysm.sh[358]:         external/com_github_libp2p_go_libp2p/p2p/host/basic/basic_host.go:566 +0x9d
Aug 19 20:56:56 eth2-test prysm.sh[358]: created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
Aug 19 20:56:56 eth2-test prysm.sh[358]:         external/com_github_libp2p_go_libp2p/p2p/host/basic/basic_host.go:416 +0x63c

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Debian, running node through systemd
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
alpha.23
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by 0xKiwi** [comment]
This looks like a bug with RPC blocks by range, any idea? @terencechain

**Comment by terencechain** [comment]
@0xKiwi I'm not too familiar with `RPC blocks by range`, while I certainly can look into this, perhaps there's a better owner?

**Comment by 0xKiwi** [comment]
Ah sorry, I think @nisdas is the owner? 
Also, this issue seems similar to #6897
