### ISSUE TITLE
Multiple Ctrl-C 's required to stop beacon chain.

### ISSUE THREAD

**Issue by Domintek** [prysmaticlabs/prysm#7296]
<
!--💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎

Hellooo! 😄 

To help us tend to your issue faster, please search our currently open issues before submitting a new one.
Existing issues often contain information about workarounds, resolution, or progress updates.

💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎-->

# 🐞 Bug Report

### Description

When I use Ctrl-C to stop my prysm.sh script, I have had to do multiple Ctrl-C's, 10 to 11 instances before the script stops.

### Has this worked before in a previous version? I never experienced this prior to the 9th of Sept 2020 and have been running Prysm consistently through all versions since January so have had experience with multiple hardware and Prysm versions.

 I first noticed it on the 9th of September 2020 with the latest version at the time.

## 🔬 Minimal Reproduction

 Starting script:   ./prysm.sh beacon-chain --http-web3provider=https://goerli.prylabs.net --p2p-max-peers=30 --clear-db

## 🔥 Error

<pre><code>

</code></pre>  
[2020-09-08 13:48:35]  INFO blockchain: Synced new block block=0x33b0c12e... epoch=7920 finalizedEpoch=7918 finalizedRoot=0xc0079c1a... slot=253442 slotInEpoch=2
[2020-09-08 13:48:35]  INFO blockchain: Finished applying state transition attestations=124 attesterSlashings=0 deposits=0 proposerSlashings=0 voluntaryExits=0
[2020-09-08 13:48:57]  INFO blockchain: Synced new block block=0xe71b4d0e... epoch=7920 finalizedEpoch=7918 finalizedRoot=0xc0079c1a... slot=253444 slotInEpoch=4
[2020-09-08 13:48:57]  INFO blockchain: Finished applying state transition attestations=54 attesterSlashings=0 deposits=0 proposerSlashings=0 voluntaryExits=0
^C[2020-09-08 13:49:07]  INFO node: Got interrupt, shutting down...
[2020-09-08 13:49:07]  INFO node: Stopping beacon node
[2020-09-08 13:49:07]  WARN sync: Subscription next failed error=context canceled topic=/eth2/e7a75d5a/beacon_block/ssz_snappy
[2020-09-08 13:49:07]  WARN sync: Subscription next failed error=context canceled topic=/eth2/e7a75d5a/beacon_aggregate_and_proof/ssz_snappy
[2020-09-08 13:49:07]  WARN sync: Subscription next failed error=context canceled topic=/eth2/e7a75d5a/proposer_slashing/ssz_snappy
[2020-09-08 13:49:07]  WARN sync: Subscription next failed error=context canceled topic=/eth2/e7a75d5a/attester_slashing/ssz_snappy
[2020-09-08 13:49:07]  WARN sync: Subscription next failed error=context canceled topic=/eth2/e7a75d5a/voluntary_exit/ssz_snappy
[2020-09-08 13:49:32]  INFO p2p: Peer disconnected activePeers=28 multiAddr=/ip4/3.14.66.221/tcp/9000/p2p/16Uiu2HAm8iWjrgA5GMGYx5jTJYcwGW8wkXu74J6tpkhmtPtSfqBn
[2020-09-08 13:49:37]  INFO p2p: Peer disconnected activePeers=27 multiAddr=/ip4/149.28.11.98/tcp/9000/p2p/16Uiu2HAmCvH5sWvpUeZywi8FitDtr5QJ7doYo8vGTS2sJKZkUj15
^C[2020-09-08 13:51:11]  INFO node: Already shutting down, interrupt more to panic times=9
^C[2020-09-08 13:51:27]  INFO node: Already shutting down, interrupt more to panic times=8
^C[2020-09-08 13:51:28]  INFO node: Already shutting down, interrupt more to panic times=7
^C[2020-09-08 13:51:28]  INFO node: Already shutting down, interrupt more to panic times=6
^C[2020-09-08 13:51:28]  INFO node: Already shutting down, interrupt more to panic times=5
^C[2020-09-08 13:51:29]  INFO node: Already shutting down, interrupt more to panic times=4
^C[2020-09-08 13:51:30]  INFO node: Already shutting down, interrupt more to panic times=3
^C[2020-09-08 13:51:31]  INFO node: Already shutting down, interrupt more to panic times=2
^C[2020-09-08 13:51:31]  INFO node: Already shutting down, interrupt more to panic times=1
^Cpanic: Panic closing the beacon node

goroutine 230 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/node.(*BeaconNode).Start.func1(0x40003080c0)
        beacon-chain/node/node.go:265 +0x2b0
created by github.com/prysmaticlabs/prysm/beacon-chain/node.(*BeaconNode).Start
        beacon-chain/node/node.go:251 +0x180

## 🌍  Your Environment

**Operating System:**  Raspberry Pi4 w/8gb ram with beacon node running on linux arm64. I had the same problem on a Win10 machine with 32 Gb ram running inside docker. The only change in the Win 10 set up is that max-peers=100. Eth2stats is running in docker on both machines which is where I noticed the declining peer numbers.

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)** Latest as of 9 September up to including Alpha 25

<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?** This problem seems to manifest itself when the beacon nodes peer count begins to decrease after running well for several days. It seems that the beacon node begins to lose peers, more than it picks up the loss out weighs the gain in peers. Usually when that happens, within 36 to 48 hours the peer count will drop about 70%, That is the point at which I restart the beacon node and noticed the multiple Ctrl-Cs required to stop the script. This spamming only seems to occur during the process of losing peers which may or not be related. This Ctrl-C spamming has happened three times since the 9th of September both on the Pi4 and the Win 10 nodes.

**Comment by shayzluf** [comment]
@farazdagi seems related to p2p , please reassign to me if you think its inappropriate

**Comment by farazdagi** [comment]
I've reviewed the code behind the functionality. This is how it was implemented:
- With termination signal (`Ctrl+C`) one is able to interrupt the program.
- Once interrupted, node starts to close all its services, sometimes it takes some time to close all routines (depending on the system load, and load within the application i.e. what app is doing at the moment).
- One is still able to force node's immediate shut down without any grace period, by repeatedly sending signals (x10 `Ctrl + C`).

So, the above-mentioned design is there intentionally: to allow graceful node shutdowns of all the services.

Closing this issue, as there's nothing actionable, atm. If it happens that node (on SIGTERM) never shuts down w/o multiple `Ctrl + C` (but give it several seconds, pls), feel free to reopen.

**Comment by farazdagi** [comment]
Further update: the issue with peer discovery should be solved in https://github.com/prysmaticlabs/prysm/pull/7434
