### ISSUE TITLE
Panic when goerli is stalled / down

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#7322]
# 🐞 Bug Report

### Description

Beacon chain experiences a panic in BlockTimeByHeight.

### Has this worked before in a previous version?

Yes, but unknown if this issue existed in prior version.

## 🔬 Minimal Reproduction

When goerli is down or stalled the error occurs. At the time of writing, Goerli has not seen a new block in over 15 minutes.

## 🔥 Error

<pre><code>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x24491b2]

goroutine 15561 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).BlockTimeByHeight(0xc000642900, 0x9f36c0, 0xc01386de40, 0xc0201161e0, 0x0, 0x0, 0x0)
        beacon-chain/powchain/block_reader.go:65 +0xd2
github.com/prysmaticlabs/prysm/beacon-chain/rpc/beacon.(*infostream).depositQueueTimestamp(0xc01f49e0d0, 0xc0201161e0, 0x30, 0x2d5380, 0xc0200d4290)
        beacon-chain/rpc/beacon/validators_stream.go:509 +0x3cb
github.com/prysmaticlabs/prysm/beacon-chain/rpc/beacon.(*infostream).generatePendingValidatorInfo(0xc01f49e0d0, 0xc014a17f80, 0x31f8c23f07e4d8da, 0x54609876776c111c, 0xa23f6be92d3c31f1)
        beacon-chain/rpc/beacon/validators_stream.go:355 +0x1ea
github.com/prysmaticlabs/prysm/beacon-chain/rpc/beacon.(*infostream).generateValidatorInfo(0xc01f49e0d0, 0xc01f545440, 0x30, 0x30, 0xc022904000, 0x67ec, 0x67ec, 0xc014a17f10, 0x27e, 0xc020116160, ...)
        beacon-chain/rpc/beacon/validators_stream.go:302 +0x30b
github.com/prysmaticlabs/prysm/beacon-chain/rpc/beacon.(*infostream).generateValidatorsInfo(0xc01f49e0d0, 0xc020116140, 0x1, 0x1, 0xc020116160, 0x20, 0x1, 0x0, 0x20)
        beacon-chain/rpc/beacon/validators_stream.go:276 +0x1fb
github.com/prysmaticlabs/prysm/beacon-chain/rpc/beacon.(*infostream).sendValidatorsInfo(0xc01f49e0d0, 0xc020116140, 0x1, 0x1, 0x1, 0xc020116160)
        beacon-chain/rpc/beacon/validators_stream.go:241 +0x53
github.com/prysmaticlabs/prysm/beacon-chain/rpc/beacon.(*infostream).handleAddValidatorKeys(0xc01f49e0d0, 0xc020116120, 0x1, 0x1, 0x15fea85, 0x43b740)
        beacon-chain/rpc/beacon/validators_stream.go:206 +0x3bd
github.com/prysmaticlabs/prysm/beacon-chain/rpc/beacon.(*infostream).handleMessage(0xc01f49e0d0, 0xc01e7dee00)
        beacon-chain/rpc/beacon/validators_stream.go:177 +0x292
github.com/prysmaticlabs/prysm/beacon-chain/rpc/beacon.(*infostream).handleConnection.func1(0xc01f49e0d0)
        beacon-chain/rpc/beacon/validators_stream.go:152 +0x4a
created by github.com/prysmaticlabs/prysm/beacon-chain/rpc/beacon.(*infostream).handleConnection
        beacon-chain/rpc/beacon/validators_stream.go:132 +0x57
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
any
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v1.0.0-alpha.26
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by prestonvanloon** [comment]
The offending line of code is 
https://github.com/prysmaticlabs/prysm/blob/5bfc4579045cb821b46b1bd4ee8a6b99310d1f1d/beacon-chain/powchain/block_reader.go#L65

It looks like the eth1DataFetcher was nil.
