### ISSUE TITLE
Panic during shutdown

### ISSUE THREAD

**Issue by yorickdowne** [prysmaticlabs/prysm#7580]
# 🐞 Bug Report

### Description

During shutdown, beacon panics with "Could not stop the following service: *blockchain.Service, could not get ancestor state: context canceled"

## 🔬 Minimal Reproduction

Start beacon

Stop beacon

## 🔥 Error

```
beacon_1            | time="2020-10-20 07:36:13" level=info msg="Synced new block" block=0x40ce5d1b... epoch=16960 finalizedEpoch=15614 finalizedRoot=0xb3806428... prefix=blockchain slot=542733 slotInEpoch=13
beacon_1            | time="2020-10-20 07:36:13" level=info msg="Finished applying state transition" attestations=128 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
beacon_1            | time="2020-10-20 07:36:13" level=info msg="Got interrupt, shutting down..." prefix=node
beacon_1            | time="2020-10-20 07:36:13" level=info msg="Stopping beacon node" prefix=node
beacon_1            | time="2020-10-20 07:36:13" level=info msg="Peer disconnected" activePeers=30 multiAddr="/ip4/49.198.236.47/tcp/13000/p2p/16Uiu2HAm9FUXDAANNo8SoPwsLZCiaEixrgwN4rTxGvoqvfdmf5ti" prefix=p2p
beacon_1            | time="2020-10-20 07:36:13" level=info msg="Peer disconnected" activePeers=29 multiAddr="/ip4/178.2.94.96/tcp/13000/p2p/16Uiu2HAmLizmmUtDSsKCEX3LcWCuV4YAn8Y2nGpbSYg5whFK5Gt8" prefix=p2p
beacon_1            | time="2020-10-20 07:36:13" level=info msg="Peer disconnected" activePeers=28 multiAddr="/ip4/5.194.213.175/tcp/13000/p2p/16Uiu2HAmU5Z6WJKnShEoFi7pcnzzhC2T69pyJKcucmXb58ps7J2W" prefix=p2p
beacon_1            | time="2020-10-20 07:36:13" level=panic msg="Could not stop the following service: *blockchain.Service, could not get ancestor state: context canceled" prefix=registry
beacon_1            | panic: (*logrus.Entry) (0x5eaf00,0xc0369c31f0)
beacon_1            |
beacon_1            | goroutine 5161348 [running]:
beacon_1            | github.com/sirupsen/logrus.Entry.log(0xc0001ea000, 0xc0001356e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
beacon_1            |   external/com_github_sirupsen_logrus/entry.go:259 +0x335
beacon_1            | github.com/sirupsen/logrus.(*Entry).Log(0xc0002d6000, 0x0, 0xc000e65ea0, 0x1, 0x1)
beacon_1            |   external/com_github_sirupsen_logrus/entry.go:287 +0xeb
beacon_1            | github.com/sirupsen/logrus.(*Entry).Logf(0xc0002d6000, 0x0, 0x64a063, 0x2c, 0xc000e65f20, 0x2, 0x2)
beacon_1            |   external/com_github_sirupsen_logrus/entry.go:333 +0xe2
beacon_1            | github.com/sirupsen/logrus.(*Entry).Panicf(...)
beacon_1            |   external/com_github_sirupsen_logrus/entry.go:371
beacon_1            | github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StopAll(0xc0003b9100)
beacon_1            |   shared/service_registry.go:57 +0x165
beacon_1            | github.com/prysmaticlabs/prysm/beacon-chain/node.(*BeaconNode).Close(0xc0000ac180)
beacon_1            |   beacon-chain/node/node.go:283 +0xdf
beacon_1            | created by github.com/prysmaticlabs/prysm/beacon-chain/node.(*BeaconNode).Start.func1
beacon_1            |   beacon-chain/node/node.go:262 +0x189
```

## 🌍  Your Environment

**Operating System:**

Ubuntu 20.04

**What version of Prysm are you running? (Which release)**

Prysm/v1.0.0-alpha.29/81b553a

**Comment by nisdas** [comment]
This is already tracked here #6924 , lets track the issue from there since this will be a duplicate.
