### ISSUE TITLE
Slasher DB backup not working on Windows 10

### ISSUE THREAD

**Issue by Cipioo** [prysmaticlabs/prysm#8070]
# 🐞 Bug Report

### Description
DB Backup is not working for the slasher on Windows 10.

### Has this worked before in a previous version?
No, this is a new enhancement as of 1.0.4

## 🔬 Minimal Reproduction

Run slasher with these flags: C:\prysm\prysm.bat slasher --enable-db-backup-webhook --db-backup-output-dir="D:\Slasher_Backup"

Data backup does not occur. Upon going to a web browser and visiting localhost:8082/db/backup you get a panic in the slasher logs.

## 🔥 Error

<pre><code>
2020/12/07 20:17:07 http: panic serving 127.0.0.1:61425: runtime error: invalid memory address or nil pointer dereference
goroutine 361 [running]:
net/http.(*conn).serve.func1(0xc00145a140)
        GOROOT/src/net/http/server.go:1801 +0x147
panic(0x1165460, 0x10566f0)
        GOROOT/src/runtime/panic.go:975 +0x499
github.com/prysmaticlabs/prysm/shared/backuputil.BackupHandler.func1(0x14206a0, 0xc0017b30a0, 0xc0000a6c00)
        shared/backuputil/http_backup_handler.go:22 +0xd2
net/http.HandlerFunc.ServeHTTP(0xc0002c93e0, 0x14206a0, 0xc0017b30a0, 0xc0000a6c00)
        GOROOT/src/net/http/server.go:2042 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc0002e2ac0, 0x14206a0, 0xc0017b30a0, 0xc0000a6c00)
        GOROOT/src/net/http/server.go:2417 +0x1b7
net/http.serverHandler.ServeHTTP(0xc00060a2a0, 0x14206a0, 0xc0017b30a0, 0xc0000a6c00)
        GOROOT/src/net/http/server.go:2843 +0xaa
net/http.(*conn).serve(0xc00145a140, 0x1422ce0, 0xc002868a40)
        GOROOT/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        GOROOT/src/net/http/server.go:2969 +0x36d
2020/12/07 20:17:07 http: panic serving 127.0.0.1:61426: runtime error: invalid memory address or nil pointer dereference
goroutine 506 [running]:
net/http.(*conn).serve.func1(0xc000110a00)
        GOROOT/src/net/http/server.go:1801 +0x147
panic(0x1165460, 0x10566f0)
        GOROOT/src/runtime/panic.go:975 +0x499
github.com/prysmaticlabs/prysm/shared/backuputil.BackupHandler.func1(0x14206a0, 0xc0017b3180, 0xc00021c900)
        shared/backuputil/http_backup_handler.go:22 +0xd2
net/http.HandlerFunc.ServeHTTP(0xc0002c93e0, 0x14206a0, 0xc0017b3180, 0xc00021c900)
        GOROOT/src/net/http/server.go:2042 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc0002e2ac0, 0x14206a0, 0xc0017b3180, 0xc00021c900)
        GOROOT/src/net/http/server.go:2417 +0x1b7
net/http.serverHandler.ServeHTTP(0xc00060a2a0, 0x14206a0, 0xc0017b3180, 0xc00021c900)
        GOROOT/src/net/http/server.go:2843 +0xaa
net/http.(*conn).serve(0xc000110a00, 0x1422ce0, 0xc0028f4040)
        GOROOT/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        GOROOT/src/net/http/server.go:2969 +0x36d
2020/12/07 20:17:07 http: panic serving 127.0.0.1:61427: runtime error: invalid memory address or nil pointer dereference
goroutine 364 [running]:
net/http.(*conn).serve.func1(0xc00145a320)
        GOROOT/src/net/http/server.go:1801 +0x147
panic(0x1165460, 0x10566f0)
        GOROOT/src/runtime/panic.go:975 +0x499
github.com/prysmaticlabs/prysm/shared/backuputil.BackupHandler.func1(0x14206a0, 0xc001b68fc0, 0xc0000a6d00)
        shared/backuputil/http_backup_handler.go:22 +0xd2
net/http.HandlerFunc.ServeHTTP(0xc0002c93e0, 0x14206a0, 0xc001b68fc0, 0xc0000a6d00)
        GOROOT/src/net/http/server.go:2042 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc0002e2ac0, 0x14206a0, 0xc001b68fc0, 0xc0000a6d00)
        GOROOT/src/net/http/server.go:2417 +0x1b7
net/http.serverHandler.ServeHTTP(0xc00060a2a0, 0x14206a0, 0xc001b68fc0, 0xc0000a6d00)
        GOROOT/src/net/http/server.go:2843 +0xaa
net/http.(*conn).serve(0xc00145a320, 0x1422ce0, 0xc002868b40)
        GOROOT/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        GOROOT/src/net/http/server.go:2969 +0x36d
2020/12/07 20:17:07 http: panic serving 127.0.0.1:61428: runtime error: invalid memory address or nil pointer dereference
goroutine 508 [running]:
net/http.(*conn).serve.func1(0xc000110dc0)
        GOROOT/src/net/http/server.go:1801 +0x147
panic(0x1165460, 0x10566f0)
        GOROOT/src/runtime/panic.go:975 +0x499
github.com/prysmaticlabs/prysm/shared/backuputil.BackupHandler.func1(0x14206a0, 0xc0017b3260, 0xc00021ca00)
        shared/backuputil/http_backup_handler.go:22 +0xd2
net/http.HandlerFunc.ServeHTTP(0xc0002c93e0, 0x14206a0, 0xc0017b3260, 0xc00021ca00)
        GOROOT/src/net/http/server.go:2042 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc0002e2ac0, 0x14206a0, 0xc0017b3260, 0xc00021ca00)
        GOROOT/src/net/http/server.go:2417 +0x1b7
net/http.serverHandler.ServeHTTP(0xc00060a2a0, 0x14206a0, 0xc0017b3260, 0xc00021ca00)
        GOROOT/src/net/http/server.go:2843 +0xaa
net/http.(*conn).serve(0xc000110dc0, 0x1422ce0, 0xc0028f4140)
        GOROOT/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        GOROOT/src/net/http/server.go:2969 +0x36d
2020/12/07 20:17:07 http: panic serving 127.0.0.1:61429: runtime error: invalid memory address or nil pointer dereference
goroutine 366 [running]:
net/http.(*conn).serve.func1(0xc00145a460)
        GOROOT/src/net/http/server.go:1801 +0x147
panic(0x1165460, 0x10566f0)
        GOROOT/src/runtime/panic.go:975 +0x499
github.com/prysmaticlabs/prysm/shared/backuputil.BackupHandler.func1(0x14206a0, 0xc0017b3340, 0xc000f6e200)
        shared/backuputil/http_backup_handler.go:22 +0xd2
net/http.HandlerFunc.ServeHTTP(0xc0002c93e0, 0x14206a0, 0xc0017b3340, 0xc000f6e200)
        GOROOT/src/net/http/server.go:2042 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc0002e2ac0, 0x14206a0, 0xc0017b3340, 0xc000f6e200)
        GOROOT/src/net/http/server.go:2417 +0x1b7
net/http.serverHandler.ServeHTTP(0xc00060a2a0, 0x14206a0, 0xc0017b3340, 0xc000f6e200)
        GOROOT/src/net/http/server.go:2843 +0xaa
net/http.(*conn).serve(0xc00145a460, 0x1422ce0, 0xc0028ba0c0)
        GOROOT/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        GOROOT/src/net/http/server.go:2969 +0x36d
2020/12/07 20:17:07 http: panic serving 127.0.0.1:61430: runtime error: invalid memory address or nil pointer dereference
goroutine 368 [running]:
net/http.(*conn).serve.func1(0xc00145a5a0)
        GOROOT/src/net/http/server.go:1801 +0x147
panic(0x1165460, 0x10566f0)
        GOROOT/src/runtime/panic.go:975 +0x499
github.com/prysmaticlabs/prysm/shared/backuputil.BackupHandler.func1(0x14206a0, 0xc003b2c460, 0xc000f6e300)
        shared/backuputil/http_backup_handler.go:22 +0xd2
net/http.HandlerFunc.ServeHTTP(0xc0002c93e0, 0x14206a0, 0xc003b2c460, 0xc000f6e300)
        GOROOT/src/net/http/server.go:2042 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc0002e2ac0, 0x14206a0, 0xc003b2c460, 0xc000f6e300)
        GOROOT/src/net/http/server.go:2417 +0x1b7
net/http.serverHandler.ServeHTTP(0xc00060a2a0, 0x14206a0, 0xc003b2c460, 0xc000f6e300)
        GOROOT/src/net/http/server.go:2843 +0xaa
net/http.(*conn).serve(0xc00145a5a0, 0x1422ce0, 0xc0028ba1c0)
        GOROOT/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        GOROOT/src/net/http/server.go:2969 +0x36d
2020/12/07 20:17:07 http: panic serving 127.0.0.1:61431: runtime error: invalid memory address or nil pointer dereference
goroutine 369 [running]:
net/http.(*conn).serve.func1(0xc00145a640)
        GOROOT/src/net/http/server.go:1801 +0x147
panic(0x1165460, 0x10566f0)
        GOROOT/src/runtime/panic.go:975 +0x499
github.com/prysmaticlabs/prysm/shared/backuputil.BackupHandler.func1(0x14206a0, 0xc003b2c540, 0xc000f6e400)
        shared/backuputil/http_backup_handler.go:22 +0xd2
net/http.HandlerFunc.ServeHTTP(0xc0002c93e0, 0x14206a0, 0xc003b2c540, 0xc000f6e400)
        GOROOT/src/net/http/server.go:2042 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc0002e2ac0, 0x14206a0, 0xc003b2c540, 0xc000f6e400)
        GOROOT/src/net/http/server.go:2417 +0x1b7
net/http.serverHandler.ServeHTTP(0xc00060a2a0, 0x14206a0, 0xc003b2c540, 0xc000f6e400)
        GOROOT/src/net/http/server.go:2843 +0xaa
net/http.(*conn).serve(0xc00145a640, 0x1422ce0, 0xc0028ba340)
        GOROOT/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        GOROOT/src/net/http/server.go:2969 +0x36d
2020/12/07 20:17:07 http: panic serving 127.0.0.1:61432: runtime error: invalid memory address or nil pointer dereference
goroutine 478 [running]:
net/http.(*conn).serve.func1(0xc00026afa0)
        GOROOT/src/net/http/server.go:1801 +0x147
panic(0x1165460, 0x10566f0)
        GOROOT/src/runtime/panic.go:975 +0x499
github.com/prysmaticlabs/prysm/shared/backuputil.BackupHandler.func1(0x14206a0, 0xc001b690a0, 0xc0000a6f00)
        shared/backuputil/http_backup_handler.go:22 +0xd2
net/http.HandlerFunc.ServeHTTP(0xc0002c93e0, 0x14206a0, 0xc001b690a0, 0xc0000a6f00)
        GOROOT/src/net/http/server.go:2042 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc0002e2ac0, 0x14206a0, 0xc001b690a0, 0xc0000a6f00)
        GOROOT/src/net/http/server.go:2417 +0x1b7
net/http.serverHandler.ServeHTTP(0xc00060a2a0, 0x14206a0, 0xc001b690a0, 0xc0000a6f00)
        GOROOT/src/net/http/server.go:2843 +0xaa
net/http.(*conn).serve(0xc00026afa0, 0x1422ce0, 0xc002868cc0)
        GOROOT/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        GOROOT/src/net/http/server.go:2969 +0x36d
2020/12/07 20:17:07 http: panic serving 127.0.0.1:61433: runtime error: invalid memory address or nil pointer dereference
goroutine 510 [running]:
net/http.(*conn).serve.func1(0xc000110fa0)
        GOROOT/src/net/http/server.go:1801 +0x147
panic(0x1165460, 0x10566f0)
        GOROOT/src/runtime/panic.go:975 +0x499
github.com/prysmaticlabs/prysm/shared/backuputil.BackupHandler.func1(0x14206a0, 0xc0017b3420, 0xc00021cb00)
        shared/backuputil/http_backup_handler.go:22 +0xd2
net/http.HandlerFunc.ServeHTTP(0xc0002c93e0, 0x14206a0, 0xc0017b3420, 0xc00021cb00)
        GOROOT/src/net/http/server.go:2042 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc0002e2ac0, 0x14206a0, 0xc0017b3420, 0xc00021cb00)
        GOROOT/src/net/http/server.go:2417 +0x1b7
net/http.serverHandler.ServeHTTP(0xc00060a2a0, 0x14206a0, 0xc0017b3420, 0xc00021cb00)
        GOROOT/src/net/http/server.go:2843 +0xaa
net/http.(*conn).serve(0xc000110fa0, 0x1422ce0, 0xc0028f42c0)
        GOROOT/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        GOROOT/src/net/http/server.go:2969 +0x36d
2020/12/07 20:17:07 http: panic serving 127.0.0.1:61434: runtime error: invalid memory address or nil pointer dereference
goroutine 515 [running]:
net/http.(*conn).serve.func1(0xc00145a780)
        GOROOT/src/net/http/server.go:1801 +0x147
panic(0x1165460, 0x10566f0)
        GOROOT/src/runtime/panic.go:975 +0x499
github.com/prysmaticlabs/prysm/shared/backuputil.BackupHandler.func1(0x14206a0, 0xc001b69180, 0xc0000a7100)
        shared/backuputil/http_backup_handler.go:22 +0xd2
net/http.HandlerFunc.ServeHTTP(0xc0002c93e0, 0x14206a0, 0xc001b69180, 0xc0000a7100)
        GOROOT/src/net/http/server.go:2042 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc0002e2ac0, 0x14206a0, 0xc001b69180, 0xc0000a7100)
        GOROOT/src/net/http/server.go:2417 +0x1b7
net/http.serverHandler.ServeHTTP(0xc00060a2a0, 0x14206a0, 0xc001b69180, 0xc0000a7100)
        GOROOT/src/net/http/server.go:2843 +0xaa
net/http.(*conn).serve(0xc00145a780, 0x1422ce0, 0xc002868ec0)
        GOROOT/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        GOROOT/src/net/http/server.go:2969 +0x36d
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
      Windows 10
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
   1.0.4
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by Cipioo** [comment]
Wanted to mention, I have since writing this also tried DB backup for Validator and Beacon and none were working.
