### ISSUE TITLE
fatal error: found pointer to free object

### ISSUE THREAD

**Issue by MaximilianMeister** [prysmaticlabs/prysm#8177]
# 🐞 Bug Report

### Description

beaconchain node went down with what looks like a memory error

### Has this worked before in a previous version?

Personally didn't see this issue yet in older versions

## 🔥 Error

1. It all started a day ago with this error in the beaconchain logs:

```
runtime: marked free object in span 0x7fc14c708d98, elemsize=32 freeindex=0 (bad use of unsafe.Pointer? try -d=checkptr)
```

2. followed by a couple of those errors:

```
0xc016ce2020 free  unmarked
0xc016ce2000 alloc marked
...
...
```

3. with this leading to a go stacktrace:

```
fatal error: found pointer to free object
goroutine 3 [running]:
runtime.throw(0x6330e3, 0x1c)
        GOROOT/src/runtime/panic.go:1116 +0x72 fp=0xc0000575d8 sp=0xc0000575a8 pc=0x1483732
runtime.(*mspan).reportZombies(0x7fc14c708d98)
        GOROOT/src/runtime/mgcsweep.go:827 +0x376 fp=0xc000057658 sp=0xc0000575d8 pc=0x1471876runtime.(*mspan).sweep(0x7fc14c708d98, 0x7fc14c708d00, 0x14b0700)
        GOROOT/src/runtime/mgcsweep.go:456 +0x4be fp=0xc000057740 sp=0xc000057658 pc=0x1470dderuntime.sweepone(0x7ea538)
        GOROOT/src/runtime/mgcsweep.go:233 +0x28d fp=0xc0000577a8 sp=0xc000057740 pc=0x14706edruntime.bgsweep(0xc00007e000)
        GOROOT/src/runtime/mgcsweep.go:166 +0xbe fp=0xc0000577d8 sp=0xc0000577a8 pc=0x147039e
runtime.goexit()
        GOROOT/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0000577e0 sp=0xc0000577d8 pc=0x14bc921
created by runtime.gcenable
        GOROOT/src/runtime/mgc.go:217 +0x5c
goroutine 1 [chan receive, 8269 minutes]:
github.com/prysmaticlabs/prysm/beacon-chain/node.(*BeaconNode).Start(0xc00132f550)
        beacon-chain/node/node.go:271 +0x1e5
main.startNode(0xc0013643c0, 0xc0003a5d00, 0x0)
        beacon-chain/main.go:214 +0xef
github.com/urfave/cli/v2.(*App).RunContext(0xc00027cd80, 0x99fbe0, 0xc000040018, 0xc00003c1e0, 0x6, 0x6, 0x0, 0x0)
        external/com_github_urfave_cli_v2/app.go:315 +0x70d
github.com/urfave/cli/v2.(*App).Run(...)
        external/com_github_urfave_cli_v2/app.go:215
main.main()
        beacon-chain/main.go:184 +0x21a
```

4. The beacon node then had quite a dent during that moment in memory usage. It dropped from 1.83GB down to 426MB, and then slowly recovered

![beacon-bug](https://user-images.githubusercontent.com/5364817/103140778-295aaf80-46eb-11eb-8bcd-0b04d50610f0.png)

5. The service was restarted by systemd, and ran for some more hours with a few of those errors in the logs in between

```
time="2020-12-24 21:55:23" level=info msg="Finished applying state transition" attestations=13 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-12-24 21:55:41" level=error msg="Panic occurred" error="runtime error: invalid memory address or nil pointer dereference" prefix=sync topic="/eth2/b5303f2a/beacon_block/ssz_snappy"
goroutine 163474 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        GOROOT/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
        GOROOT/src/runtime/debug/stack.go:16 +0x25
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).subscribeWithBase.func1.1(0xc01411ca00, 0xc008a8a070)
        beacon-chain/sync/subscriber.go:124 +0x1f0
panic(0x3c18a0, 0x27a3810)
        GOROOT/src/runtime/panic.go:969 +0x1b9
github.com/prysmaticlabs/ethereumapis/eth/v1alpha1.(*Deposit_Data).HashTreeRootWith(0x0, 0xc03be90480, 0xa71b8edba42b252d, 0xf4b3eae044f195e0)
        bazel-out/k8-opt/bin/external/com_github_prysmaticlabs_ethereumapis/eth/v1alpha1/generated.ssz.go:1749 +0x26
github.com/ferranbt/fastssz.HashWithDefaultHasher(0x981720, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)        external/com_github_ferranbt_fastssz/hasher.go:42 +0x79
github.com/prysmaticlabs/ethereumapis/eth/v1alpha1.(*Deposit_Data).HashTreeRoot(...)
        bazel-out/k8-opt/bin/external/com_github_prysmaticlabs_ethereumapis/eth/v1alpha1/generated.ssz.go:1741
github.com/prysmaticlabs/prysm/beacon-chain/cache/depositcache.(*DepositCache).InsertFinalizedDeposits(0xc0014a4050, 0x99fc60, 0xc004c6cf90, 0xf537)
        beacon-chain/cache/depositcache/deposits_cache.go:126 +0x191
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).onBlock(0xc00000cd20, 0x99fc60, 0xc004c6cf90, 0xc022b6ec00, 0x9b5dda45f8954ea7, 0x33d23735072d61e5, 0xe22b854d29199875, 0xc56f548c10b07cfb, 0x0, 0x0)
        beacon-chain/blockchain/process_block.go:139 +0x6dc
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveBlock(0xc00000cd20, 0x99fc60, 0xc004c6cf30, 0xc0265c4f80, 0x9b5dda45f8954ea7, 0x33d23735072d61e5, 0xe22b854d29199875, 0xc56f548c10b07cfb, 0x0, 0x0)
        beacon-chain/blockchain/receive_block.go:39 +0x136
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).beaconBlockSubscriber(0xc001135a00, 0x99fc60, 0xc004c6ce40, 0x9949e0, 0xc0265c4f80, 0x0, 0x9949e0)
        beacon-chain/sync/subscriber_beacon_blocks.go:32 +0x1b5
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).subscribeWithBase.func1(0xc004c6c570)
        beacon-chain/sync/subscriber.go:136 +0x26f
created by github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).subscribeWithBase.func2
        beacon-chain/sync/subscriber.go:163 +0xe5
```

6. Until it hit the wall and hasn't recovered anymore (systemd service kept restarting but failing)

```
time="2020-12-25 14:24:23" level=info msg="Finished applying state transition" attestations=22 attesterSlashings=0 deposits

panic: runtime error: index out of range [16320634820604461056] with length 281474976710655
goroutine 5764687 [running]:
go.etcd.io/bbolt.(*DB).page(...)
        external/io_etcd_go_bbolt/db.go:886
go.etcd.io/bbolt.(*Tx).page(...)
        external/io_etcd_go_bbolt/tx.go:618
go.etcd.io/bbolt.(*Tx).forEachPage(0xc00a5f5b20, 0xc42e27e8ae61f000, 0x2, 0xc009cfcb30)
        external/io_etcd_go_bbolt/tx.go:623 +0x14a
go.etcd.io/bbolt.(*Tx).forEachPage(0xc00a5f5b20, 0x337c5, 0x1, 0xc009cfcb30)
        external/io_etcd_go_bbolt/tx.go:632 +0xe5
go.etcd.io/bbolt.(*Tx).forEachPage(0xc00a5f5b20, 0x5f2, 0x0, 0xc009cfcb30)
        external/io_etcd_go_bbolt/tx.go:632 +0xe5
go.etcd.io/bbolt.(*Bucket).forEachPage(0xc039226440, 0xc009cfcb30)
        external/io_etcd_go_bbolt/bucket.go:488 +0x77
go.etcd.io/bbolt.(*Bucket).Stats(0xc039226440, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        external/io_etcd_go_bbolt/bucket.go:405 +0x165
github.com/prysmaticlabs/prombbolt.forEachWithBoltDB.func1.1.1(0x7f998b4a157c, 0x5, 0x5, 0xc039226440, 0xc039226440, 0x0)
        external/com_github_prysmaticlabs_prombbolt/bucketstatscollector.go:181 +0x4c
go.etcd.io/bbolt.(*Tx).ForEach.func1(0x7f998b4a157c, 0x5, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0)
        external/io_etcd_go_bbolt/tx.go:129 +0x8c
go.etcd.io/bbolt.(*Bucket).ForEach(0xc00a5f5b38, 0xc009cfcd40, 0x203005, 0x203005)
        external/io_etcd_go_bbolt/bucket.go:390 +0xfe
go.etcd.io/bbolt.(*Tx).ForEach(0xc00a5f5b20, 0xc009cfcd88, 0xc0001e2a00, 0xc00a5f5b20)
        external/io_etcd_go_bbolt/tx.go:128 +0x67
github.com/prysmaticlabs/prombbolt.forEachWithBoltDB.func1.1(0xc00a5f5b20, 0x7f9a68214300, 0xc00a5f5b20)
        external/com_github_prysmaticlabs_prombbolt/bucketstatscollector.go:177 +0x52
go.etcd.io/bbolt.(*DB).View(0xc0001e2a00, 0xc009cfce30, 0x0, 0x0)
        external/io_etcd_go_bbolt/db.go:725 +0x96
github.com/prysmaticlabs/prombbolt.forEachWithBoltDB.func1(0xc015e3a0c0, 0xc015e3a0c0, 0xc00146c310)
        external/com_github_prysmaticlabs_prombbolt/bucketstatscollector.go:176 +0x52
github.com/prysmaticlabs/prombbolt.(*bucketStatsCollector).Collect(0xc0003fc000, 0xc04a0bf140)        external/com_github_prysmaticlabs_prombbolt/bucketstatscollector.go:189 +0x6c
github.com/prysmaticlabs/prombbolt.(*collector).Collect(0xc0014911e0, 0xc04a0bf140)
        external/com_github_prysmaticlabs_prombbolt/prombolt.go:53 +0x8e
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        external/com_github_prometheus_client_golang/prometheus/registry.go:444 +0x1a2
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        external/com_github_prometheus_client_golang/prometheus/registry.go:455 +0x5ce
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux - Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v1.0.5
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

* There hasn't been any sign of memory shortage on the system at that point in time
* I have started a fresh (beaconchain) sync from scratch, as I assumed that the db was corrupted

**Comment by nisdas** [comment]
Those look like interesting errors, do you mind providing more details on the machine you were running on ? 
Ex: Computer Architecture, Memory, CPU used , etc 

The initial error signifies something deeply wrong with garbage collection pointing to some sort of memory corruption, which 
eventually leads to your database being corrupted. 

After the restart, do you see this issue anymore ?

**Comment by MaximilianMeister** [comment]
Thanks for looking into it

* x86
* Intel(R) Core(TM) i5 CPU 760  @ 2.80GHz
* 16GB RAM

Regarding the restart, during step 6 in the description you can see the error after restarting the service, it immediately crashed again and again.

My guess is that the hardware, especially the CPU might be too weak and could have led to this.

**Comment by nisdas** [comment]
> Regarding the restart, during step 6 in the description you can see the error after restarting the service, it immediately crashed again and again.

Sorry should have framed this better, I meant after you start with a fresh db. Do you still see the above errors ?

**Comment by MaximilianMeister** [comment]
> Sorry should have framed this better, I meant after you start with a fresh db. Do you still see the above errors ?

Can't say much about that unfortunately. After the fresh start, it took quite long to sync the beaconchain again, so I decided to switch the main environment to a different (more potent) host. I stopped the service again without waiting for it to be in full sync. But during this initial sync at least there haven't been any issues besides the long estimated time to finish the sync.

**Comment by nisdas** [comment]
> Can't say much about that unfortunately. After the fresh start, it took quite long to sync the beaconchain again, 

Oh that is wierd, syncing the beaconcha.in shouldn't take too long. How long did you wait to sync ?

**Comment by MaximilianMeister** [comment]
> Oh that is wierd, syncing the beaconcha.in shouldn't take too long. How long did you wait to sync ?

Yes that was quite unexpected for me too. IIRC i was waiting about 2 hours and there was still 1.5 hours or so estimated. I really think this might be due to the weak CPU specs, as I also ran Geth at the same time (also still syncing and taking way too long already). I also [had issues with geth on that node](https://github.com/ethereum/go-ethereum/issues/21917).

My guess is that the [minimum hardware specs](https://docs.prylabs.network/docs/install/install-with-script/#minimum-specifications) could be announced a bit higher. But this is just a guess, as I havent done any meaningful benchmark here.

**Comment by nisdas** [comment]
Oh that is very interesting, so you had the same exact error in geth as in prysm.
```
Nov 25 15:56:39 validator geth[51005]: fatal error: found pointer to free object
Nov 25 15:56:39 validator geth[51005]: goroutine 3 [running]:
Nov 25 15:56:39 validator geth[51005]: runtime.throw(0x13482fa, 0x1c)
Nov 25 15:56:39 validator geth[51005]:         runtime/panic.go:1116 +0x72 fp=0xc00004d5d8 sp=0xc00004d5a8 pc=0x454032
Nov 25 15:56:39 validator geth[51005]: runtime.(*mspan).reportZombies(0x7f0e55434a10)
Nov 25 15:56:39 validator geth[51005]:         runtime/mgcsweep.go:827 +0x376 fp=0xc00004d658 sp=0xc00004d5d8 pc=0x4424b6
Nov 25 15:56:39 validator geth[51005]: runtime.(*mspan).sweep(0x7f0e55434a10, 0x7f0e55434a00, 0x480f00)
Nov 25 15:56:39 validator geth[51005]:         runtime/mgcsweep.go:456 +0x4be fp=0xc00004d740 sp=0xc00004d658 pc=0x441a1e
Nov 25 15:56:39 validator geth[51005]: runtime.sweepone(0x1407830)
Nov 25 15:56:39 validator geth[51005]:         runtime/mgcsweep.go:233 +0x28d fp=0xc00004d7a8 sp=0xc00004d740 pc=0x44132d
Nov 25 15:56:39 validator geth[51005]: runtime.bgsweep(0xc000074000)
Nov 25 15:56:39 validator geth[51005]:         runtime/mgcsweep.go:166 +0xbe fp=0xc00004d7d8 sp=0xc00004d7a8 pc=0x440fde
Nov 25 15:56:39 validator geth[51005]: runtime.goexit()
Nov 25 15:56:39 validator geth[51005]:         runtime/asm_amd64.s:1374 +0x1 fp=0xc00004d7e0 sp=0xc00004d7d8 pc=0x48cda1
Nov 25 15:56:39 validator geth[51005]: created by runtime.gcenable
Nov 25 15:56:39 validator geth[51005]:         runtime/mgc.go:217 +0x5c
Nov 25 15:56:39 validator geth[51005]: goroutine 1 [chan receive, 203 minutes]:
Nov 25 15:56:39 validator geth[51005]: github.com/ethereum/go-ethereum/node.(*Node).Wait(...)
Nov 25 15:56:39 validator geth[51005]:         github.com/ethereum/go-ethereum/node/node.go:407
Nov 25 15:56:39 validator geth[51005]: main.geth(0xc0002262c0, 0x0, 0x0)
Nov 25 15:56:39 validator geth[51005]:         github.com/ethereum/go-ethereum/cmd/geth/main.go:358 +0x157
Nov 25 15:56:39 validator geth[51005]: gopkg.in/urfave/cli%2ev1.HandleAction(0x1156940, 0x1406fe8, 0xc0002262c0, 0xc0001c4ae0, 0x0)
Nov 25 15:56:39 validator geth[51005]:         gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0x82
Nov 25 15:56:39 validator geth[51005]: gopkg.in/urfave/cli%2ev1.(*App).Run(0xc00024e820, 0xc000032080, 0x4, 0x4, 0x0, 0x0)
Nov 25 15:56:39 validator geth[51005]:         gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x5f5
```
The above error is linked in the issue, and it also is pretty much the same exact stack trace. Your hardware specs that you are running on are more than enough. I run on a more restricted machine and still haven't seen the errors you have encountered. If i had to guess this might be an issue with your underlying hardware. 

If its possible could you boot to your BIOS and run the hardware tests that they have ? If there are any obvious issues, it should come up in those checks.

**Comment by MaximilianMeister** [comment]
> If its possible could you boot to your BIOS and run the hardware tests that they have ? If there are any obvious issues, it should come up in those checks.

Thanks for the hint, I have only done some runtime checks on the disk, which were OK. I'll probably not be able to boot into BIOS as it's managed by another provider and running on top of OpenStack ... I guess I just got a borked piece of hardware. I'll close the issue. Feel free to reopen it if you think it still has to be investigated somehow
