### ISSUE TITLE
beacon chain crash regression since 1.3.2 on aarch64

### ISSUE THREAD

**Issue by adrianschroeter** [prysmaticlabs/prysm#8547]
### Description

beaconchain process is crashing during startup since 1.3.2 on an Raspberry Pi4 running openSUSE aarch64.

### Has this worked before in a previous version?

v1.3.1 worked before and also after downgrade.

## 🔬 Minimal Reproduction

direct after startup after ~ 1 minute:

Mär 03 08:24:28 pi4 beacon-chain-v1[27060]: Processing block 0xe2c155a4... 661312/661320 - estimated time remaining 2m40s
Mär 03 08:24:29 pi4 bash[27060]: unexpected fault address 0x5adfe2d1b007e02c
Mär 03 08:24:29 pi4 bash[27060]: fatal error: fault
Mär 03 08:24:29 pi4 bash[27060]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x5adfe2d1b007e02c pc=0x1c5aa00]
Mär 03 08:24:29 pi4 bash[27060]: goroutine 174 [running]:
Mär 03 08:24:29 pi4 bash[27060]: runtime.throw(0x5d9465, 0x5)
Mär 03 08:24:29 pi4 bash[27060]:         GOROOT/src/runtime/panic.go:1117 +0x54 fp=0x40172a4340 sp=0x40172a4310 pc=0x13b28f4
Mär 03 08:24:29 pi4 bash[27060]: runtime.sigpanic()
Mär 03 08:24:29 pi4 bash[27060]:         GOROOT/src/runtime/signal_unix.go:741 +0x230 fp=0x40172a4380 sp=0x40172a4340 pc=0x13ca500
Mär 03 08:24:29 pi4 bash[27060]: github.com/golang/snappy.encodeBlock(0x40100f5002, 0x4a95, 0x4a95, 0x401729a000, 0x3fd4, 0x3fd4, 0x0)
Mär 03 08:24:29 pi4 bash[27060]:         external/com_github_golang_snappy/encode_arm64.s:666 +0x360 fp=0x40172ac420 sp=0x40172a4390 pc=0x1c5aa00
Mär 03 08:24:29 pi4 bash[27060]: github.com/golang/snappy.Encode(0x40100f5000, 0x4a97, 0x4a97, 0x0, 0x0, 0x0, 0x0, 0x964578, 0x401986d890)
Mär 03 08:24:29 pi4 bash[27060]:         external/com_github_golang_snappy/encode.go:39 +0x17c fp=0x40172ac470 sp=0x40172ac420 pc=0x1c5968c
Mär 03 08:24:29 pi4 bash[27060]: github.com/prysmaticlabs/prysm/beacon-chain/db/kv.encode(0x964578, 0x401986d740, 0x95af28, 0x4010662640, 0x0, 0x0, 0x0, 0x0, 0x0)
Mär 03 08:24:29 pi4 bash[27060]:         beacon-chain/db/kv/encoding.go:50 +0x1e8 fp=0x40172ac500 sp=0x40172ac470 pc=0x1c63588
Mär 03 08:24:29 pi4 bash[27060]: github.com/prysmaticlabs/prysm/beacon-chain/db/kv.(*Store).SaveBlocks.func1(0x4002d79420, 0x1, 0x4002d79420)
Mär 03 08:24:29 pi4 bash[27060]:         beacon-chain/db/kv/blocks.go:270 +0x1dc fp=0x40172ac620 sp=0x40172ac500 pc=0x1c6c57c
Mär 03 08:24:29 pi4 bash[27060]: go.etcd.io/bbolt.(*DB).Update(0x40004fc800, 0x40078746f0, 0x0, 0x0)
Mär 03 08:24:29 pi4 bash[27060]:         external/io_etcd_go_bbolt/db.go:694 +0x88 fp=0x40172ac690 sp=0x40172ac620 pc=0x1ab76f8
Mär 03 08:24:29 pi4 bash[27060]: github.com/prysmaticlabs/prysm/beacon-chain/db/kv.(*Store).SaveBlocks(0x40012c7f80, 0x964578, 0x401986d710, 0x4007874810, 0x1, 0x1, 0x0, 0x0)
Mär 03 08:24:29 pi4 bash[27060]:         beacon-chain/db/kv/blocks.go:259 +0xd8 fp=0x40172ac740 sp=0x40172ac690 pc=0x1c60a88
Mär 03 08:24:29 pi4 bash[27060]: github.com/prysmaticlabs/prysm/beacon-chain/db/kv.(*Store).SaveBlock(0x40012c7f80, 0x964578, 0x401986d710, 0x4010662640, 0x0, 0x0)
Mär 03 08:24:29 pi4 bash[27060]:         beacon-chain/db/kv/blocks.go:251 +0x1a4 fp=0x40172ac830 sp=0x40172ac740 pc=0x1c60924
Mär 03 08:24:29 pi4 bash[27060]: github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).savePostStateInfo(0x40000fc3c0, 0x964578, 0x401986d6e0, 0x8605c032a455c1e2, 0x13e865bc43007423, 0xc5624d8a1c922627, 0x8e70bb1253923e49, 0x4010662640, 0x4007125e30, 0x401065c000, ...)
Mär 03 08:24:29 pi4 bash[27060]:         beacon-chain/blockchain/process_block.go:389 +0x2a0 fp=0x40172ac8e0 sp=0x40172ac830 pc=0x20db170
Mär 03 08:24:29 pi4 bash[27060]: github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).onBlock(0x40000fc3c0, 0x964578, 0x401b366150, 0x4010662640, 0x8605c032a455c1e2, 0x13e865bc43007423, 0xc5624d8a1c922627, 0x8e70bb1253923e49, 0x0, 0x0)
Mär 03 08:24:29 pi4 bash[27060]:         beacon-chain/blockchain/process_block.go:109 +0x2a8 fp=0x40172acc20 sp=0x40172ac8e0 pc=0x20d8d68
Mär 03 08:24:29 pi4 bash[27060]: github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveBlock(0x40000fc3c0, 0x9644d0, 0x401b366120, 0x401057f9c0, 0x8605c032a455c1e2, 0x13e865bc43007423, 0xc5624d8a1c922627, 0x8e70bb1253923e49, 0x0, 0x0)
Mär 03 08:24:29 pi4 bash[27060]:         beacon-chain/blockchain/receive_block.go:41 +0x108 fp=0x40172ace70 sp=0x40172acc20 pc=0x20dfad8
Mär 03 08:24:29 pi4 bash[27060]: github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.blockchainService.ReceiveBlock-fm(0x9644d0, 0x4007869880, 0x401057f9c0, 0x8605c032a455c1e2, 0x13e865bc43007423, 0xc5624d8a1c922627, 0x8e70bb1253923e49, 0xc5624d8a1c922600, 0x8e70bb1253923e49)
Mär 03 08:24:29 pi4 bash[27060]:         beacon-chain/sync/initial-sync/service.go:31 +0x6c fp=0x40172aced0 sp=0x40172ace70 pc=0x21eab4c
Mär 03 08:24:29 pi4 bash[27060]: github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processBlock(0x4000469180, 0x9644d0, 0x4007869880, 0x0, 0xed7582757, 0x24cada0, 0x401057f9c0, 0x4007875150, 0x932170, 0x400e9c16e0)
Mär 03 08:24:29 pi4 bash[27060]:         beacon-chain/sync/initial-sync/round_robin.go:239 +0x300 fp=0x40172ad020 sp=0x40172aced0 pc=0x21e6380
Mär 03 08:24:29 pi4 bash[27060]: github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processFetchedDataRegSync(0x4000469180, 0x9644d0, 0x4007869880, 0x0, 0xed7582757, 0x24cada0, 0xa173f, 0x401986ca80)
Mär 03 08:24:29 pi4 bash[27060]:         beacon-chain/sync/initial-sync/round_robin.go:146 +0x12c fp=0x40172ad690 sp=0x40172ad020 pc=0x21e4fbc
Mär 03 08:24:29 pi4 bash[27060]: github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).syncToNonFinalizedEpoch(0x4000469180, 0x9644d0, 0x4007869880, 0x0, 0xed7582757, 0x24cada0, 0x0, 0x0)
Mär 03 08:24:29 pi4 bash[27060]:         beacon-chain/sync/initial-sync/round_robin.go:114 +0x150 fp=0x40172ada20 sp=0x40172ad690 pc=0x21e48a0
Mär 03 08:24:29 pi4 bash[27060]: github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync(0x4000469180, 0x0, 0xed7582757, 0x24cada0, 0x0, 0x0)
Mär 03 08:24:29 pi4 bash[27060]:         beacon-chain/sync/initial-sync/round_robin.go:60 +0x228 fp=0x40172adab0 sp=0x40172ada20 pc=0x21e4138
Mär 03 08:24:29 pi4 bash[27060]: github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).Start(0x4000469180)
Mär 03 08:24:29 pi4 bash[27060]:         beacon-chain/sync/initial-sync/service.go:112 +0x678 fp=0x40172adfd0 sp=0x40172adab0 pc=0x21e7808
Mär 03 08:24:29 pi4 bash[27060]: runtime.goexit()
Mär 03 08:24:29 pi4 bash[27060]:         src/runtime/asm_arm64.s:1130 +0x4 fp=0x40172adfd0 sp=0x40172adfd0 pc=0x13ea454
Mär 03 08:24:29 pi4 bash[27060]: created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
Mär 03 08:24:29 pi4 bash[27060]:         shared/service_registry.go:46 +0x1c4
Mär 03 08:24:29 pi4 bash[27060]: goroutine 1 [chan receive, 1 minutes]:
Mär 03 08:24:29 pi4 bash[27060]: github.com/prysmaticlabs/prysm/beacon-chain/node.(*BeaconNode).Start(0x40000c0b40)
Mär 03 08:24:29 pi4 bash[27060]:         beacon-chain/node/node.go:272 +0x190
Mär 03 08:24:29 pi4 bash[27060]: main.startNode(0x40012c7d40, 0x0, 0x0)
Mär 03 08:24:29 pi4 bash[27060]:         beacon-chain/main.go:225 +0x180
Mär 03 08:24:29 pi4 bash[27060]: github.com/urfave/cli/v2.(*App).RunContext(0x40002ed500, 0x964508, 0x4000142010, 0x4000148000, 0xf, 0xf, 0x0, 0x0)
Mär 03 08:24:29 pi4 bash[27060]:         external/com_github_urfave_cli_v2/app.go:315 +0x520
Mär 03 08:24:29 pi4 bash[27060]: github.com/urfave/cli/v2.(*App).Run(...)
Mär 03 08:24:29 pi4 bash[27060]:         external/com_github_urfave_cli_v2/app.go:215
Mär 03 08:24:29 pi4 bash[27060]: main.main()
Mär 03 08:24:29 pi4 bash[27060]:         beacon-chain/main.go:188 +0x1d4
Mär 03 08:24:29 pi4 bash[27060]: goroutine 21 [select, 1 minutes]:

**Comment by adrianschroeter** [comment]
I saw it already reported now .... it was too obvious on top and not in the list ...
