### ISSUE TITLE
v1.3.3: Prysm crashes on startup; illegal instruction

### ISSUE THREAD

**Issue by zi0r** [prysmaticlabs/prysm#8622]
# 🐞 Bug Report

### Description

<pre>
  <code>
SIGILL: illegal instruction
PC=0x25b0593 m=0 sigcode=5
signal arrived during cgo execution
instruction bytes: 0xf3 0x48 0xf 0x38 0xf6 0xc8 0x66 0x4d 0xf 0x38 0xf6 0xc6 0xc4 0x42 0xfb 0xf6

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x2534ba0, 0xc00024b728, 0xc000118300)
        /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc00024b6f8 sp=0xc00024b6c0 pc=0x13943db
github.com/herumi/bls-eth-go-binary/bls._Cfunc_blsInit(0xf600000005, 0xc000000000)
        _cgo_gotypes.go:417 +0x48 fp=0xc00024b728 sp=0xc00024b6f8 pc=0x1b29908
github.com/herumi/bls-eth-go-binary/bls.Init(0x5, 0x0, 0x0)
        /wrkdirs/usr/ports/net-p2p/go-prysm/work/prysm-1.3.3/vendor/github.com/herumi/bls-eth-go-binary/bls/bls.go:63 +0x45 fp=0xc00024b780 sp=0xc00024b728 pc=0x1b2bf45
github.com/prysmaticlabs/prysm/shared/bls/herumi.init.0()
        /wrkdirs/usr/ports/net-p2p/go-prysm/work/prysm-1.3.3/shared/bls/herumi/init.go:6 +0x2e fp=0xc00024b7a8 sp=0xc00024b780 pc=0x1b7652e
runtime.doInit(0x2606d60)
        /usr/local/go/src/runtime/proc.go:6265 +0xec fp=0xc00024b8f8 sp=0xc00024b7a8 pc=0x13d928c
runtime.doInit(0x2600280)
        /usr/local/go/src/runtime/proc.go:6242 +0x72 fp=0xc00024ba48 sp=0xc00024b8f8 pc=0x13d9212
runtime.doInit(0x2610480)
        /usr/local/go/src/runtime/proc.go:6242 +0x72 fp=0xc00024bb98 sp=0xc00024ba48 pc=0x13d9212
runtime.doInit(0x2619060)
        /usr/local/go/src/runtime/proc.go:6242 +0x72 fp=0xc00024bce8 sp=0xc00024bb98 pc=0x13d9212
runtime.doInit(0x2619700)
        /usr/local/go/src/runtime/proc.go:6242 +0x72 fp=0xc00024be38 sp=0xc00024bce8 pc=0x13d9212
runtime.doInit(0x26121e0)
        /usr/local/go/src/runtime/proc.go:6242 +0x72 fp=0xc00024bf88 sp=0xc00024be38 pc=0x13d9212
runtime.main()
        /usr/local/go/src/runtime/proc.go:208 +0x205 fp=0xc00024bfe0 sp=0xc00024bf88 pc=0x13cb625
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00024bfe8 sp=0xc00024bfe0 pc=0x1402d81

goroutine 19 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc000236600)
        /wrkdirs/usr/ports/net-p2p/go-prysm/work/prysm-1.3.3/vendor/github.com/dgraph-io/ristretto/policy.go:96 +0xa5
created by github.com/dgraph-io/ristretto.newDefaultPolicy
        /wrkdirs/usr/ports/net-p2p/go-prysm/work/prysm-1.3.3/vendor/github.com/dgraph-io/ristretto/policy.go:80 +0x129

goroutine 20 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc00014b440)
        /wrkdirs/usr/ports/net-p2p/go-prysm/work/prysm-1.3.3/vendor/github.com/dgraph-io/ristretto/cache.go:314 +0xbd
created by github.com/dgraph-io/ristretto.NewCache
        /wrkdirs/usr/ports/net-p2p/go-prysm/work/prysm-1.3.3/vendor/github.com/dgraph-io/ristretto/cache.go:162 +0x22f

rax    0x1641c197c797d174
rbx    0x0
rcx    0xe9be3e6838682e8c
rdx    0x27c40feacb23745c
rdi    0x829ec4690
rsi    0x7fffffffe250
rbp    0x0
rsp    0x7fffffffe1f0
r8     0x1
r9     0x0
r10    0x0
r11    0x2798270
r12    0x0
r13    0x7fffffffe258
r14    0x1ce44bcc87acea26
r15    0x25afe50
rip    0x25b0593
rflags 0x10246
cs     0x43
fs     0x13
gs     0x1b
  </code>
</pre>

### Has this worked before in a previous version?

Unknown, this is the first version I've tried to use.  It seems very similar to issue 8410

## 🔬 Minimal Reproduction

TBD

## 🔥 Error

<pre>
  <code>
SIGILL: illegal instruction
PC=0x25b0593 m=0 sigcode=5
signal arrived during cgo execution
instruction bytes: 0xf3 0x48 0xf 0x38 0xf6 0xc8 0x66 0x4d 0xf 0x38 0xf6 0xc6 0xc4 0x42 0xfb 0xf6

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x2534ba0, 0xc00024b728, 0xc000118300)
        /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc00024b6f8 sp=0xc00024b6c0 pc=0x13943db
github.com/herumi/bls-eth-go-binary/bls._Cfunc_blsInit(0xf600000005, 0xc000000000)
        _cgo_gotypes.go:417 +0x48 fp=0xc00024b728 sp=0xc00024b6f8 pc=0x1b29908
github.com/herumi/bls-eth-go-binary/bls.Init(0x5, 0x0, 0x0)
        /wrkdirs/usr/ports/net-p2p/go-prysm/work/prysm-1.3.3/vendor/github.com/herumi/bls-eth-go-binary/bls/bls.go:63 +0x45 fp=0xc00024b780 sp=0xc00024b728 pc=0x1b2bf45
github.com/prysmaticlabs/prysm/shared/bls/herumi.init.0()
        /wrkdirs/usr/ports/net-p2p/go-prysm/work/prysm-1.3.3/shared/bls/herumi/init.go:6 +0x2e fp=0xc00024b7a8 sp=0xc00024b780 pc=0x1b7652e
runtime.doInit(0x2606d60)
        /usr/local/go/src/runtime/proc.go:6265 +0xec fp=0xc00024b8f8 sp=0xc00024b7a8 pc=0x13d928c
runtime.doInit(0x2600280)
        /usr/local/go/src/runtime/proc.go:6242 +0x72 fp=0xc00024ba48 sp=0xc00024b8f8 pc=0x13d9212
runtime.doInit(0x2610480)
        /usr/local/go/src/runtime/proc.go:6242 +0x72 fp=0xc00024bb98 sp=0xc00024ba48 pc=0x13d9212
runtime.doInit(0x2619060)
        /usr/local/go/src/runtime/proc.go:6242 +0x72 fp=0xc00024bce8 sp=0xc00024bb98 pc=0x13d9212
runtime.doInit(0x2619700)
        /usr/local/go/src/runtime/proc.go:6242 +0x72 fp=0xc00024be38 sp=0xc00024bce8 pc=0x13d9212
runtime.doInit(0x26121e0)
        /usr/local/go/src/runtime/proc.go:6242 +0x72 fp=0xc00024bf88 sp=0xc00024be38 pc=0x13d9212
runtime.main()
        /usr/local/go/src/runtime/proc.go:208 +0x205 fp=0xc00024bfe0 sp=0xc00024bf88 pc=0x13cb625
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00024bfe8 sp=0xc00024bfe0 pc=0x1402d81

goroutine 19 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc000236600)
        /wrkdirs/usr/ports/net-p2p/go-prysm/work/prysm-1.3.3/vendor/github.com/dgraph-io/ristretto/policy.go:96 +0xa5
created by github.com/dgraph-io/ristretto.newDefaultPolicy
        /wrkdirs/usr/ports/net-p2p/go-prysm/work/prysm-1.3.3/vendor/github.com/dgraph-io/ristretto/policy.go:80 +0x129

goroutine 20 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc00014b440)
        /wrkdirs/usr/ports/net-p2p/go-prysm/work/prysm-1.3.3/vendor/github.com/dgraph-io/ristretto/cache.go:314 +0xbd
created by github.com/dgraph-io/ristretto.NewCache
        /wrkdirs/usr/ports/net-p2p/go-prysm/work/prysm-1.3.3/vendor/github.com/dgraph-io/ristretto/cache.go:162 +0x22f

rax    0x1641c197c797d174
rbx    0x0
rcx    0xe9be3e6838682e8c
rdx    0x27c40feacb23745c
rdi    0x829ec4690
rsi    0x7fffffffe250
rbp    0x0
rsp    0x7fffffffe1f0
r8     0x1
r9     0x0
r10    0x0
r11    0x2798270
r12    0x0
r13    0x7fffffffe258
r14    0x1ce44bcc87acea26
r15    0x25afe50
rip    0x25b0593
rflags 0x10246
cs     0x43
fs     0x13
gs     0x1b

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
FreeBSD 122R-test2 12.2-RELEASE-p3 FreeBSD 12.2-RELEASE-p3 amd64
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
1.3.3
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

<pre>
  <code>
# go version
go version go1.16.2 freebsd/amd64
  </code>
</pre>

<pre>
  <code>
CPU: Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz (2300.00-MHz K8-class CPU)
  Origin="GenuineIntel"  Id=0x306f2  Family=0x6  Model=0x3f  Stepping=2
  Features=0x1f83fbff<FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,MMX,FXSR,SSE,SSE2,SS,HTT>
  Features2=0xfffa3203<SSE3,PCLMULQDQ,SSSE3,FMA,CX16,PCID,SSE4.1,SSE4.2,x2APIC,MOVBE,POPCNT,TSCDLT,AESNI,XSAVE,OSXSAVE,AVX,F16C,RDRAND,HV>
  AMD Features=0x2c100800<SYSCALL,NX,Page1GB,RDTSCP,LM>
  AMD Features2=0x21<LAHF,ABM>
  Structured Extended Features=0x27ab<FSGSBASE,TSCADJ,BMI1,AVX2,SMEP,BMI2,ERMS,INVPCID,NFPUSG>
  Structured Extended Features3=0xbc000400<MD_CLEAR,IBPB,STIBP,L1DFL,ARCH_CAP,SSBD>
  XSAVE Features=0x1<XSAVEOPT>
  IA32_ARCH_CAPS=0xc<RSBA,SKIP_L1DFL_VME>
  TSC: P-state invariant
Hypervisor: Origin = "VMwareVMware"
  </code>
</pre>

**Comment by zi0r** [comment]
After doing some spelunking, it looks like the underlying cause is two issues:
- herumi/bls-eth-go-binary has a typo in herumi/bls-eth-go-binary/blob/master/bls/bls.go:
<pre><code>#cgo freebsd,amd64 LDFLAGS:-L${SRCDIR}/lib/linux/amd64</code></pre>
- prysm does not build herumi/bls-eth-go-binary and just brings in their pre-built archives.  In this case, the Linux one.

I've got an initial version of a FreeBSD port created and will add it to the ports tree after some additional testing.  I'll also open a PR for the typo fix for herumi/bls-eth-go-binary.

Ignoring the above, so far, it appears as if prysm v1.3.3 runs fine under FreeBSD.

**Comment by zi0r** [comment]
Upstream PR submitted: [herumi/bls-eth-go-binary/pull/35](https://github.com/herumi/bls-eth-go-binary/pull/35)
